import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: 1,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the output of the following code?",
    code: `int x = 5;\nif (x = 10) {\n    std::cout << x;\n}`,
    options: ["0", "Compilation error", "5", "10"],
    correctIndex: 3,
    explanation:
      "x = 10 is an assignment, not a comparison. It assigns 10 to x and evaluates to 10 (truthy), so the body executes and prints 10.",
    link: "https://www.learncpp.com/cpp-tutorial/if-statements-and-blocks/",
  },
  {
    id: 2,
    difficulty: "Medium",
    topic: "Fundamentals",
    question:
      "Given void modify(int& a, int b) { a = 10; b = 20; } and calling with x=1, y=2, what are x and y after the call?",
    code: `void modify(int& a, int b) { a = 10; b = 20; }\n\nint x = 1, y = 2;\nmodify(x, y);`,
    options: ["x=10, y=20", "x=10, y=2", "x=1, y=20", "x=1, y=2"],
    correctIndex: 1,
    explanation:
      "a is passed by reference so the original x is modified. b is passed by value so y is unchanged.",
    link: "https://www.learncpp.com/cpp-tutorial/pass-by-lvalue-reference/",
  },
  {
    id: 422,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the difference between a declaration and a definition in C++?",
    options: [
      "A declaration tells the compiler a name exists and its type; a definition provides the actual implementation or allocates storage",
      "Declarations are only for functions and must appear in headers; definitions are only for variables and must appear in .cpp files",
      "They are the same thing",
      "A declaration allocates memory on the stack or heap; a definition merely introduces the name without reserving any storage",
    ],
    correctIndex: 0,
    explanation:
      "A declaration introduces a name (e.g., extern int x; or void f();). A definition provides the actual entity (e.g., int x = 5; or void f() { ... }). Every definition is a declaration, but not every declaration is a definition.",
    link: "https://www.learncpp.com/cpp-tutorial/forward-declarations/",
  },
  {
    id: 423,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the output of this code?",
    code: `int a = 10;\nint b = 3;\nstd::cout << a / b;`,
    options: ["3.0", "Compilation error", "3.33", "3"],
    correctIndex: 3,
    explanation:
      "When both operands of / are integers, C++ performs integer division, which truncates the decimal part. 10 / 3 = 3 (not 3.33). To get floating-point division, at least one operand must be a float or double.",
    link: "https://www.learncpp.com/cpp-tutorial/arithmetic-operators/",
  },
  {
    id: 424,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What does the const qualifier mean when applied to a variable?",
    code: `const int MAX = 100;\nMAX = 200;  // What happens?`,
    options: [
      "The variable can only be modified inside the function that declares it, but not outside that scope",
      "The variable is stored in read-only memory at runtime, so modification causes a segfault instead",
      "The variable cannot be modified after initialization",
      "The variable becomes a preprocessor macro, expanded and replaced with its literal value at each use",
    ],
    correctIndex: 2,
    explanation:
      "const makes a variable immutable after initialization. Any attempt to modify it results in a compilation error. Unlike #define, const variables have proper type checking and scoping.",
    link: "https://www.learncpp.com/cpp-tutorial/const-variables-and-symbolic-constants/",
  },
  {
    id: 425,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the difference between ++i (pre-increment) and i++ (post-increment)?",
    options: [
      "++i is faster because it skips the actual increment and returns the original value unmodified",
      "i++ increments by 2; ++i increments by 1, so they produce different values after repeated use",
      "No difference -- they always produce the same result and compilers optimize both to identical code",
      "++i increments and returns the new value; i++ returns the old value and then increments",
    ],
    correctIndex: 3,
    explanation:
      "Pre-increment (++i) modifies i and evaluates to the new value. Post-increment (i++) saves the old value, increments i, and evaluates to the saved old value. For built-in types the performance is identical, but for iterators/objects, pre-increment avoids creating a temporary copy.",
    link: "https://www.learncpp.com/cpp-tutorial/increment-decrement-operators-and-side-effects/",
  },
  {
    id: 426,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the purpose of a header file in C++?",
    options: [
      "To define the main() function and provide the program entry point that the operating system invokes at startup",
      "To store compiled object code that the linker reads during the final linking phase of the build process",
      "To share declarations across multiple source files so they can reference each other",
      "To store runtime configuration data such as environment variables, locale settings, and user preferences",
    ],
    correctIndex: 2,
    explanation:
      "Header files (.h / .hpp) contain declarations and are #included into source files (.cpp). This lets multiple translation units see the same class definitions, function prototypes, and constants without duplicating code.",
    link: "https://www.learncpp.com/cpp-tutorial/header-files/",
  },
  {
    id: 427,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the difference between a pointer and a reference in C++?",
    options: [
      "They are interchangeable",
      "References are always faster than pointers because the compiler resolves them at compile time, eliminating all runtime indirection",
      "Pointers are used for stack variables; references are used exclusively for heap variables that require indirection through the allocator",
      "A pointer holds an address and can be null or reassigned; a reference is an alias that must be initialized and cannot be reseated",
    ],
    correctIndex: 3,
    explanation:
      "A pointer is a variable that stores an address -- it can be null, reassigned, or used with pointer arithmetic. A reference is an alias for an existing object -- it must be initialized at declaration and always refers to the same object. Under the hood, references are often implemented as pointers.",
    link: "https://www.learncpp.com/cpp-tutorial/lvalue-references/",
  },
  {
    id: 428,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What does the auto keyword do in C++11 and later?",
    code: `auto x = 42;\nauto y = 3.14;\nauto z = std::string("hello");`,
    options: [
      "Makes the variable mutable and allows it to be modified even if it appears inside a const-qualified scope",
      "Asks the compiler to deduce the variable's type from its initializer",
      "Makes the variable dynamically typed like Python, so the type can change at runtime depending on what value is assigned",
      "Allocates the variable on the heap automatically and returns a managed pointer that is freed when the scope ends",
    ],
    correctIndex: 1,
    explanation:
      "auto tells the compiler to deduce the type from the initializer expression. The type is fixed at compile time (it's still statically typed). auto reduces verbosity, especially with complex types like iterators.",
    link: "https://www.learncpp.com/cpp-tutorial/the-auto-keyword/",
  },
  {
    id: 429,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What is the value of sizeof(char) in C++ on every platform?",
    options: [
      "Implementation-defined",
      "8 -- one byte is always 8 bits",
      "Depends on whether the platform is 32-bit or 64-bit",
      "Always 1 -- by definition, sizeof(char) is 1 byte",
    ],
    correctIndex: 3,
    explanation:
      "The C++ standard defines sizeof(char) as exactly 1. A 'byte' in C++ is defined as the size of a char. Note that a byte is not necessarily 8 bits (CHAR_BIT may vary on exotic platforms), but sizeof(char) is always 1.",
    link: "https://en.cppreference.com/w/cpp/language/sizeof.html",
  },
  {
    id: 430,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What does the break statement do inside a switch?",
    code: `switch (x) {\n    case 1: std::cout << "one";\n    case 2: std::cout << "two";\n    case 3: std::cout << "three"; break;\n}`,
    options: [
      "Exits the program immediately by calling std::exit, terminating all active threads and flushing output buffers",
      "Without break, execution falls through to the next case. If x is 1, this prints 'onetwothree'. break exits the switch",
      "break is optional and has no effect",
      "break causes a compilation error in a switch because control flow is managed automatically by the compiler",
    ],
    correctIndex: 1,
    explanation:
      "In C++, switch cases fall through by default -- execution continues into the next case unless stopped by break. If x is 1, all three cases execute. This is a common source of bugs. C++17's [[fallthrough]] attribute documents intentional fall-through.",
    link: "https://www.learncpp.com/cpp-tutorial/switch-statement-basics/",
  },
  {
    id: 431,
    difficulty: "Easy",
    topic: "Fundamentals",
    question: "What does the & operator do in these two different contexts?",
    code: `int x = 10;\nint* p = &x;    // context 1\nint& r = x;     // context 2`,
    options: [
      "Both create references",
      "Both create pointers",
      "In context 1, & is the address-of operator. In context 2, & declares a reference",
      "Context 1 is bitwise AND that computes a mask from x; context 2 is the address-of operator that stores x's memory location",
    ],
    correctIndex: 2,
    explanation:
      "The & symbol has different meanings depending on context. As a unary operator on an expression (&x), it takes the address. In a declaration (int& r), it declares a reference. This is a common point of confusion for C++ beginners.",
    link: "https://www.learncpp.com/cpp-tutorial/lvalue-references/",
  },
  {
    id: 432,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What is the output of this code?",
    code: `int arr[] = {10, 20, 30, 40, 50};\nint* p = arr + 2;\nstd::cout << p[-1] << " " << *p << " " << p[1];`,
    options: [
      "20 30 40",
      "30 40 50",
      "Undefined behavior",
      "10 20 30",
    ],
    correctIndex: 0,
    explanation:
      "p points to arr[2] (value 30). p[-1] is *(p-1) = arr[1] = 20. *p is arr[2] = 30. p[1] is *(p+1) = arr[3] = 40. Negative indexing is valid as long as it stays within the array bounds.",
    link: "https://www.learncpp.com/cpp-tutorial/pointer-arithmetic-and-subscripting/",
  },
  {
    id: 433,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What is the difference between #include <header> and #include \"header\"?",
    options: [
      "Angle brackets search system/standard include paths first; quotes search the local project directory first, then fall back to system paths",
      "No difference -- they are interchangeable, and the preprocessor resolves both forms to the same search path on all compilers",
      "Quotes are for C headers (.h files); angle brackets are for C++ headers",
      "Angle brackets are for forward declarations that the linker will resolve; quotes are for full definitions that must be available during compilation",
    ],
    correctIndex: 0,
    explanation:
      "The #include <...> form searches implementation-defined system directories (e.g., /usr/include, standard library headers). The #include \"...\" form searches the source file's directory first, then falls back to the system paths. Use quotes for your own headers and angle brackets for library/system headers.",
    link: "https://www.learncpp.com/cpp-tutorial/header-files/",
  },
  {
    id: 434,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What is undefined behavior (UB) in C++ and why is it dangerous?",
    options: [
      "Code that produces a compiler warning but works correctly at runtime",
      "Code that throws an exception at runtime, which can be caught with a try/catch block to recover gracefully from the error",
      "Code that produces implementation-defined results across compilers",
      "Code that violates the language rules",
    ],
    correctIndex: 3,
    explanation:
      "UB means the C++ standard imposes no requirements. The compiler may assume UB never happens and optimize accordingly. This can cause time-travel bugs -- code before the UB may be affected. Common UB: signed overflow, null deref, out-of-bounds access, use-after-free.",
    link: "https://en.cppreference.com/w/cpp/language/ub.html",
  },
  {
    id: 435,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What is the output of this code?",
    code: `unsigned int a = 1;\nint b = -1;\nif (a > b) {\n    std::cout << "a is greater";\n} else {\n    std::cout << "b is greater";\n}`,
    options: [
      "Compilation error",
      "a is greater -- the signed int -1 is treated as a small negative number, so 1 is clearly larger in the comparison",
      "b is greater -- because -1 is implicitly converted to a large unsigned value (4294967295 on 32-bit)",
      "Undefined behavior",
    ],
    correctIndex: 2,
    explanation:
      "When comparing signed and unsigned integers of the same rank, the signed value is implicitly converted to unsigned. -1 becomes UINT_MAX (the largest unsigned value), so the comparison becomes 1 > 4294967295, which is false. This is a classic C++ pitfall.",
    link: "https://www.learncpp.com/cpp-tutorial/arithmetic-conversions/",
  },
  {
    id: 436,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What is the One Definition Rule (ODR)?",
    options: [
      "Each class can only have one constructor",
      "Each function can only have one return statement",
      "Each source file can only define one class, and that class name must match the filename, similar to Java's file-naming convention",
      "Every entity must have exactly one definition in the entire program. Multiple definitions cause linker errors. Inline functions and templates are exceptions",
    ],
    correctIndex: 3,
    explanation:
      "The ODR requires exactly one definition of each non-inline function/variable across all translation units. Violating it (e.g., defining a function in a header without inline) causes linker errors (multiple definitions). Classes, inline functions, and templates may appear in multiple TUs but must be identical.",
    link: "https://en.cppreference.com/w/cpp/language/definition.html",
  },
  {
    id: 437,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What does this code do and what is the output?",
    code: `int x = 5;\nint y = x++ + ++x;\nstd::cout << y;`,
    options: [
      "10 -- both increments apply before the addition, so x becomes 7, and the expression evaluates to 5 + 5 = 10",
      "Undefined behavior",
      "11 -- post-increment yields 5 and pre-increment yields 6, so the sum is 5 + 6 = 11 under strict left-to-right sequencing",
      "12 -- post-increment returns the original 5 and pre-increment produces 7, giving 5 + 7 = 12 under left-to-right evaluation",
    ],
    correctIndex: 1,
    explanation:
      "Modifying the same variable more than once in a single expression without sequencing between the modifications is undefined behavior. The compiler may evaluate x++ and ++x in any order, and the result is unpredictable. Never write code like this.",
    link: "https://en.cppreference.com/w/cpp/language/eval_order.html",
  },
  {
    id: 438,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What is the difference between a C-style array and a pointer to its first element?",
    code: `int arr[5] = {1, 2, 3, 4, 5};\nint* p = arr;\n\nstd::cout << sizeof(arr) << " " << sizeof(p);`,
    options: [
      "Compilation error",
      "Both print the same value because an array decays to a pointer, so sizeof always returns the pointer size for both expressions regardless of the original declaration",
      "sizeof(arr) is 5 and sizeof(p) is 1",
      "sizeof(arr) is 20 (5 ints × 4 bytes) but sizeof(p) is 8",
    ],
    correctIndex: 3,
    explanation:
      "An array and a pointer are different types. sizeof(arr) returns the total size of the array in bytes. sizeof(p) returns the size of a pointer. Arrays decay to pointers when passed to functions, losing size information -- this is called array-to-pointer decay.",
    link: "https://www.learncpp.com/cpp-tutorial/arrays-and-pointers/",
  },
  {
    id: 439,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What are lvalues and rvalues in C++?",
    options: [
      "lvalues are local variables allocated on the stack frame; rvalues are remote variables stored on the heap and accessed through indirection",
      "lvalues are variables that appear on the left side of an assignment; rvalues are constants or literals that can only appear on the right side",
      "An lvalue identifies a persistent object with an address. An rvalue is a temporary value that does not persist beyond the expression",
      "lvalues are values computed at compile time by constexpr evaluation; rvalues are values computed at runtime during program execution",
    ],
    correctIndex: 2,
    explanation:
      "An lvalue (locator value) refers to an object that occupies identifiable memory -- you can take its address. An rvalue is a temporary (e.g., 42, x + y, f() returning by value). This distinction is fundamental to move semantics: rvalues can be moved from since they're about to be destroyed.",
    link: "https://www.learncpp.com/cpp-tutorial/value-categories-lvalues-and-rvalues/",
  },
  {
    id: 440,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What happens when an enum without a fixed underlying type has this code?",
    code: `enum Color { RED, GREEN, BLUE };\nint x = RED;        // OK?\nColor c = 1;        // OK?\nColor d = GREEN;    // OK?`,
    options: [
      "All are valid only with enum class, which enables bidirectional implicit conversion between integers and enumerators",
      "x = RED is valid. c = 1 is invalid. d = GREEN is valid",
      "All three are valid",
      "None are valid -- enums are distinct types that cannot be assigned to or from any other type without explicit conversion",
    ],
    correctIndex: 1,
    explanation:
      "Unscoped enums implicitly convert TO int (x = RED is fine). But int does NOT implicitly convert to an enum -- c = 1 requires a cast: c = static_cast<Color>(1). This asymmetry is one reason C++11 introduced enum class, which prevents both implicit conversions.",
    link: "https://www.learncpp.com/cpp-tutorial/unscoped-enumerations/",
  },
  {
    id: 441,
    difficulty: "Medium",
    topic: "Fundamentals",
    question: "What does constexpr mean on a function?",
    code: `constexpr int square(int x) {\n    return x * x;\n}\n\nconstexpr int val = square(5);  // evaluated at compile time\nint runtime = square(n);        // evaluated at runtime if n is not constexpr`,
    options: [
      "The function is always inlined at every call site, eliminating the overhead of a function call and stack frame setup",
      "The function cannot have any side effects at all and is restricted to pure arithmetic with no memory access or I/O",
      "The function can only be called at compile time",
      "The function CAN be evaluated at compile time if given constant arguments, but can also run at runtime with non-constant arguments",
    ],
    correctIndex: 3,
    explanation:
      "constexpr functions are evaluated at compile time when called with constant expressions (required in constexpr contexts like array sizes). They can also be called with runtime values, behaving like normal functions. This makes them flexible for both compile-time and runtime use.",
    link: "https://www.learncpp.com/cpp-tutorial/constexpr-and-consteval-functions/",
  },
  {
    id: 442,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What does the strict aliasing rule prohibit, and why?",
    code: `float f = 3.14f;\nint* p = reinterpret_cast<int*>(&f);\nstd::cout << *p;  // UB?`,
    options: [
      "Defined behavior",
      "Legal -- reinterpret_cast makes it safe to read through any pointer type by instructing the compiler to bypass all type-checking rules for that access, producing well-defined results that correspond to the raw bit pattern",
      "Undefined behavior",
      "Compilation error",
    ],
    correctIndex: 2,
    explanation:
      "The strict aliasing rule says you can only access an object through a pointer to its actual type (or char*). Reading a float through an int* is UB. The compiler uses this rule to avoid redundant loads -- it assumes writes through int* can't affect float values. Use memcpy or std::bit_cast for safe type punning.",
    link: "https://en.cppreference.com/w/cpp/language/reinterpret_cast.html",
  },
  {
    id: 443,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the difference between implementation-defined behavior and undefined behavior?",
    options: [
      "Undefined behavior always crashes the program immediately with a diagnostic message; implementation-defined behavior never crashes but may produce different outputs depending on the compiler vendor's documented choices",
      "Implementation-defined: the compiler must choose a consistent behavior and document it. Undefined behavior: the standard imposes no requirements",
      "Implementation-defined applies to hardware-level details like register sizes and word widths; undefined applies to software-level mistakes like logic errors in code, such as incorrect loop conditions or wrong assignments",
      "They are the same",
    ],
    correctIndex: 1,
    explanation:
      "Implementation-defined behavior has a guaranteed-consistent result per compiler -- the compiler documents its choice (e.g., right-shifting a negative int). Undefined behavior has NO guarantees -- the compiler may assume it never happens and optimize accordingly, leading to unpredictable results.",
    link: "https://en.cppreference.com/w/cpp/language/ub.html",
  },
  {
    id: 444,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the output of this code?",
    code: `#include <cstdint>\nint8_t x = 127;\nx += 1;\nstd::cout << static_cast<int>(x);`,
    options: [
      "0 -- signed overflow saturates to the maximum value and then resets to zero, following the modular arithmetic rules of C++",
      "128 -- the value increments normally to 128, which fits in an int8_t because the range extends to 128 on modern two's complement hardware",
      "-128 -- signed integer overflow wraps around, but technically this is undefined behavior for signed types",
      "Compilation error",
    ],
    correctIndex: 2,
    explanation:
      "int8_t is a signed 8-bit type with range -128 to 127. Adding 1 to 127 causes signed overflow, which is undefined behavior in C++. In practice on two's complement systems, it wraps to -128, but the compiler is free to optimize based on the assumption that signed overflow never occurs.",
    link: "https://en.cppreference.com/w/cpp/language/ub.html",
  },
  {
    id: 445,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the purpose of std::forward and when do you use it?",
    code: `template<typename T>\nvoid wrapper(T&& arg) {\n    target(std::forward<T>(arg));\n}`,
    options: [
      "It preserves the value category of the original argument",
      "It casts the argument to const& so the called function receives a read-only reference regardless of the original value category, preventing modifications inside the target",
      "It creates a deep copy of the argument to ensure the original caller's data is never modified by the target function, preserving value semantics across the forwarding boundary at the cost of a copy",
      "It always moves the argument into the target function, exactly like std::move, converting every argument to an rvalue reference regardless of its original value category in the calling context",
    ],
    correctIndex: 0,
    explanation:
      "std::forward is used in forwarding references (T&&). If an lvalue was passed, T is deduced as T& and forward returns an lvalue reference. If an rvalue was passed, T is deduced as T and forward returns an rvalue reference. This lets wrapper() pass args to target() with the same value category the caller used.",
    link: "https://en.cppreference.com/w/cpp/utility/forward.html",
  },
  {
    id: 446,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the difference between a translation unit and a source file?",
    options: [
      "A translation unit is a compiled object file (.o) containing machine code and symbol tables, produced after the compilation phase completes",
      "A source file compiles into multiple translation units, one for each function defined in the file, each compiled independently",
      "A translation unit is a source file (.cpp) AFTER all #include directives and macros have been expanded",
      "They are the same thing",
    ],
    correctIndex: 2,
    explanation:
      "The preprocessor expands all #includes, macros, and conditional compilation directives, producing a single flat stream of code called a translation unit. This is what the compiler parses and compiles into an object file. Understanding this helps explain ODR violations and include-order bugs.",
    link: "https://en.cppreference.com/w/cpp/language/translation_phases.html",
  },
  {
    id: 447,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What does this structured binding do and how does it work?",
    code: `std::map<std::string, int> scores = {{\"Alice\", 90}, {\"Bob\", 85}};\nfor (const auto& [name, score] : scores) {\n    std::cout << name << ": " << score << "\\n";\n}`,
    options: [
      "The structured binding [name, score] decomposes each std::pair<const string, int> into its two members. The compiler creates hidden references to .first and .second -- no copies are made because of const auto&",
      "Compilation error -- you can't destructure map entries because std::pair is not an aggregate type and lacks the required get<> specialization, so structured bindings cannot decompose pair objects in range-based for loops",
      "This only works with tuples, not pairs -- std::pair does not support structured bindings because it predates the C++17 standard and was never updated with the required decomposition interface for binding support",
      "name and score are copies of the pair elements, allocated on the stack each iteration, because structured bindings always copy by default -- you need to use std::ref() to create references instead of copies in the binding",
    ],
    correctIndex: 0,
    explanation:
      "Structured bindings (C++17) decompose an object into its named parts. For std::pair, [name, score] binds to .first and .second. For structs, it binds to members in declaration order. For arrays, to each element. With const auto&, these are references -- no copying.",
    link: "https://en.cppreference.com/w/cpp/language/structured_binding.html",
  },
  {
    id: 448,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the difference between linkage types: no linkage, internal linkage, and external linkage?",
    options: [
      "No linkage: the name is only visible in its scope. Internal linkage: visible within the translation unit only. External linkage: visible across translation units",
      "Internal linkage means the function is inline and expanded at every call site without generating a standalone symbol; external linkage means it uses a regular function call through the linker with a global symbol visible to all object files",
      "Linkage only applies to functions, not variables",
      "They control whether a variable is on the stack, heap, or static memory",
    ],
    correctIndex: 0,
    explanation:
      "Linkage determines if a name can be referred to from other translation units. Local variables have no linkage. static at file scope or anonymous namespace gives internal linkage (private to the TU). Non-static functions/globals have external linkage (the linker can see them across files).",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 449,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What does this code output, and what rule governs the evaluation?",
    code: `int i = 0;\nstd::cout << i << " " << ++i << " " << ++i;`,
    options: [
      "Unspecified -- the order of evaluation of function arguments is unspecified before C++17. In C++17, << is left-to-right sequenced, so the output is 0 1 2",
      "Undefined behavior regardless of standard version",
      "0 1 2 -- the << operator always evaluates its operands strictly left to right in every version of the C++ standard, because operator overloads follow the same fixed sequencing rules as built-in operators",
      "2 2 2 -- all increments happen before any output because the compiler evaluates all side effects before executing the << chain, as side effects are always fully resolved before expression evaluation begins",
    ],
    correctIndex: 0,
    explanation:
      "Before C++17, the evaluation order of operands to << was unspecified (not undefined -- it's safe, but the order varies between compilers). C++17 mandates left-to-right evaluation for << chains, making the output deterministic: 0 1 2. In pre-C++17 code, you might see 1 2 2 or 2 2 2.",
    link: "https://en.cppreference.com/w/cpp/language/eval_order.html",
  },
  {
    id: 450,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the difference between narrowing and non-narrowing conversions?",
    code: `int x = 3.14;          // narrowing: double to int (OK in C++, warns)\nint y{3.14};           // narrowing: PROHIBITED by brace initialization\nint z{42};             // non-narrowing: OK`,
    options: [
      "Narrowing only applies to pointer conversions, such as casting a derived pointer to a base pointer where the vtable layout changes, not to arithmetic conversions between numeric types like int and double which are always safe",
      "Brace initialization and = initialization follow the same conversion rules",
      "No difference -- all conversions are allowed in all contexts, and the compiler applies implicit casts automatically regardless of initialization syntax, with brace and equals initialization following identical type-checking rules",
      "A narrowing conversion loses information. Brace initialization {} prohibits narrowing conversions at compile time, while = initialization only warns",
    ],
    correctIndex: 3,
    explanation:
      "Brace initialization (uniform initialization) was introduced in C++11 partly to catch narrowing conversions. int y{3.14} is a compilation error because the double-to-int conversion loses the .14. This makes {} safer than = for catching accidental data loss.",
    link: "https://www.learncpp.com/cpp-tutorial/narrowing-conversions-list-initialization-and-constexpr-initializers/",
  },
  {
    id: 451,
    difficulty: "Hard",
    topic: "Fundamentals",
    question: "What is the difference between constexpr, consteval, and constinit?",
    options: [
      "constexpr is for functions that return compile-time values; consteval is for variables that hold compile-time data with immutable storage; constinit is for class types that need static storage duration with guaranteed constant initialization",
      "They are all synonyms for compile-time constants",
      "constexpr: can be evaluated at compile time OR runtime. consteval (C++20): MUST be evaluated at compile time. constinit (C++20): guarantees compile-time initialization of a static/thread_local variable but does NOT make it const",
      "constinit and consteval are deprecated aliases for constexpr, kept only for backward compatibility with early C++20 drafts and scheduled for removal in C++26",
    ],
    correctIndex: 2,
    explanation:
      "constexpr is dual-use (compile or runtime). consteval forces compile-time evaluation -- calling it with runtime values is a compilation error. constinit ensures a static variable is initialized at compile time (preventing the static initialization order fiasco) but the variable can be mutated at runtime.",
    link: "https://en.cppreference.com/w/cpp/language/consteval.html",
  },
];
