import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: 342,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What are the four storage durations in C++?",
    options: [
      "automatic, static, thread, dynamic",
      "value, reference, pointer, array",
      "local, global, temporary, persistent",
      "stack, heap, global, register",
    ],
    correctIndex: 0,
    explanation:
      "C++ defines four storage durations: automatic (local variables -- destroyed at end of scope), static (globals and static locals -- last for the entire program), thread (thread_local -- one per thread), and dynamic (new/delete -- manually managed).",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 343,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "When is a local variable with automatic storage duration destroyed?",
    code: `void f() {\n    std::string s = "hello";\n    // ...\n}  // What happens to s here?`,
    options: [
      "When the function returns",
      "It is never destroyed",
      "Only when the program exits, because locals persist until termination",
      "When the garbage collector runs and determines the object is unreachable",
    ],
    correctIndex: 0,
    explanation:
      "Automatic storage duration variables are created when their declaration is reached and destroyed when execution leaves the enclosing scope (typically the closing brace). Their destructor is called automatically.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 344,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What is the storage duration of a global variable?",
    code: `int globalCount = 0;  // defined at namespace scope\n\nint main() {\n    ++globalCount;\n}`,
    options: [
      "Static -- exists for the entire duration of the program",
      "Thread -- one copy is created for each thread in the process",
      "Automatic -- destroyed when main() returns and the stack unwinds",
      "Dynamic -- allocated on the heap and must be freed manually",
    ],
    correctIndex: 0,
    explanation:
      "Variables defined at namespace scope (outside any function) have static storage duration. They are created before main() starts and destroyed after main() returns.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 345,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What is special about a static local variable?",
    code: `int nextId() {\n    static int counter = 0;\n    return ++counter;\n}`,
    options: [
      "It is initialized once and persists across all subsequent calls to the function",
      "It is allocated on the heap using dynamic memory allocation and must be manually freed to avoid a memory leak",
      "It is re-initialized to its original value of 0 every time the function is called, resetting on each invocation",
      "It is shared between all threads without any synchronization, leading to potential data races on concurrent access",
    ],
    correctIndex: 0,
    explanation:
      "A static local variable has static storage duration but local scope. It is initialized the first time execution reaches its declaration and persists until program termination. Since C++11, this initialization is guaranteed to be thread-safe.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 346,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What storage duration do objects created with new have?",
    code: `int* p = new int(42);`,
    options: [
      "Dynamic -- exists until explicitly deleted",
      "Automatic -- destroyed at end of scope",
      "Thread -- exists until the thread ends",
      "Static -- destroyed when the program ends",
    ],
    correctIndex: 0,
    explanation:
      "Objects created with new have dynamic storage duration. They live on the heap and exist until you call delete (or the program ends, leaking them). The pointer p itself has automatic duration, but the int it points to does not.",
    link: "https://en.cppreference.com/w/cpp/language/new.html",
  },
  {
    id: 347,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What is the difference between scope and lifetime?",
    options: [
      "Scope applies only to functions and their parameters; lifetime applies only to variables and allocated objects",
      "Scope is a runtime concept determined by the call stack; lifetime is a compile-time concept determined by type analysis",
      "Scope is where a name is visible in source code; lifetime is how long the object exists in memory at runtime",
      "They are the same concept with different names",
    ],
    correctIndex: 2,
    explanation:
      "Scope is a compile-time property: the region of code where a name can be used. Lifetime is a runtime property: the period during which an object exists in memory. A static local variable has local scope but lifetime that extends to program termination.",
    link: "https://en.cppreference.com/w/cpp/language/scope.html",
  },
  {
    id: 348,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What does thread_local do?",
    code: `thread_local int requestCount = 0;`,
    options: [
      "Makes every access to the variable atomic, ensuring thread-safe reads and writes without synchronization",
      "Makes the variable immutable within each thread so that no write operations can modify its value",
      "Creates a separate copy of the variable for each thread, each with its own lifetime tied to its thread",
      "Restricts the variable to the main thread only, preventing other threads from reading or modifying it",
    ],
    correctIndex: 2,
    explanation:
      "thread_local gives a variable thread storage duration: each thread gets its own independent copy, initialized when the thread starts (or on first use for local statics) and destroyed when the thread exits.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 349,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "In what order are local variables destroyed at the end of a scope?",
    code: `void f() {\n    std::string a = "first";\n    std::string b = "second";\n    std::string c = "third";\n}  // destruction order?`,
    options: [
      "c, b, a -- reverse order of construction",
      "a, b, c -- same order as construction",
      "Unspecified -- the compiler may choose any order",
      "All three are destroyed simultaneously",
    ],
    correctIndex: 0,
    explanation:
      "Local variables are destroyed in the reverse order of their construction. This is a fundamental C++ guarantee that ensures dependent objects are destroyed before the objects they depend on.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 350,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "Where is a local variable with automatic storage duration typically allocated?",
    options: [
      "In a memory-mapped file",
      "On the call stack",
      "In a global data segment",
      "On the heap",
    ],
    correctIndex: 1,
    explanation:
      "Automatic variables are typically allocated on the call stack. Stack allocation is extremely fast (just a pointer adjustment) and deallocation is automatic when the function returns.",
    link: "https://www.learncpp.com/cpp-tutorial/the-stack-and-the-heap/",
  },
  {
    id: 351,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What happens to the dynamically allocated memory if you lose the pointer?",
    code: `void leak() {\n    int* p = new int(100);\n    p = nullptr;  // original pointer lost\n}`,
    options: [
      "The memory is automatically freed when p is reassigned",
      "The memory is leaked",
      "The memory is freed when the function returns and the stack unwinds",
      "The garbage collector will eventually reclaim it automatically",
    ],
    correctIndex: 1,
    explanation:
      "C++ has no garbage collector. Once you overwrite or lose the only pointer to dynamically allocated memory, there is no way to call delete on it. The memory is leaked until the program exits. Use smart pointers to prevent this.",
    link: "https://www.learncpp.com/cpp-tutorial/dynamic-memory-allocation-with-new-and-delete/",
  },
  {
    id: 352,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What is wrong with this function?",
    code: `int& getLocal() {\n    int x = 42;\n    return x;\n}`,
    options: [
      "It returns a copy of x rather than a reference, so the value 42 is preserved for the caller",
      "Nothing is wrong",
      "Compilation error",
      "Undefined behavior",
    ],
    correctIndex: 3,
    explanation:
      "x has automatic storage duration and is destroyed when getLocal() returns. The returned reference refers to memory that no longer holds a valid object -- this is a dangling reference and using it is undefined behavior.",
    link: "https://www.learncpp.com/cpp-tutorial/returning-values-by-value-reference-and-address/",
  },
  {
    id: 353,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What is the default value of an uninitialized local int variable?",
    code: `void f() {\n    int x;\n    std::cout << x;  // what prints?\n}`,
    options: [
      "The compiler always produces an error for uninitialized variables",
      "0 -- local variables are zero-initialized",
      "Indeterminate -- reading it is undefined behavior",
      "-1 -- the compiler fills uninitialized memory with -1",
    ],
    correctIndex: 2,
    explanation:
      "Local variables with automatic storage duration and no initializer are default-initialized. For built-in types like int, this means they hold an indeterminate value. Reading such a value is undefined behavior. Always initialize your variables.",
    link: "https://en.cppreference.com/w/cpp/language/default_initialization.html",
  },
  {
    id: 354,
    difficulty: "Easy",
    topic: "Lifetime & Storage",
    question: "What is the default value of a global int variable that is not explicitly initialized?",
    code: `int globalX;\n\nint main() {\n    std::cout << globalX;\n}`,
    options: [
      "Indeterminate -- same as local variables",
      "0 -- variables with static storage duration are zero-initialized",
      "Compilation error",
      "-1",
    ],
    correctIndex: 1,
    explanation:
      "Variables with static storage duration (globals, static locals, static class members) are zero-initialized before any other initialization. So an uninitialized global int is guaranteed to be 0, unlike local variables.",
    link: "https://en.cppreference.com/w/cpp/language/zero_initialization.html",
  },
  {
    id: 355,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What does this code demonstrate?",
    code: `const std::string& extend() {\n    return "temporary";\n}\n\nconst std::string& ref = extend();\nstd::cout << ref;  // safe?`,
    options: [
      "Compilation error",
      "Safe -- string literals have static storage duration, so the temporary std::string constructed from the literal inherits that same lifetime and persists throughout the program",
      "Safe -- the const reference extends the temporary’s lifetime to match the scope of the calling function, so the string remains valid for as long as the reference exists",
      "Dangling reference",
    ],
    correctIndex: 3,
    explanation:
      "Lifetime extension via const reference only works when the temporary is bound directly at the call site. Here, the temporary is created inside extend() and bound to the return reference there -- it dies when the function returns. The caller gets a dangling reference.",
    link: "https://en.cppreference.com/w/cpp/language/reference_initialization.html",
  },
  {
    id: 356,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "When does lifetime extension via const reference apply?",
    code: `std::string makeStr() { return "hello"; }\n\nconst std::string& ref = makeStr();  // valid?\nstd::cout << ref;`,
    options: [
      "Here, yes -- binding a const reference directly to a prvalue extends the temporary's lifetime to match the reference's scope",
      "Always -- any const reference extends any temporary it is bound to, including through intermediate function calls",
      "Never -- const references cannot bind to temporaries regardless of whether the function returns by value or by reference",
      "Only when the function returns by reference, because returning by value creates a copy that cannot be lifetime-extended",
    ],
    correctIndex: 0,
    explanation:
      "When a const lvalue reference (or rvalue reference) is directly bound to a temporary (prvalue), the temporary's lifetime is extended to match the reference. This works here because makeStr() returns by value, creating a temporary at the call site.",
    link: "https://en.cppreference.com/w/cpp/language/reference_initialization.html",
  },
  {
    id: 357,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What is the 'static initialization order fiasco'?",
    code: `// file_a.cpp\nextern int b;\nint a = b + 1;  // depends on b\n\n// file_b.cpp\nextern int a;\nint b = a + 1;  // depends on a`,
    options: [
      "The initialization order of static variables across translation units is unspecified, so a and b may read uninitialized (zero) values depending on which file is initialized first",
      "A linker error -- circular dependencies between translation unit files are forbidden and detected during the symbol resolution phase of the linking process",
      "The compiler detects the circular dependency cycle and produces a compilation error because cross-translation-unit static variable dependencies are statically analyzed during compilation",
      "Both a and b will be 1 because all static variables are always zero-initialized first in the data segment, and then the dynamic initializers run in the order they appear in the source",
    ],
    correctIndex: 0,
    explanation:
      "Static variables in different translation units are zero-initialized first, then dynamically initialized in an unspecified order between TUs. If a is initialized first, it reads b as 0 (zero-initialized), so a=1, then b=2. The order may vary between builds.",
    link: "https://en.cppreference.com/w/cpp/language/initialization.html",
  },
  {
    id: 358,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "How does the 'construct on first use' idiom solve the static initialization order fiasco?",
    code: `int& getA() {\n    static int a = getB() + 1;\n    return a;\n}\n\nint& getB() {\n    static int b = 42;\n    return b;\n}`,
    options: [
      "Function-local statics are initialized on first call, guaranteeing that b is initialized before a uses it",
      "The static keyword makes both variables thread-local so they avoid shared initialization ordering",
      "It doesn’t solve anything",
      "The functions force the linker to resolve the initialization order by analyzing the dependency graph",
    ],
    correctIndex: 0,
    explanation:
      "By wrapping statics in functions, initialization happens on the first call rather than at program startup. When getA() calls getB(), b is initialized first (if not already). This gives you explicit control over initialization order.",
    link: "https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use",
  },
  {
    id: 359,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What happens to the string inside this optional?",
    code: `std::optional<std::string> opt = "hello";\nopt.reset();\n// Is the string destroyed?`,
    options: [
      "The string is moved out of the optional into a temporary but its destructor is not called yet",
      "Yes -- reset() destroys the contained object immediately, calling its destructor",
      "reset() only marks the optional as empty",
      "No -- the string persists inside the optional’s storage until opt goes completely out of scope",
    ],
    correctIndex: 1,
    explanation:
      "optional::reset() immediately destroys the contained value by calling its destructor, then marks the optional as empty. The storage remains (it's part of optional's footprint) but the object's lifetime has ended.",
    link: "https://en.cppreference.com/w/cpp/utility/optional/reset.html",
  },
  {
    id: 360,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What is the lifetime of the temporary in this expression?",
    code: `const char* p = std::string("temp").c_str();\nstd::cout << p;  // safe?`,
    options: [
      "Compilation error",
      "Safe -- c_str() returns a pointer to static memory that persists independently of the string object’s lifetime, so the pointer remains valid after destruction",
      "Dangling pointer",
      "Safe -- the const pointer p extends the temporary’s lifetime to match the scope of the pointer variable, keeping the string data valid throughout",
    ],
    correctIndex: 2,
    explanation:
      "The temporary std::string is destroyed at the semicolon (end of the full expression). c_str() returns a pointer to the string's internal buffer, which is freed when the string is destroyed. p is now a dangling pointer.",
    link: "https://en.cppreference.com/w/cpp/language/lifetime.html",
  },
  {
    id: 361,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "When are global objects destroyed relative to each other?",
    options: [
      "In the same order in which they were originally constructed at startup",
      "In alphabetical order based on the identifier names of the global objects",
      "All at once, simultaneously, when the program terminates and exits main",
      "In reverse order of construction",
    ],
    correctIndex: 3,
    explanation:
      "Within a single translation unit, global objects are constructed in definition order and destroyed in the reverse order. Across translation units, the construction order is unspecified, but within each TU, the reverse-of-construction guarantee holds.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 362,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What happens when you use std::move on a local variable and then access it?",
    code: `std::string name = "Alice";\nstd::string other = std::move(name);\nstd::cout << name.size();  // safe?`,
    options: [
      "Undefined behavior",
      "Safe -- name is in a valid but unspecified state; calling size() is fine, but the value is unspecified",
      "Always prints 5",
      "Compilation error",
    ],
    correctIndex: 1,
    explanation:
      "std::move doesn't end the object's lifetime -- it casts to an rvalue reference, enabling the move constructor. After being moved from, the std::string is in a valid but unspecified state. Calling size() is safe; the value may be 0 or something else.",
    link: "https://en.cppreference.com/w/cpp/utility/move.html",
  },
  {
    id: 363,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What storage duration do lambda captures have?",
    code: `auto makeLambda() {\n    int local = 42;\n    return [local]() { return local; };\n}\n\nauto fn = makeLambda();\nstd::cout << fn();  // safe?`,
    options: [
      "Dangling reference",
      "Safe only if the lambda is called in the same scope as the captured variable was originally declared; otherwise the captured reference dangles on access",
      "The capture has static storage duration because lambda closures are implicitly stored as static objects in the data segment by the compiler",
      "Safe -- capturing by value copies local into the lambda's closure object, which has its own storage duration independent of the original",
    ],
    correctIndex: 3,
    explanation:
      "Capturing by value copies the variable into the closure object. The closure is a regular object with its own lifetime -- here it's returned and stored in fn, so the copy of local lives as long as fn does. Capturing by reference would dangle.",
    link: "https://en.cppreference.com/w/cpp/language/lambda.html",
  },
  {
    id: 364,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What is the risk of returning a lambda that captures by reference?",
    code: `auto make() {\n    int x = 10;\n    return [&x]() { return x; };\n}\n\nauto fn = make();\nstd::cout << fn();`,
    options: [
      "Undefined behavior",
      "Compilation error",
      "Safe -- the reference capture keeps x alive for as long as the lambda object exists in the calling scope",
      "Prints 0 -- x is zero-initialized after the function returns because the reference is reset to its default value",
    ],
    correctIndex: 0,
    explanation:
      "The lambda captures a reference to x, which has automatic storage duration in make(). When make() returns, x is destroyed. The lambda now holds a dangling reference. Calling fn() reads destroyed memory -- undefined behavior.",
    link: "https://en.cppreference.com/w/cpp/language/lambda.html",
  },
  {
    id: 365,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What is the lifetime of a string literal?",
    code: `const char* getMessage() {\n    return "hello world";\n}\n\nconst char* p = getMessage();\nstd::cout << p;  // safe?`,
    options: [
      "Safe -- string literals have static storage duration and exist for the entire program",
      "Implementation-defined",
      "Safe only if the caller copies the string immediately into a local buffer before use",
      "Dangling -- the literal is destroyed when the function returns and the stack unwinds",
    ],
    correctIndex: 0,
    explanation:
      "String literals are stored in a read-only section of the binary and have static storage duration. They exist from program start to program end. Returning a pointer to one is always safe.",
    link: "https://en.cppreference.com/w/cpp/language/string_literal.html",
  },
  {
    id: 366,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "What storage duration does this constexpr variable have?",
    code: `void f() {\n    constexpr int N = 100;\n}`,
    options: [
      "Static -- constexpr always implies static storage duration for all variables",
      "Dynamic -- constexpr variables are heap-allocated and freed at scope end",
      "Automatic -- like any local variable, but the value is computed at compile time",
      "Compile-time only",
    ],
    correctIndex: 2,
    explanation:
      "A local constexpr variable has automatic storage duration -- it follows normal scoping rules. constexpr means the value is usable in constant expressions (compile time), but the variable itself is still a local. Only at namespace scope does constexpr imply internal linkage.",
    link: "https://en.cppreference.com/w/cpp/language/constexpr.html",
  },
  {
    id: 367,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "Is the object alive between its constructor throwing and the catch block?",
    code: `class Resource {\npublic:\n    Resource() {\n        // acquire stuff...\n        throw std::runtime_error("init failed");\n    }\n    ~Resource() { /* release stuff */ }\n};\n\ntry { Resource r; } catch (...) {}`,
    options: [
      "Implementation-defined",
      "Yes -- the destructor always runs regardless of exceptions to guarantee RAII cleanup of all resources",
      "No -- if a constructor throws, the object was never fully constructed and the destructor is NOT called",
      "Yes -- the destructor runs in the catch block to clean up the partially constructed object's resources",
    ],
    correctIndex: 2,
    explanation:
      "If a constructor throws, the object's lifetime never begins. The destructor is not called. However, any sub-objects (base classes, members) that were already fully constructed ARE destroyed. This is why RAII members are important -- they clean themselves up.",
    link: "https://en.cppreference.com/w/cpp/language/destructor.html",
  },
  {
    id: 368,
    difficulty: "Medium",
    topic: "Lifetime & Storage",
    question: "How does std::unique_ptr tie into storage duration?",
    code: `void f() {\n    auto p = std::make_unique<Widget>();\n    // use *p ...\n}  // What happens here?`,
    options: [
      "The unique_ptr is destroyed at end of scope, and its destructor calls delete on the managed Widget, ending both lifetimes",
      "The Widget has automatic storage duration because it is managed by a local unique_ptr variable, so it is stored on the stack rather than the heap",
      "The Widget is not destroyed when f() returns",
      "The Widget leaks",
    ],
    correctIndex: 0,
    explanation:
      "unique_ptr is an RAII wrapper. The pointer p has automatic storage duration. The Widget it manages has dynamic storage duration. When p's destructor runs (end of scope), it calls delete on the Widget. This bridges automatic and dynamic lifetimes.",
    link: "https://en.cppreference.com/w/cpp/memory/unique_ptr.html",
  },
  {
    id: 369,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What does placement new do to object lifetime?",
    code: `alignas(Widget) unsigned char buf[sizeof(Widget)];\nWidget* w = new (buf) Widget();  // placement new\nw->doWork();\nw->~Widget();  // manual destructor call`,
    options: [
      "Same as regular new but faster because it skips allocation",
      "Undefined behavior",
      "The object’s lifetime is tied to buf’s scope regardless of when the explicit destructor call occurs, and it ends automatically when buf is deallocated at scope exit",
      "Creates a Widget in pre-allocated storage; the object's lifetime begins at placement new and ends at the explicit destructor call",
    ],
    correctIndex: 3,
    explanation:
      "Placement new constructs an object in existing memory without allocating. The object's lifetime begins at the placement new call. You must manually call the destructor to end the lifetime. Calling delete would try to free buf, which wasn't allocated with new.",
    link: "https://en.cppreference.com/w/cpp/language/new.html",
  },
  {
    id: 370,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What is the problem with reusing storage after placement new?",
    code: `alignas(A) unsigned char buf[sizeof(A)];\nA* a = new (buf) A();\na->~A();\nB* b = new (buf) B();  // reuse same storage\n// Is it safe to use 'a' pointer for anything?`,
    options: [
      "The compiler automatically updates the old pointer a to point to the new B object through an implicit pointer-rebinding mechanism in the language specification, so using a after constructing B in the same storage is well-defined behavior",
      "Undefined behavior in general: after A is destroyed and B is constructed, using the old pointer a may violate strict aliasing and object lifetime rules. In C++17, std::launder may be needed even for the new pointer if types differ",
      "Safe -- the old pointer a still points to valid memory because the underlying buffer was not deallocated or moved to a different address, so dereferencing it always produces defined behavior regardless of what was constructed there",
      "Safe as long as sizeof(B) <= sizeof(A) and both types have the same alignment requirement so the buffer is compatible; the C++ standard guarantees that pointer reuse across types is always valid when these size and alignment conditions are met",
    ],
    correctIndex: 1,
    explanation:
      "Once A is destroyed, the pointer a no longer points to a valid A object. Reusing the storage for B starts a new object's lifetime. The original pointer may not be valid for accessing the new object due to type aliasing rules. std::launder (C++17) was introduced to handle such scenarios.",
    link: "https://en.cppreference.com/w/cpp/utility/launder.html",
  },
  {
    id: 371,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What does [[no_unique_address]] do to a member's storage?",
    code: `struct Empty {};\n\nstruct S {\n    [[no_unique_address]] Empty e;\n    int x;\n};\n\nstatic_assert(sizeof(S) == sizeof(int));  // likely passes`,
    options: [
      "Deletes the member from the class entirely",
      "Makes the member constexpr so that it is evaluated entirely at compile time and does not occupy any storage in the runtime object layout of the class",
      "Allows the compiler to give an empty member zero size, similar to the Empty Base Optimization but for data members",
      "Makes the member thread_local so that each thread gets its own independent copy of the empty object, preventing data races between concurrent accesses",
    ],
    correctIndex: 2,
    explanation:
      "Normally, even empty members must occupy at least 1 byte. [[no_unique_address]] (C++20) tells the compiler it may overlap the empty member with other members or give it zero size. This is EBO for members, useful for stateless allocators and comparators.",
    link: "https://en.cppreference.com/w/cpp/language/attributes/no_unique_address.html",
  },
  {
    id: 372,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What happens during the two phases of static variable initialization?",
    options: [
      "Phase 1 is zero/constant initialization; Phase 2 is dynamic initialization (runtime). All static variables are zero-initialized first, then those with constant initializers are set, then runtime constructors run",
      "Phase 1 allocates memory in the data segment for all static and global variables, and Phase 2 calls their constructors and evaluates each initializer expression in the order they appear in the source code of each translation unit",
      "Phase 1 initializes globals declared at namespace scope in definition order within each translation unit, and Phase 2 initializes all function-local static variables on first use when their enclosing function is called during program execution",
      "Phase 1 runs before main() begins and handles all constexpr initializers that can be evaluated at compile time, and Phase 2 runs during main() execution for everything else that requires dynamic evaluation at runtime",
    ],
    correctIndex: 0,
    explanation:
      "Static initialization has two ordered phases: (1) zero-initialization (all static storage is zeroed) followed by constant initialization (constexpr-evaluable initializers are applied at compile/load time), then (2) dynamic initialization runs constructors and complex initializers. This is why globals are zero before their constructors run.",
    link: "https://en.cppreference.com/w/cpp/language/initialization.html",
  },
  {
    id: 373,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What does std::atexit control about object lifetime?",
    code: `void cleanup() { std::cout << "cleanup "; }\n\nstruct Global {\n    ~Global() { std::cout << "~Global "; }\n} g;\n\nint main() {\n    std::atexit(cleanup);\n}`,
    options: [
      "~Global runs first, then cleanup is called",
      "The order between atexit handlers and static destructors is implementation-defined and varies across compilers and platforms",
      "cleanup runs first, then ~Global is called",
      "cleanup runs, then ~Global",
    ],
    correctIndex: 3,
    explanation:
      "atexit handlers and static object destructors share the same 'at-exit' queue and execute in reverse order of registration. g was constructed (registered) before atexit(cleanup), so cleanup runs first, then ~Global. They are interleaved, not separated.",
    link: "https://en.cppreference.com/w/cpp/utility/program/atexit.html",
  },
  {
    id: 374,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What is the lifetime issue with this code?",
    code: `struct S {\n    const std::string& name;\n};\n\nS makeS() {\n    std::string str = "hello";\n    return S{str};\n}`,
    options: [
      "Safe -- the struct copies the string because aggregate initialization performs an implicit copy of each initializer value into the corresponding member, creating an independent copy",
      "Dangling reference",
      "Compilation error",
      "Safe -- return value optimization extends the lifetime of the local string str to match the lifetime of the returned S object, keeping the reference valid at the call site",
    ],
    correctIndex: 1,
    explanation:
      "S::name is a reference member bound to a local variable. When makeS() returns, str is destroyed, and the returned S object contains a dangling reference. Lifetime extension only works when a const reference directly binds a temporary -- not when a local is referenced through a struct member.",
    link: "https://en.cppreference.com/w/cpp/language/lifetime.html",
  },
  {
    id: 375,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What happens when you access a union member that was not the last one written?",
    code: `union Data {\n    int i;\n    float f;\n};\n\nData d;\nd.f = 3.14f;\nstd::cout << d.i;  // type punning`,
    options: [
      "In C, this is well-defined. In C++, reading an inactive union member is technically undefined behavior",
      "Well-defined -- always prints the integer representation of 3.14f because unions explicitly allow type punning between all member types in both C and C++ language standards",
      "Compilation error",
      "Defined only for trivially copyable types because the compiler can safely reinterpret their underlying byte representation without violating strict aliasing or object lifetime rules",
    ],
    correctIndex: 0,
    explanation:
      "In C++, only one union member is 'active' (has a started lifetime) at a time -- the last one written. Reading a non-active member is UB in C++. Use std::bit_cast (C++20) or memcpy for safe type punning. Note: C permits union type punning explicitly.",
    link: "https://en.cppreference.com/w/cpp/language/union.html",
  },
  {
    id: 376,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What is the 'static local variable destruction' problem shown here?",
    code: `class Logger {\npublic:\n    void log(const std::string& msg) { /* write to file */ }\n    ~Logger() { /* close file */ }\n};\n\nLogger& getLogger() {\n    static Logger instance;\n    return instance;\n}\n\nclass Widget {\npublic:\n    ~Widget() { getLogger().log("Widget destroyed"); }\n};\n\nstatic Widget w;`,
    options: [
      "Thread safety issue",
      "If w is constructed before the Logger, it is destroyed after the Logger",
      "No problem -- static local variables like the Logger instance are always destroyed last during program shutdown, after all other static objects",
      "Compilation error",
    ],
    correctIndex: 1,
    explanation:
      "Static objects are destroyed in reverse construction order. If w is constructed first (before getLogger() is called), it will be destroyed last -- after the Logger. Widget's destructor tries to use an already-destroyed Logger. This is the 'static destruction order fiasco'.",
    link: "https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use",
  },
  {
    id: 377,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "Does guaranteed copy elision (C++17) affect object lifetime?",
    code: `Widget createWidget() {\n    return Widget(42);  // prvalue\n}\n\nWidget w = createWidget();`,
    options: [
      "Two Widgets are created and one is moved",
      "One Widget is created inside createWidget and then moved into w when the function returns by value, requiring an accessible move constructor to transfer ownership of the object",
      "Exactly one Widget is ever created",
      "The compiler may or may not elide the copy",
    ],
    correctIndex: 2,
    explanation:
      "C++17's guaranteed copy elision means prvalues are not objects -- they are 'recipes' for initializing objects. Widget(42) directly initializes w. No temporary is created, no move/copy constructor is called or needed. This is a fundamental change in the object model.",
    link: "https://en.cppreference.com/w/cpp/language/copy_elision.html",
  },
  {
    id: 378,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What happens to sub-objects when a constructor throws?",
    code: `class Engine {\npublic:\n    Engine() { std::cout << "E "; }\n    ~Engine() { std::cout << "~E "; }\n};\n\nclass Car {\n    Engine engine;\n    int* data;\npublic:\n    Car() : engine(), data(new int(42)) {\n        throw std::runtime_error("fail");\n    }\n    ~Car() { delete data; std::cout << "~Car "; }\n};`,
    options: [
      "E -- nothing is destroyed; everything leaks because an exception in the constructor prevents all destructor calls",
      "E ~Car ~E -- the Car destructor runs and cleans up everything because the constructor body had already begun executing",
      "E ~E -- engine's destructor runs, but ~Car does NOT run, so data is leaked",
      "E ~E ~Car -- both destructors run because the language guarantees cleanup for any object whose constructor body was entered",
    ],
    correctIndex: 2,
    explanation:
      "When a constructor throws, fully constructed sub-objects (engine) are destroyed, but the object's destructor (~Car) is NOT called because the object was never fully constructed. data is leaked. This is why raw new in constructors is dangerous -- use smart pointers.",
    link: "https://en.cppreference.com/w/cpp/language/destructor.html",
  },
  {
    id: 379,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What is the lifetime of a temporary bound to an rvalue reference parameter inside a function?",
    code: `void process(std::string&& s) {\n    // Is s valid for the entire function body?\n    std::cout << s;\n}\n\nprocess("temporary");`,
    options: [
      "The temporary's lifetime extends until process returns",
      "The temporary string is destroyed before process begins executing, because temporaries are always destroyed at the point where they are created in the calling expression",
      "The temporary is automatically moved into the rvalue reference parameter, so s is empty and contains no data inside the function body when it is accessed",
      "Undefined behavior",
    ],
    correctIndex: 0,
    explanation:
      "The temporary std::string created from \"temporary\" lives until the end of the full expression containing the function call. Since process() executes within that expression, s is valid for the entire function body. The temporary is destroyed after process() returns.",
    link: "https://en.cppreference.com/w/cpp/language/lifetime.html",
  },
  {
    id: 380,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What subtle issue does this range-based for loop have?",
    code: `class Matrix {\npublic:\n    std::vector<int> getRow(int i) const;\n};\n\nMatrix m;\nfor (auto& val : m.getRow(0)) {\n    std::cout << val;\n}`,
    options: [
      "Compilation error",
      "No issue -- the vector is valid for the entire loop’s duration because range-for always copies the range expression into a hidden local variable, ensuring the temporary vector persists throughout all iterations",
      "Performance issue only",
      "The vector returned by getRow() is a temporary that is destroyed before the loop body executes, leaving a dangling reference. Range-for stores the range as auto&& __range = expr, but the sub-expression temporary dies at the semicolon",
    ],
    correctIndex: 3,
    explanation:
      "In C++17 and earlier, range-for expands to auto&& __range = m.getRow(0); -- the temporary vector is lifetime-extended. However, if getRow() returned a reference to a temporary sub-object, or if the expression were more complex (like m.getRows()[0]), the temporary could dangle. C++23's P2718 fixes the general case. In this specific example with most compilers, the temporary is actually extended, but this pattern is fragile.",
    link: "https://en.cppreference.com/w/cpp/language/range-for.html",
  },
  {
    id: 381,
    difficulty: "Hard",
    topic: "Lifetime & Storage",
    question: "What is the result of calling std::exit() regarding local object lifetimes?",
    code: `void f() {\n    std::string local = "important";\n    std::exit(0);  // called deep in the call stack\n}`,
    options: [
      "std::exit() throws a special exception that unwinds the stack normally, calling all destructors along the way, similar to how a regular unhandled exception propagates",
      "All objects in all scopes are destroyed in reverse order of construction, identical to returning from main(), including both automatic and static storage duration objects in every frame",
      "local's destructor runs before the program exits because std::exit triggers normal stack unwinding first, just like a regular return from the function would do in standard execution flow",
      "std::exit() does NOT unwind the stack",
    ],
    correctIndex: 3,
    explanation:
      "std::exit() skips stack unwinding entirely. No destructors for automatic (local) variables are called. It does run destructors for static objects and atexit-registered functions. This can cause resource leaks, unclosed files, etc. Prefer returning from main() for clean shutdown.",
    link: "https://en.cppreference.com/w/cpp/utility/program/exit.html",
  },
];
