import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: 3,
    difficulty: "Easy",
    topic: "OOP",
    question: "Which keyword enables runtime polymorphism in C++?",
    options: ["virtual", "static", "abstract", "override"],
    correctIndex: 0,
    explanation:
      "Declaring a member function virtual in the base class enables dynamic dispatch, allowing the correct derived class override to be called through a base pointer or reference.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-functions/",
  },
  {
    id: 4,
    difficulty: "Medium",
    topic: "OOP",
    question:
      "What happens when a Derived object is assigned to a Base variable by value?",
    code: "Base b = derivedObj;",
    options: [
      "Runtime exception",
      "The Base variable behaves polymorphically as a Derived",
      "Object slicing -- derived-specific data is lost",
      "Compilation error",
    ],
    correctIndex: 2,
    explanation:
      "When copied by value into a Base, only the Base portion is copied. The derived members and virtual dispatch are stripped away.",
    link: "https://www.learncpp.com/cpp-tutorial/object-slicing/",
  },
  {
    id: 5,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the problem with this code?",
    code: `class Base {\npublic:\n    ~Base() { std::cout << "~Base"; }\n};\n\nclass Derived : public Base {\n    int* data = new int(42);\npublic:\n    ~Derived() { delete data; std::cout << "~Derived"; }\n};\n\nBase* p = new Derived();\ndelete p;`,
    options: [
      "Double deletion",
      "No problem -- the compiler chains destructors correctly",
      "Stack overflow -- destructors call each other recursively",
      "Memory leak -- Derived destructor is never called",
    ],
    correctIndex: 3,
    explanation:
      "Without a virtual destructor in Base, deleting through a Base* only calls ~Base(). The Derived destructor never runs, so data is never freed.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-destructors-virtual-assignment-and-overriding-virtualization/",
  },
  {
    id: 39,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "A base class declares virtual void speak() const. A derived class writes void speak() override (missing const). What happens?",
    code: `class Animal {\npublic:\n    virtual void speak() const { std::cout << "..."; }\n};\n\nclass Dog : public Animal {\npublic:\n    void speak() override { std::cout << "Woof"; }\n};`,
    options: [
      "Runtime error -- the vtable entry points to an invalid function address",
      "Compiles and prints 'Woof' when called through an Animal pointer",
      "Compilation error",
      "Compiles but silently hides the base version without any warning",
    ],
    correctIndex: 2,
    explanation:
      "speak() and speak() const are different signatures. The override keyword catches this at compile time. Without override, the derived version would silently hide the base version.",
    link: "https://en.cppreference.com/w/cpp/language/override.html",
  },
  {
    id: 40,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "In a diamond inheritance hierarchy without virtual inheritance, how many copies of the shared base's data members exist?",
    options: ["It depends on the compiler", "Two", "One", "Zero"],
    correctIndex: 1,
    explanation:
      "Without virtual inheritance, each path through the diamond creates its own copy of the base class, causing ambiguity when accessing the base's members.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-base-classes/",
  },
  {
    id: 59,
    difficulty: "Hard",
    topic: "OOP",
    question:
      "In a virtual inheritance diamond (D inherits B and C, both virtually inherit from A), which value does A receive?",
    code: `struct A { A(int x); };\nstruct B : virtual A { B() : A(1) {} };\nstruct C : virtual A { C() : A(2) {} };\nstruct D : B, C { D() : A(3), B(), C() {} };`,
    options: [
      "Compilation error",
      "3 -- the most-derived class constructs virtual bases",
      "2 -- C is listed second, overriding B",
      "1 -- B is listed first in D's inheritance",
    ],
    correctIndex: 1,
    explanation:
      "With virtual inheritance, B's and C's initializers for A are ignored. The most-derived class (D) is responsible for directly constructing all virtual base classes.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-base-classes/",
  },
  {
    id: 64,
    difficulty: "Hard",
    topic: "OOP",
    question:
      "In the copy-and-swap idiom, the assignment operator takes the parameter by value. Why does this also handle move assignment?",
    code: `Widget& operator=(Widget other) {\n    swap(*this, other);\n    return *this;\n}`,
    options: [
      "The compiler automatically converts it to a move assignment at link time",
      "When called with an rvalue, other is move-constructed instead of copied",
      "swap detects rvalues at runtime and skips the copy in that code path",
      "It doesn't -- you still need a separate move assignment operator defined",
    ],
    correctIndex: 1,
    explanation:
      "When the argument is an rvalue, the by-value parameter other is initialized via the move constructor. When the argument is an lvalue, other is copy-constructed. Either way, you swap with the temporary and let its destructor clean up the old state.",
    link: "https://en.cppreference.com/w/cpp/language/operators.html",
  },
  {
    id: 272,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is the default access specifier for members of a class in C++?",
    options: ["private", "public", "protected", "friend"],
    correctIndex: 0,
    explanation:
      "In a class, members are private by default. In a struct, members are public by default. This is the only behavioral difference between class and struct in C++.",
    link: "https://www.learncpp.com/cpp-tutorial/access-specifiers/",
  },
  {
    id: 273,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What is the output of this program?",
    code: `class Base {\npublic:\n    Base()  { std::cout << "B"; }\n    ~Base() { std::cout << "~B"; }\n};\n\nclass Derived : public Base {\npublic:\n    Derived()  { std::cout << "D"; }\n    ~Derived() { std::cout << "~D"; }\n};\n\nint main() {\n    Derived d;\n}`,
    options: ["BD~D~B", "DB~B~D", "DB~D~B", "BD~B~D"],
    correctIndex: 0,
    explanation:
      "Constructors run base-first then derived. Destructors run in the reverse order: derived first, then base. So we get B, D on construction and ~D, ~B on destruction.",
    link: "https://www.learncpp.com/cpp-tutorial/order-of-construction-of-derived-classes/",
  },
  {
    id: 274,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What does = 0 at the end of a virtual function declaration mean?",
    code: `class Shape {\npublic:\n    virtual double area() const = 0;\n};`,
    options: [
      "The function is deleted and cannot be called",
      "The function is pure virtual",
      "The function always returns 0",
      "The function has a default implementation that returns 0",
    ],
    correctIndex: 1,
    explanation:
      "= 0 makes the function pure virtual. Any class with at least one pure virtual function is abstract and cannot be instantiated directly. Derived classes must provide an implementation.",
    link: "https://www.learncpp.com/cpp-tutorial/pure-virtual-functions-abstract-base-classes-and-interface-classes/",
  },
  {
    id: 275,
    difficulty: "Easy",
    topic: "OOP",
    question: "What does the this pointer refer to inside a member function?",
    options: [
      "A pointer to the most-derived class in the hierarchy",
      "The class definition itself",
      "A pointer to the current object the function was called on",
      "A pointer to the base class",
    ],
    correctIndex: 2,
    explanation:
      "Inside a non-static member function, this is an implicit pointer to the object on which the function was invoked. Its type is ClassName* (or const ClassName* in a const member function).",
    link: "https://www.learncpp.com/cpp-tutorial/the-hidden-this-pointer-and-member-function-chaining/",
  },
  {
    id: 276,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "If you define a parameterized constructor but no default constructor, what happens when you write MyClass obj;?",
    code: `class MyClass {\npublic:\n    MyClass(int x) {}\n};\n\nMyClass obj;`,
    options: [
      "Runtime error",
      "Compilation error",
      "The object is zero-initialized",
      "The compiler generates a default constructor automatically",
    ],
    correctIndex: 1,
    explanation:
      "Once you declare any constructor, the compiler no longer generates a default constructor. You must either add MyClass() = default; or always provide an argument.",
    link: "https://www.learncpp.com/cpp-tutorial/default-constructors-and-default-arguments/",
  },
  {
    id: 277,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "Which of the following best describes encapsulation?",
    options: [
      "Having multiple functions with the same name but different parameter lists or types",
      "Bundling data and methods together and restricting direct access to internal state",
      "Deriving new classes from existing ones to form an inheritance hierarchy",
      "Using base class pointers to call derived class methods via dynamic dispatch",
    ],
    correctIndex: 1,
    explanation:
      "Encapsulation means keeping data members private and exposing controlled access through public member functions. This protects invariants and hides implementation details.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-encapsulation/",
  },
  {
    id: 278,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "A friend function declared inside a class can access which members?",
    code: `class Box {\n    int width;  // private\nprotected:\n    int height;\npublic:\n    int depth;\n    friend void inspect(const Box& b);\n};`,
    options: [
      "Only public and protected members, not private",
      "All members",
      "Only the private members of the class body",
      "Only public members of the class definition",
    ],
    correctIndex: 1,
    explanation:
      "A friend function is granted full access to all members of the class, regardless of access specifier. Friendship bypasses access control entirely.",
    link: "https://www.learncpp.com/cpp-tutorial/friend-non-member-functions/",
  },
  {
    id: 279,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "Can a static member function access non-static member variables of its class?",
    options: [
      "Only if those members are also declared as static",
      "Yes, always -- static functions can access any member",
      "Only if the non-static members are declared as public",
      "No -- static member functions have no this pointer",
    ],
    correctIndex: 3,
    explanation:
      "Static member functions are not called on an object, so there is no this pointer. They can only access static members and other data explicitly passed to them.",
    link: "https://www.learncpp.com/cpp-tutorial/static-member-functions/",
  },
  {
    id: 280,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What type of inheritance is shown here?",
    code: `class Animal {};\nclass Dog : public Animal {};\nclass Puppy : public Dog {};`,
    options: [
      "Multilevel inheritance",
      "Hierarchical inheritance",
      "Hybrid inheritance",
      "Multiple inheritance",
    ],
    correctIndex: 0,
    explanation:
      "Multilevel inheritance is a chain: Animal → Dog → Puppy. Multiple inheritance is one class inheriting from two or more base classes. Hierarchical inheritance is multiple classes inheriting from a single base.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-inheritance/",
  },
  {
    id: 281,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is function overloading in C++?",
    options: [
      "Redefining a base class function in a derived class to change the behavior at runtime via virtual dispatch",
      "Using the virtual keyword on a base class declaration to enable late binding and dynamic dispatch at runtime",
      "Calling a function recursively so that it invokes itself repeatedly with different arguments each time",
      "Having multiple functions with the same name but different parameter lists in the same scope",
    ],
    correctIndex: 3,
    explanation:
      "Function overloading allows multiple functions with the same name as long as their parameter types or counts differ. The compiler selects the best match at compile time (static polymorphism).",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-function-overloading/",
  },
  {
    id: 282,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is the correct signature of a copy constructor for class Foo?",
    options: [
      "Foo(const Foo& other)",
      "Foo(Foo* other)",
      "void Foo(const Foo& other)",
      "Foo(Foo other)",
    ],
    correctIndex: 0,
    explanation:
      "A copy constructor takes a const reference to the same class. Passing by value would require calling the copy constructor itself, creating infinite recursion.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-the-copy-constructor/",
  },
  {
    id: 283,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "A protected member of a base class is accessible from where?",
    options: [
      "Within the base class and its derived classes, but not from outside code",
      "Only from friend functions explicitly declared inside the base class",
      "From anywhere in the program, just like a public member is accessible",
      "Only within the base class itself, not from derived classes or outside",
    ],
    correctIndex: 0,
    explanation:
      "Protected members sit between private and public: they are accessible within the class and any class that derives from it, but not by unrelated code.",
    link: "https://www.learncpp.com/cpp-tutorial/access-specifiers/",
  },
  {
    id: 284,
    difficulty: "Easy",
    topic: "OOP",
    question: "Can constructors be declared virtual in C++?",
    options: [
      "Only copy constructors can be virtual",
      "Yes, it's required for polymorphic construction",
      "Yes, but only in abstract classes",
      "No",
    ],
    correctIndex: 3,
    explanation:
      "Constructors cannot be virtual. The virtual dispatch mechanism relies on the vtable pointer, which is not set up until the constructor runs. Use factory patterns or clone() methods for polymorphic creation.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-functions/",
  },
  {
    id: 285,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What does the explicit keyword do on a single-argument constructor?",
    code: `class Meter {\npublic:\n    explicit Meter(double val);\n};`,
    options: [
      "Makes the constructor private so it cannot be called externally",
      "Forces the compiler to inline the constructor at every call site",
      "Prevents implicit conversions",
      "Makes the constructor constexpr for compile-time evaluation",
    ],
    correctIndex: 2,
    explanation:
      "Without explicit, Meter m = 3.5; would compile via implicit conversion. With explicit, you must write Meter m(3.5) or Meter m{3.5}. This prevents accidental type conversions.",
    link: "https://www.learncpp.com/cpp-tutorial/explicit-constructors-and-conversion-operators/",
  },
  {
    id: 286,
    difficulty: "Easy",
    topic: "OOP",
    question: "Can a class have more than one constructor?",
    options: [
      "Yes -- constructors can be overloaded with different parameter lists",
      "Only if one of the constructors for that class is a copy constructor",
      "Only if the class is declared abstract using a pure virtual function",
      "No -- the C++ standard says a class can only have one constructor",
    ],
    correctIndex: 0,
    explanation:
      "Constructors follow the same overloading rules as regular functions. A class commonly has a default constructor, a parameterized constructor, and a copy/move constructor.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-function-overloading/",
  },
  {
    id: 287,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What is the only difference between class and struct in C++?",
    options: [
      "Classes are allocated on the heap, structs on the stack",
      "The default access specifier: private for class, public for struct",
      "Structs cannot have member functions, only plain data fields and no methods",
      "Structs cannot use inheritance or derive from other types in any way",
    ],
    correctIndex: 1,
    explanation:
      "In C++, struct and class are nearly identical. The only difference is the default access level: struct defaults to public, class defaults to private. This applies to both members and inheritance.",
    link: "https://www.learncpp.com/cpp-tutorial/structs-vs-classes/",
  },
  {
    id: 288,
    difficulty: "Easy",
    topic: "OOP",
    question: "What does marking a class as final do?",
    code: `class Connection final {\n    // ...\n};`,
    options: [
      "Prevents any class from inheriting from it",
      "Makes all member functions const",
      "Prevents the class from being copied",
      "Prevents the class from being instantiated",
    ],
    correctIndex: 0,
    explanation:
      "The final specifier on a class prevents further derivation. Any attempt to inherit from a final class results in a compilation error.",
    link: "https://en.cppreference.com/w/cpp/language/final.html",
  },
  {
    id: 289,
    difficulty: "Easy",
    topic: "OOP",
    question: "What does final mean when applied to a virtual function?",
    code: `class Base {\npublic:\n    virtual void draw() const final;\n};`,
    options: [
      "The function must return void, no other type",
      "The function is pure virtual, needing an override",
      "No derived class can override this function",
      "The function cannot be called by any code at all",
    ],
    correctIndex: 2,
    explanation:
      "Marking a virtual function as final means any attempt to override it in a derived class will produce a compilation error. This is useful to lock down behavior in a class hierarchy.",
    link: "https://en.cppreference.com/w/cpp/language/final.html",
  },
  {
    id: 290,
    difficulty: "Easy",
    topic: "OOP",
    question: "When is a destructor automatically called?",
    options: [
      "Destructors are never called automatically",
      "At the end of the program only",
      "Only when you explicitly call delete",
      "When an object goes out of scope or is deleted",
    ],
    correctIndex: 3,
    explanation:
      "For stack objects, the destructor runs when the object leaves scope. For heap objects, it runs when delete is called. The destructor cleans up resources owned by the object.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-destructors/",
  },
  {
    id: 291,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What is the difference between overriding and overloading?",
    options: [
      "Overriding is resolved at compile time using static type information from the declared variable; overloading is resolved at runtime via the vtable pointer",
      "They are two names for the same concept",
      "Overloading requires the virtual keyword on the base declaration to enable dispatch; overriding does not need any special keyword or annotation at all",
      "Overriding replaces a base class virtual function in a derived class; overloading provides multiple functions with the same name but different parameters",
    ],
    correctIndex: 3,
    explanation:
      "Overloading is compile-time (static) polymorphism: same name, different signatures. Overriding is runtime (dynamic) polymorphism: a derived class provides its own implementation of a base class virtual function.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-functions/",
  },
  {
    id: 292,
    difficulty: "Easy",
    topic: "OOP",
    question: "What does the scope resolution operator :: do in this context?",
    code: `class Logger {\npublic:\n    static int count;\n    void print();\n};\n\nint Logger::count = 0;\nvoid Logger::print() { /* ... */ }`,
    options: [
      "It dereferences a pointer to the class",
      "It imports all members of Logger into the current scope",
      "It creates a new instance of Logger",
      "It specifies that count and print belong to the Logger class",
    ],
    correctIndex: 3,
    explanation:
      "The scope resolution operator :: is used to define class members outside the class body and to access static members or specify which scope a name belongs to.",
    link: "https://www.learncpp.com/cpp-tutorial/static-member-functions/",
  },
  {
    id: 293,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What does this member initializer list do?",
    code: `class Point {\n    int x, y;\npublic:\n    Point(int a, int b) : x(a), y(b) {}\n};`,
    options: [
      "Creates two separate Point objects from the integer arguments",
      "Declares x and y as static members shared across all instances",
      "Directly initializes x and y before the constructor body runs",
      "Assigns a and b to x and y after the object is fully constructed",
    ],
    correctIndex: 2,
    explanation:
      "The member initializer list (after the colon) initializes members directly, which is more efficient than assigning inside the body. For const and reference members, this is the only option.",
    link: "https://www.learncpp.com/cpp-tutorial/constructor-member-initializer-lists/",
  },
  {
    id: 294,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "Composition models which relationship between classes?",
    options: [
      "is-a (e.g., a Dog is an Animal)",
      "has-a (e.g., a Car has an Engine)",
      "uses-a (e.g., a Logger uses a File)",
      "acts-as (e.g., a Proxy acts as a Server)",
    ],
    correctIndex: 1,
    explanation:
      "Composition models a has-a relationship: one class contains an instance of another as a member. Inheritance models is-a. Prefer composition over inheritance when has-a is the natural relationship.",
    link: "https://www.learncpp.com/cpp-tutorial/composition/",
  },
  {
    id: 295,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What does the compiler-generated copy constructor do by default?",
    options: [
      "Performs a member-wise (shallow) copy of each data member",
      "Deep copies all dynamically allocated memory",
      "Calls the default constructor, then copies each member",
      "Does nothing -- all members are left uninitialized",
    ],
    correctIndex: 0,
    explanation:
      "The implicit copy constructor copies each member using its own copy constructor. For raw pointers, this copies the pointer value (not the pointed-to data), which is why classes managing resources often need a custom copy constructor.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-the-copy-constructor/",
  },
  {
    id: 296,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What does using Base::Base; in a derived class do?",
    code: `class Base {\npublic:\n    Base(int x);\n    Base(int x, int y);\n};\n\nclass Derived : public Base {\npublic:\n    using Base::Base;\n};`,
    options: [
      "Inherits all constructors from Base into Derived",
      "Hides all Base constructors",
      "Creates aliases for Base member functions",
      "Makes Base constructors private in Derived",
    ],
    correctIndex: 0,
    explanation:
      "using Base::Base; inherits the base class constructors, allowing Derived to be constructed with the same argument lists as Base without rewriting them.",
    link: "https://en.cppreference.com/w/cpp/language/using_declaration.html",
  },
  {
    id: 297,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "Can an abstract class have non-pure (regular) virtual functions with implementations?",
    options: [
      "Yes -- an abstract class only needs at least one pure virtual function",
      "Only if the functions are static",
      "Only if the functions are private",
      "No -- all functions in an abstract class must be pure virtual",
    ],
    correctIndex: 0,
    explanation:
      "An abstract class is defined by having at least one pure virtual function. It can still have fully implemented methods, data members, constructors, and destructors.",
    link: "https://www.learncpp.com/cpp-tutorial/pure-virtual-functions-abstract-base-classes-and-interface-classes/",
  },
  {
    id: 298,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is the purpose of getter and setter methods?",
    code: `class Account {\n    double balance;\npublic:\n    double getBalance() const { return balance; }\n    void setBalance(double b) { balance = b; }\n};`,
    options: [
      "They automatically synchronize access to member variables across multiple threads in a safe manner",
      "They are required for all member variables by the C++ standard or the code will not compile",
      "They make member variables static so they can be accessed without an object instance at all",
      "They provide controlled access to private data, enabling validation and encapsulation",
    ],
    correctIndex: 3,
    explanation:
      "Getters and setters enforce encapsulation. The setter can validate input before modifying state, and the getter can control what is exposed. This lets you change internal representation without breaking external code.",
    link: "https://www.learncpp.com/cpp-tutorial/getters-and-setters/",
  },
  {
    id: 299,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is the output of this program?",
    code: `class Animal {\npublic:\n    virtual void speak() { std::cout << "Animal"; }\n};\n\nclass Cat : public Animal {\npublic:\n    void speak() override { std::cout << "Meow"; }\n};\n\nvoid makeSound(Animal& a) { a.speak(); }\n\nint main() {\n    Cat c;\n    makeSound(c);\n}`,
    options: ["Meow", "AnimalMeow", "Compilation error", "Animal"],
    correctIndex: 0,
    explanation:
      "Because speak() is virtual and a Cat is passed by reference, dynamic dispatch calls Cat::speak(). This is runtime polymorphism in action.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-functions/",
  },
  {
    id: 300,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is the syntax for multiple inheritance?",
    code: `class Printable {\npublic:\n    virtual void print() = 0;\n};\n\nclass Serializable {\npublic:\n    virtual void serialize() = 0;\n};\n\nclass Document : public Printable, public Serializable {\n    void print() override {}\n    void serialize() override {}\n};`,
    options: [
      "This is invalid syntax",
      "This requires the virtual keyword on each inheritance specifier to resolve ambiguity issues",
      "This is valid -- a class can inherit from multiple base classes using a comma-separated list",
      "This only works if both base classes are abstract interfaces with no data members defined",
    ],
    correctIndex: 2,
    explanation:
      "C++ supports multiple inheritance. A class lists its base classes separated by commas after the colon. Each base can have its own access specifier.",
    link: "https://www.learncpp.com/cpp-tutorial/multiple-inheritance/",
  },
  {
    id: 301,
    difficulty: "Easy",
    topic: "OOP",
    question:
      "What happens if you don't define any constructor in a class?",
    options: [
      "The class cannot be instantiated without an explicitly defined constructor",
      "The compiler generates a default constructor that default-initializes each member",
      "The class is treated as abstract and cannot be instantiated directly",
      "All member variables are automatically set to zero regardless of type",
    ],
    correctIndex: 1,
    explanation:
      "If no constructors are declared, the compiler implicitly generates a public default constructor. It default-initializes each member (which for built-in types means they may be left uninitialized).",
    link: "https://www.learncpp.com/cpp-tutorial/default-constructors-and-default-arguments/",
  },
  {
    id: 302,
    difficulty: "Medium",
    topic: "OOP",
    question: "What does this program print?",
    code: `class Base {\npublic:\n    Base() { init(); }\n    virtual void init() { std::cout << "Base"; }\n};\n\nclass Derived : public Base {\npublic:\n    void init() override { std::cout << "Derived"; }\n};\n\nint main() { Derived d; }`,
    options: ["Undefined behavior", "Base", "BaseDerived", "Derived"],
    correctIndex: 1,
    explanation:
      "During Base's constructor, the object's dynamic type is still Base -- the Derived part has not been constructed yet. Virtual calls in constructors resolve to the current class's version, not the derived override.",
    link: "https://www.learncpp.com/cpp-tutorial/calling-virtual-functions-during-construction-and-destruction/",
  },
  {
    id: 303,
    difficulty: "Medium",
    topic: "OOP",
    question: "What happens when you call d.show()?",
    code: `class Base {\npublic:\n    void show(int x) { std::cout << "Base:" << x; }\n};\n\nclass Derived : public Base {\npublic:\n    void show(std::string s) { std::cout << "Derived:" << s; }\n};\n\nDerived d;\nd.show(42);`,
    options: [
      "Prints Derived:42",
      "Calls both overloads sequentially, printing both Base:42 and Derived:42",
      "Prints Base:42 -- the base class show(int) is found through normal lookup",
      "Compilation error",
    ],
    correctIndex: 3,
    explanation:
      "When a derived class declares a function with the same name as a base class function (regardless of parameters), it hides all base class versions. Add using Base::show; in Derived to bring them back into scope.",
    link: "https://www.learncpp.com/cpp-tutorial/hiding-inherited-functionality/",
  },
  {
    id: 304,
    difficulty: "Medium",
    topic: "OOP",
    question: "What is a covariant return type?",
    code: `class Base {\npublic:\n    virtual Base* clone() const { return new Base(*this); }\n};\n\nclass Derived : public Base {\npublic:\n    Derived* clone() const override { return new Derived(*this); }\n};`,
    options: [
      "A template-based return type deduction mechanism that infers the return type from the derived class",
      "A compilation error",
      "A feature that allows an overriding function to return a pointer/reference to a more derived type",
      "A deprecated feature that was available in earlier C++ standards but was officially removed in C++17",
    ],
    correctIndex: 2,
    explanation:
      "Covariant return types allow an override to return a pointer or reference to a class derived from the base function's return type. This makes clone() patterns more natural.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 305,
    difficulty: "Medium",
    topic: "OOP",
    question: "What happens when dynamic_cast fails on a reference?",
    code: `Base& ref = someObject;\nDerived& d = dynamic_cast<Derived&>(ref);`,
    options: [
      "Throws std::bad_cast",
      "Undefined behavior",
      "Returns a default-constructed Derived",
      "Returns a null reference",
    ],
    correctIndex: 0,
    explanation:
      "dynamic_cast on a pointer returns nullptr on failure, but on a reference it throws std::bad_cast because there is no such thing as a null reference.",
    link: "https://en.cppreference.com/w/cpp/language/dynamic_cast.html",
  },
  {
    id: 306,
    difficulty: "Medium",
    topic: "OOP",
    question: "Why is operator<< typically overloaded as a friend rather than a member function?",
    code: `class Vec2 {\n    double x, y;\n    friend std::ostream& operator<<(std::ostream& os, const Vec2& v);\n};`,
    options: [
      "Because member operator<< would require ostream to be on the right side: v << std::cout",
      "Because friend functions are always faster than member functions due to reduced indirection",
      "Because operator<< cannot be overloaded as a member function under the C++ standard",
      "Because only friend functions can return ostream references for chaining output calls",
    ],
    correctIndex: 0,
    explanation:
      "A binary operator's left operand is the object the member function is called on. For std::cout << v, the left operand is ostream, not Vec2. Since we can't add a member to ostream, we use a free or friend function.",
    link: "https://www.learncpp.com/cpp-tutorial/overloading-the-io-operators/",
  },
  {
    id: 307,
    difficulty: "Medium",
    topic: "OOP",
    question: "What is the Rule of Three?",
    options: [
      "A class should never have more than three public member functions to keep the interface simple and maintainable",
      "If a class defines a destructor, copy constructor, or copy assignment operator, it should define all three",
      "Inheritance hierarchies in C++ should not exceed three levels of depth to avoid excessive coupling and complexity",
      "A function should take no more than three parameters in its signature to maintain readability and clean design",
    ],
    correctIndex: 1,
    explanation:
      "If a class needs custom behavior for any one of the destructor, copy constructor, or copy assignment operator (typically because it manages a resource), it almost certainly needs all three to handle copying and cleanup correctly.",
    link: "https://www.learncpp.com/cpp-tutorial/the-rule-of-three-and-the-rule-of-five/",
  },
  {
    id: 308,
    difficulty: "Medium",
    topic: "OOP",
    question: "With private inheritance, how are inherited public members accessible?",
    code: `class Engine {\npublic:\n    void start() {}\n};\n\nclass Car : private Engine {\npublic:\n    void ignition() { start(); }  // OK internally\n};`,
    options: [
      "car.start() works only if Engine is abstract",
      "car.start() fails",
      "car.start() fails",
      "car.start() works",
    ],
    correctIndex: 1,
    explanation:
      "Private inheritance makes all inherited members (public and protected) private in the derived class. External code cannot access them. The derived class itself can still use them internally.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-inheritance/",
  },
  {
    id: 309,
    difficulty: "Medium",
    topic: "OOP",
    question: "What does this constructor delegation do?",
    code: `class Widget {\n    int id;\n    std::string name;\npublic:\n    Widget(int i, std::string n) : id(i), name(std::move(n)) {}\n    Widget(int i) : Widget(i, "default") {}\n    Widget() : Widget(0) {}\n};`,
    options: [
      "Each simpler constructor delegates to a more specific one, forming a chain of initialization",
      "Compilation error",
      "Creates three separate objects",
      "The default constructor Widget() will recurse infinitely because of the circular chain",
    ],
    correctIndex: 0,
    explanation:
      "Constructor delegation (C++11) allows one constructor to call another. Here Widget() calls Widget(0), which calls Widget(0, \"default\"). This avoids code duplication.",
    link: "https://en.cppreference.com/w/cpp/language/constructor.html",
  },
  {
    id: 310,
    difficulty: "Medium",
    topic: "OOP",
    question: "When is the move constructor called instead of the copy constructor?",
    code: `Widget makeWidget() {\n    Widget w;\n    return w;\n}\n\nWidget a = makeWidget();`,
    options: [
      "When the object is larger than 64 bytes and the compiler determines a move would be more efficient",
      "When the source is an rvalue (temporary or std::move'd object) and a move constructor exists",
      "Only when you explicitly call the move constructor by name using a direct invocation syntax",
      "Never -- the copy constructor is always preferred over the move constructor regardless of value category",
    ],
    correctIndex: 1,
    explanation:
      "The move constructor is selected when the argument is an rvalue -- either a temporary, the return value of a function, or the result of std::move(). Note: copy elision (NRVO) may eliminate the move entirely.",
    link: "https://www.learncpp.com/cpp-tutorial/move-constructors-and-move-assignment/",
  },
  {
    id: 311,
    difficulty: "Medium",
    topic: "OOP",
    question: "What is RAII in C++?",
    options: [
      "A runtime type information system that provides dynamic_cast and typeid for classes",
      "An optimization that reduces virtual function overhead through devirtualization at compile time",
      "A design pattern where resources are acquired in constructors and released in destructors",
      "A memory allocator replacing new and delete with a custom arena-based allocation strategy",
    ],
    correctIndex: 2,
    explanation:
      "Resource Acquisition Is Initialization (RAII) ties resource lifetime to object lifetime. The constructor acquires (e.g., opens a file, locks a mutex), and the destructor releases. This guarantees cleanup even when exceptions are thrown.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-smart-pointers-move-semantics/",
  },
  {
    id: 312,
    difficulty: "Medium",
    topic: "OOP",
    question: "What error does this code produce?",
    code: `class A {\npublic:\n    void doWork() { std::cout << "A"; }\n};\n\nclass B {\npublic:\n    void doWork() { std::cout << "B"; }\n};\n\nclass C : public A, public B {};\n\nC c;\nc.doWork();`,
    options: [
      "Prints AB -- both versions are called in order",
      "Prints A -- the first base class wins in resolution",
      "Prints B -- the last base class wins in resolution",
      "Compilation error",
    ],
    correctIndex: 3,
    explanation:
      "Both A and B have doWork(), so calling it on C is ambiguous. You must qualify the call: c.A::doWork() or c.B::doWork(), or add a using declaration in C.",
    link: "https://www.learncpp.com/cpp-tutorial/multiple-inheritance/",
  },
  {
    id: 313,
    difficulty: "Medium",
    topic: "OOP",
    question: "What is the problem with this code?",
    code: `class Meter {\npublic:\n    Meter(double v) : val(v) {}\n    double val;\n};\n\nvoid print(Meter m) { std::cout << m.val; }\n\nprint(3.5);  // compiles!`,
    options: [
      "This is a compilation error",
      "The implicit conversion from double to Meter is potentially confusing; marking the constructor explicit would prevent it",
      "There is no problem",
      "This causes undefined behavior at runtime because the double value 3.5 is reinterpreted as raw memory for the Meter object",
    ],
    correctIndex: 1,
    explanation:
      "A single-argument constructor acts as an implicit conversion operator unless declared explicit. print(3.5) silently converts 3.5 to Meter(3.5). This can hide bugs and make code surprising.",
    link: "https://www.learncpp.com/cpp-tutorial/explicit-constructors-and-conversion-operators/",
  },
  {
    id: 314,
    difficulty: "Medium",
    topic: "OOP",
    question: "What does the mutable keyword allow?",
    code: `class Cache {\n    mutable int hits = 0;\npublic:\n    int lookup(int key) const {\n        ++hits;  // OK because hits is mutable\n        return key * 2;\n    }\n};`,
    options: [
      "It allows a const member function to modify that specific member",
      "It makes the member thread-safe with implicit synchronization",
      "It makes the member volatile, preventing register caching",
      "It prevents the member from being copied during assignment",
    ],
    correctIndex: 0,
    explanation:
      "mutable exempts a data member from the const restriction on the enclosing object. This is used for caches, mutexes, and other members that don't affect the logical state of the object.",
    link: "https://en.cppreference.com/w/cpp/language/cv.html",
  },
  {
    id: 315,
    difficulty: "Medium",
    topic: "OOP",
    question:
      "Members are initialized in which order?",
    code: `class Widget {\n    int a;\n    int b;\npublic:\n    Widget() : b(1), a(b) {}  // warning!\n};`,
    options: [
      "In alphabetical order",
      "In an unspecified, implementation-defined order",
      "In the order the members are declared in the class: a first, then b",
      "In the order listed in the initializer list: b first, then a",
    ],
    correctIndex: 2,
    explanation:
      "Members are always initialized in the order they are declared in the class, regardless of the order in the initializer list. Here a is initialized before b, so a(b) reads uninitialized b -- a subtle bug.",
    link: "https://www.learncpp.com/cpp-tutorial/constructor-member-initializer-lists/",
  },
  {
    id: 316,
    difficulty: "Medium",
    topic: "OOP",
    question:
      "Can a derived class override a virtual function with a more restrictive access specifier?",
    code: `class Base {\npublic:\n    virtual void doStuff() {}\n};\n\nclass Derived : public Base {\nprivate:\n    void doStuff() override {}\n};`,
    options: [
      "Legal only if the base function is declared protected rather than public in the class",
      "Compilation error",
      "Legal, but calling base->doStuff() still works because access is checked on the static type",
      "Legal, and calling base->doStuff() through a Base pointer is blocked at runtime",
    ],
    correctIndex: 2,
    explanation:
      "Access specifiers are checked at compile time using the static type. Through a Base*, doStuff() is public, so the call compiles. At runtime, Derived::doStuff() executes. This is surprising but valid C++.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 317,
    difficulty: "Medium",
    topic: "OOP",
    question: "What do = default and = delete do for special member functions?",
    code: `class NoCopy {\npublic:\n    NoCopy() = default;\n    NoCopy(const NoCopy&) = delete;\n    NoCopy& operator=(const NoCopy&) = delete;\n};`,
    options: [
      "Both = default and = delete are no-ops that serve only as documentation hints and have no actual effect on the generated code",
      "= default asks the compiler to generate the default implementation; = delete prevents the function from being called",
      "= default makes the function abstract and forces derived classes to override it; = delete removes it from the symbol table at link time",
      "= default sets all member variables to zero in the function body; = delete calls the destructor to clean up resources immediately",
    ],
    correctIndex: 1,
    explanation:
      "= default explicitly asks for the compiler-generated version. = delete makes any call to that function a compilation error. Together they give precise control over which special members exist.",
    link: "https://www.learncpp.com/cpp-tutorial/deleting-functions/",
  },
  {
    id: 318,
    difficulty: "Medium",
    topic: "OOP",
    question:
      "If a base class has a static member, how many copies exist when there are multiple derived classes?",
    code: `class Base {\npublic:\n    static int count;\n};\nint Base::count = 0;\n\nclass A : public Base {};\nclass B : public Base {};`,
    options: [
      "One -- static members are shared across the entire hierarchy",
      "Two -- each derived class gets its own copy of the static",
      "Three -- one copy for Base, one for A, and one for B",
      "Zero -- static members are not inherited by derived classes",
    ],
    correctIndex: 0,
    explanation:
      "A static member belongs to the class in which it is defined, not to any object. Derived classes can access it, but they share the same single instance. Base::count, A::count, and B::count all refer to the same variable.",
    link: "https://www.learncpp.com/cpp-tutorial/static-member-variables/",
  },
  {
    id: 319,
    difficulty: "Medium",
    topic: "OOP",
    question: "Can a nested class access the private members of its enclosing class?",
    code: `class Outer {\n    int secret = 42;\n    class Inner {\n        void peek(Outer& o) {\n            std::cout << o.secret;  // Is this legal?\n        }\n    };\n};`,
    options: [
      "Only if Inner is declared in the public section of Outer’s definition",
      "No -- Inner has no special access to Outer’s private members without a friend",
      "Only if the secret member is declared protected rather than private",
      "Yes -- since C++11, a nested class is a friend of its enclosing class",
    ],
    correctIndex: 3,
    explanation:
      "Since C++11, a nested class can access all members (including private) of its enclosing class, given an object. The nested class is implicitly treated as a friend.",
    link: "https://en.cppreference.com/w/cpp/language/nested_types.html",
  },
  {
    id: 320,
    difficulty: "Medium",
    topic: "OOP",
    question: "How do you call a base class version of an overridden function from the derived class?",
    code: `class Base {\npublic:\n    virtual void log() { std::cout << "Base::log "; }\n};\n\nclass Derived : public Base {\npublic:\n    void log() override {\n        Base::log();  // explicit base call\n        std::cout << "Derived::log";\n    }\n};`,
    options: [
      "Use super.log() like in Java",
      "Use this->Base.log()",
      "Use the scope resolution operator: Base::log()",
      "It's not possible",
    ],
    correctIndex: 2,
    explanation:
      "C++ has no super keyword. To call the base class version, use the scope resolution operator: Base::log(). This bypasses virtual dispatch and calls the base version directly.",
    link: "https://www.learncpp.com/cpp-tutorial/calling-inherited-functions-and-overriding-behavior/",
  },
  {
    id: 321,
    difficulty: "Medium",
    topic: "OOP",
    question:
      "What does this code demonstrate?",
    code: `class Widget {\npublic:\n    void process() { std::cout << "non-const"; }\n    void process() const { std::cout << "const"; }\n};\n\nconst Widget cw;\nWidget w;\ncw.process();\nw.process();`,
    options: [
      "Compilation error",
      "Both objects call the non-const version of process regardless of qualification",
      "const overloading: cw calls the const version, w calls the non-const version",
      "Both objects call the const version of process regardless of qualification",
    ],
    correctIndex: 2,
    explanation:
      "A member function can be overloaded on const. When called on a const object, the const overload is selected. On a non-const object, the non-const overload is preferred.",
    link: "https://www.learncpp.com/cpp-tutorial/const-class-objects-and-const-member-functions/",
  },
  {
    id: 322,
    difficulty: "Hard",
    topic: "OOP",
    question: "How does virtual dispatch work internally in most C++ implementations?",
    options: [
      "The runtime uses string-based function name lookup similar to reflection, searching a hash map of method signatures to find the correct implementation at each call",
      "Virtual functions are inlined and resolved entirely at compile time using template-based static dispatch mechanisms that eliminate all dynamic overhead from the program",
      "The compiler generates if-else chains to check the dynamic type at each call site and dispatches to the matching implementation based on runtime type comparison",
      "Each polymorphic object contains a vptr pointing to a vtable of function pointers; virtual calls are resolved by an indirect call through the vtable",
    ],
    correctIndex: 3,
    explanation:
      "Most implementations store a hidden vptr in each polymorphic object. The vptr points to a per-class vtable -- an array of function pointers for each virtual function. A virtual call dereferences the vptr, indexes into the vtable, and calls through the function pointer.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 323,
    difficulty: "Hard",
    topic: "OOP",
    question: "What pattern does this code demonstrate, and what is its benefit?",
    code: `template<typename Derived>\nclass Counter {\n    static int count;\npublic:\n    Counter() { ++count; }\n    ~Counter() { --count; }\n    static int getCount() { return count; }\n};\ntemplate<typename T> int Counter<T>::count = 0;\n\nclass Dog : public Counter<Dog> {};\nclass Cat : public Counter<Cat> {};`,
    options: [
      "Template method pattern",
      "Observer pattern",
      "CRTP -- each derived class gets its own static count because each instantiation is a unique base class",
      "This is undefined behavior",
    ],
    correctIndex: 2,
    explanation:
      "CRTP passes the derived class as a template argument to the base. Counter<Dog> and Counter<Cat> are different classes, each with their own static count. This enables per-type static data and compile-time polymorphism.",
    link: "https://en.cppreference.com/w/cpp/language/crtp.html",
  },
  {
    id: 324,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the Empty Base Optimization (EBO)?",
    code: `class Empty {};\n\nclass NotOptimized {\n    Empty e;\n    int x;\n};\n\nclass Optimized : private Empty {\n    int x;\n};\n\n// sizeof(NotOptimized) > sizeof(Optimized) typically`,
    options: [
      "The compiler removes all virtual functions from empty base classes to reduce the size of the vtable",
      "Empty classes are always allocated on the stack regardless of context, bypassing normal storage duration rules",
      "Empty classes cannot be used as bases",
      "When an empty class is used as a base, the compiler can give it zero size, avoiding wasted padding",
    ],
    correctIndex: 3,
    explanation:
      "An empty class as a member must have size >= 1 (to give it a unique address). But as a base class, the compiler can overlap it with the derived class's data, using zero extra bytes. This is EBO, widely used in the STL (e.g., stateless allocators and comparators).",
    link: "https://en.cppreference.com/w/cpp/language/ebo.html",
  },
  {
    id: 325,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the Non-Virtual Interface (NVI) idiom?",
    code: `class Shape {\npublic:\n    void draw() const {       // non-virtual public interface\n        validate();\n        doDraw();             // calls the private virtual\n        log();\n    }\nprivate:\n    virtual void doDraw() const = 0;  // private virtual\n    void validate() const {}\n    void log() const {}\n};`,
    options: [
      "A technique that eliminates virtual function overhead entirely by converting all virtual calls to direct calls at compile time through static analysis",
      "An anti-pattern that makes virtual functions slower by adding unnecessary indirection layers between the caller and the implementation",
      "A pattern where the public interface is non-virtual, and the customization points are private virtual functions",
      "A pattern that replaces virtual functions with function pointers stored as data members to enable runtime polymorphism without using the vtable mechanism",
    ],
    correctIndex: 2,
    explanation:
      "NVI separates the public interface (non-virtual) from the customization points (private virtual). The base class controls what happens before and after the virtual call, enforcing invariants. Derived classes override only the private virtual.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 326,
    difficulty: "Hard",
    topic: "OOP",
    question: "What does this declaration actually do?",
    code: `class Timer {\npublic:\n    Timer(int interval);\n};\n\nTimer t(Timer(10));`,
    options: [
      "Creates a Timer t by copy-constructing from a temporary Timer(10) using the implicit copy constructor generated by the compiler automatically",
      "Creates two Timer objects: one temporary Timer(10) and one named t that is copy-initialized from the temporary using the default copy constructor",
      "Compilation error",
      "This is the 'most vexing parse': the compiler interprets it as a function declaration",
    ],
    correctIndex: 3,
    explanation:
      "C++'s grammar ambiguity means Timer t(Timer(10)) can be parsed as a function declaration: t is a function taking a parameter of type Timer (named 10 is invalid, but Timer(int) is valid as a type). Use braces -- Timer t{Timer{10}} -- to avoid this.",
    link: "https://en.wikipedia.org/wiki/Most_vexing_parse",
  },
  {
    id: 327,
    difficulty: "Hard",
    topic: "OOP",
    question: "What does this conversion operator do, and what is the risk?",
    code: `class BigInt {\n    long long value;\npublic:\n    BigInt(long long v) : value(v) {}\n    operator bool() const { return value != 0; }\n};\n\nBigInt a(5), b(10);\nstd::cout << (a + b);`,
    options: [
      "Prints 1 -- boolean addition saturates at 1 because true + true caps",
      "Compilation error",
      "Prints 15 -- the addition operates on the BigInt values directly",
      "Prints 2 -- both a and b are implicitly converted to bool",
    ],
    correctIndex: 3,
    explanation:
      "Without operator+, the compiler looks for implicit conversions. operator bool() converts both to bool (true). Then bool is promoted to int, and 1 + 1 = 2. This is why C++11 introduced explicit operator bool().",
    link: "https://en.cppreference.com/w/cpp/language/cast_operator.html",
  },
  {
    id: 328,
    difficulty: "Hard",
    topic: "OOP",
    question: "How does the Rule of Five extend the Rule of Three?",
    options: [
      "It adds two more overloads of the assignment operator: one for rvalue references and one for const references",
      "It adds a virtual clone() function and a factory method for polymorphic deep-copying of derived objects",
      "It adds move constructor and move assignment operator to the list of special members that should be defined together",
      "It adds the default constructor and a swap function to the set of special members that must be coordinated",
    ],
    correctIndex: 2,
    explanation:
      "The Rule of Five says: if you define any of destructor, copy constructor, copy assignment, move constructor, or move assignment, you should define all five. Move semantics (C++11) added two more special members to manage.",
    link: "https://www.learncpp.com/cpp-tutorial/the-rule-of-three-and-the-rule-of-five/",
  },
  {
    id: 329,
    difficulty: "Hard",
    topic: "OOP",
    question: "What does this program output?",
    code: `class Base {\npublic:\n    virtual ~Base() { std::cout << "~B "; }\n    virtual std::string name() { return "Base"; }\n};\n\nclass Derived : public Base {\npublic:\n    ~Derived() override { std::cout << "~D(" << name() << ") "; }\n};\n\nint main() { Base* p = new Derived(); delete p; }`,
    options: [
      "~D(Derived) ~B",
      "~D(Derived) ~B ~D(Derived)",
      "~D(Base) ~B",
      "~B ~D(Derived)",
    ],
    correctIndex: 0,
    explanation:
      "During Derived's destructor, the dynamic type is still Derived, so name() returns \"Derived\". Virtual dispatch works normally in the destructor of the current class. It's only after Derived's destructor finishes that the type reverts to Base.",
    link: "https://www.learncpp.com/cpp-tutorial/calling-virtual-functions-during-construction-and-destruction/",
  },
  {
    id: 330,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the syntax for a pointer to member function, and how is it called?",
    code: `class Widget {\npublic:\n    void process(int x) { std::cout << x; }\n};\n\nvoid (Widget::*pmf)(int) = &Widget::process;\nWidget w;\n(w.*pmf)(42);`,
    options: [
      "This requires static_cast to convert the member function address to the correct pointer-to-member type",
      "This is invalid syntax",
      "This is valid: pmf is a pointer to Widget::process, and .* is the pointer-to-member dereference operator",
      "This creates a regular function pointer equivalent to void(*pmf)(int) callable without an object",
    ],
    correctIndex: 2,
    explanation:
      "Pointers to member functions have a special type (ReturnType (Class::*)(Args)). They require an object to call through, using .* (for objects) or ->* (for pointers). They cannot be converted to regular function pointers because they need a this context.",
    link: "https://en.cppreference.com/w/cpp/language/pointer.html",
  },
  {
    id: 331,
    difficulty: "Hard",
    topic: "OOP",
    question: "Can a pure virtual function have an implementation?",
    code: `class Base {\npublic:\n    virtual void log() = 0;\n};\n\nvoid Base::log() {\n    std::cout << "Base default log";\n}\n\nclass Derived : public Base {\npublic:\n    void log() override {\n        Base::log();  // call the pure virtual's implementation\n        std::cout << " + Derived";\n    }\n};`,
    options: [
      "Legal, but providing a body for the pure virtual function makes the class no longer abstract and allows direct instantiation",
      "Compilation error",
      "Legal only if the pure virtual function is declared as protected in the base class, not as public or private",
      "Legal -- the class is still abstract, but derived classes can explicitly call the base implementation via Base::log()",
    ],
    correctIndex: 3,
    explanation:
      "A pure virtual function can have an out-of-line definition. The class remains abstract (cannot be instantiated), but derived classes can call the implementation using qualified name lookup (Base::log()). This is useful for providing default behavior.",
    link: "https://en.cppreference.com/w/cpp/language/abstract_class.html",
  },
  {
    id: 332,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the problem with this code?",
    code: `class Animal {\npublic:\n    virtual std::string speak() { return "..."; }\n    virtual ~Animal() = default;\n};\nclass Cat : public Animal {\npublic:\n    std::string speak() override { return "Meow"; }\n};\n\nstd::vector<Animal> zoo;\nzoo.push_back(Cat());\nstd::cout << zoo[0].speak();`,
    options: [
      "Object slicing: the Cat is copied into a vector of Animal by value, losing the Cat part. Prints '...'",
      "Prints Meow -- polymorphism works correctly because the vtable is preserved when copying by value",
      "Compilation error",
      "Undefined behavior",
    ],
    correctIndex: 0,
    explanation:
      "Storing by value in a vector of base type slices the derived object. The vector contains Animal copies, not Cat objects. Use std::vector<std::unique_ptr<Animal>> to preserve polymorphism.",
    link: "https://www.learncpp.com/cpp-tutorial/object-slicing/",
  },
  {
    id: 333,
    difficulty: "Hard",
    topic: "OOP",
    question: "In virtual inheritance, which class is responsible for constructing the virtual base?",
    code: `struct Base { Base(int x) { std::cout << x; } };\nstruct Left : virtual Base { Left() : Base(1) {} };\nstruct Right : virtual Base { Right() : Base(2) {} };\nstruct Diamond : Left, Right { Diamond() : Base(3), Left(), Right() {} };\n\nDiamond d;`,
    options: [
      "Diamond constructs Base with 3",
      "Left constructs Base with 1 because it is first in the inheritance list order",
      "Right constructs Base with 2 because it is last in the inheritance declaration",
      "Base is constructed three times with 1, 2, and 3",
    ],
    correctIndex: 0,
    explanation:
      "With virtual inheritance, the most-derived class (Diamond) is responsible for directly initializing all virtual base classes. Left's and Right's Base(...) initializers are ignored when Diamond is the most-derived class.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-base-classes/",
  },
  {
    id: 334,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the overhead of RTTI (Runtime Type Information)?",
    options: [
      "Zero cost -- RTTI is resolved entirely at compile time using template-based type deduction with no runtime data structures, meaning there is no memory or performance overhead for polymorphic classes",
      "Each polymorphic class stores a type_info object, adding a small per-class cost; dynamic_cast and typeid have a runtime cost proportional to hierarchy depth",
      "RTTI doubles the size of every vtable by adding a mirrored set of entries that encode type metadata for each virtual function, significantly increasing the memory footprint of polymorphic types",
      "Each object stores a full copy of its class name and hierarchy as a string in its memory layout, adding significant per-object memory overhead that scales linearly with hierarchy depth",
    ],
    correctIndex: 1,
    explanation:
      "RTTI adds a pointer to type_info in each class's vtable (not in each object). typeid is a constant-time vtable lookup. dynamic_cast traverses the class hierarchy, which can be slower for deep hierarchies. Some codebases disable RTTI (-fno-rtti) to eliminate this cost.",
    link: "https://en.cppreference.com/w/cpp/language/typeid.html",
  },
  {
    id: 335,
    difficulty: "Hard",
    topic: "OOP",
    question: "What problem does a delegating constructor have with member initializer lists?",
    code: `class Config {\n    int timeout;\n    std::string name;\npublic:\n    Config(int t, std::string n) : timeout(t), name(std::move(n)) {}\n    Config() : Config(30, "default"), timeout(60) {}  // ERROR\n};`,
    options: [
      "This compiles successfully",
      "Compilation error",
      "Compilation error",
      "This compiles but timeout has an undefined value because the delegation and direct initialization conflict at runtime",
    ],
    correctIndex: 2,
    explanation:
      "When a constructor delegates to another, the target constructor initializes the entire object. The delegating constructor cannot also initialize individual members -- the initializer list must contain only the delegating call.",
    link: "https://en.cppreference.com/w/cpp/language/constructor.html",
  },
  {
    id: 336,
    difficulty: "Hard",
    topic: "OOP",
    question: "What does this code output?",
    code: `class A {\npublic:\n    A() { std::cout << "A"; }\n    ~A() { std::cout << "~A"; }\n};\n\nclass B {\npublic:\n    B() { std::cout << "B"; }\n    ~B() { std::cout << "~B"; }\n};\n\nclass C : public A {\n    B b;\npublic:\n    C() { std::cout << "C"; }\n    ~C() { std::cout << "~C"; }\n};`,
    options: [
      "ACB~B~C~A",
      "ABC~A~B~C",
      "BAC~C~A~B",
      "ABC~C~B~A",
    ],
    correctIndex: 3,
    explanation:
      "Construction order: base classes first (A), then members in declaration order (B), then the constructor body (C). Destruction is the exact reverse: ~C, ~B, ~A.",
    link: "https://www.learncpp.com/cpp-tutorial/order-of-construction-of-derived-classes/",
  },
  {
    id: 337,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is the effect of making a destructor protected and non-virtual?",
    code: `class Base {\nprotected:\n    ~Base() = default;\n};\n\nclass Derived : public Base {\npublic:\n    ~Derived() = default;\n};`,
    options: [
      "This is a compilation error",
      "Objects of both Base and Derived cannot be destroyed by any external code regardless of the access specifier",
      "This makes Base abstract, preventing instantiation since the protected destructor acts as a pure virtual function",
      "Base cannot be deleted through a Base* but Derived objects can be created and destroyed normally",
    ],
    correctIndex: 3,
    explanation:
      "A protected destructor prevents external code from deleting through a Base pointer (which would be unsafe without a virtual destructor). Derived's public destructor calls Base's protected destructor, so Derived objects work normally. This is the protected destructor idiom.",
    link: "https://en.cppreference.com/w/cpp/language/destructor.html",
  },
  {
    id: 338,
    difficulty: "Hard",
    topic: "OOP",
    question: "Why does this assertion fail?",
    code: `class Base {\npublic:\n    bool operator==(const Base& other) const {\n        return true;  // simplified\n    }\n};\n\nclass Derived : public Base {\n    int extra = 5;\npublic:\n    bool operator==(const Derived& other) const {\n        return Base::operator==(other) && extra == other.extra;\n    }\n};\n\nDerived d1, d2;\nd2.extra = 99;\nBase& ref1 = d1;\nBase& ref2 = d2;\nassert(ref1 == ref2);  // calls Base::operator==, returns true!`,
    options: [
      "Because d2.extra is private in Derived and cannot be accessed from Base::operator==",
      "Because references cannot be compared with == without an explicit overload for reference types",
      "Because operator== is not virtual, so the call resolves to Base::operator== which ignores extra",
      "The assertion actually passes, which is the correct and intended behavior for these objects",
    ],
    correctIndex: 2,
    explanation:
      "operator== is non-virtual, so through Base references it calls Base::operator==, comparing only the Base parts. This is a form of slicing in comparisons. Solutions include making operator== virtual or using the visitor/double-dispatch pattern.",
    link: "https://en.cppreference.com/w/cpp/language/operators.html",
  },
  {
    id: 339,
    difficulty: "Hard",
    topic: "OOP",
    question: "What does this code do?",
    code: `class Singleton {\n    Singleton() = default;\n    Singleton(const Singleton&) = delete;\n    Singleton& operator=(const Singleton&) = delete;\npublic:\n    static Singleton& instance() {\n        static Singleton s;\n        return s;\n    }\n};`,
    options: [
      "Implements the Meyers' Singleton: a lazy-initialized, thread-safe (since C++11) singleton using a function-local static",
      "Creates a thread-unsafe global object that is eagerly initialized before main() begins execution",
      "This creates a new Singleton each time instance() is called because the static keyword only affects linkage, not storage",
      "This is undefined behavior",
    ],
    correctIndex: 0,
    explanation:
      "C++11 guarantees that function-local static variables are initialized exactly once, even under concurrent access. The private constructor and deleted copy/assignment prevent any other instances. This is Meyers' Singleton -- simple and thread-safe.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 340,
    difficulty: "Hard",
    topic: "OOP",
    question: "What is wrong with this code?",
    code: `class Base {\npublic:\n    virtual std::unique_ptr<Base> clone() const {\n        return std::make_unique<Base>(*this);\n    }\n    virtual ~Base() = default;\n};\n\nclass Derived : public Base {\npublic:\n    std::unique_ptr<Derived> clone() const override {\n        return std::make_unique<Derived>(*this);\n    }\n};`,
    options: [
      "Compilation error",
      "Nothing is wrong",
      "The Derived version of clone shadows but does not override the Base version, causing unexpected static dispatch instead of virtual dispatch",
      "Runtime error -- the unique_ptr managing the Derived object is double-freed because the virtual dispatch creates a duplicate ownership path",
    ],
    correctIndex: 0,
    explanation:
      "Covariant return types require the return types to be pointers or references to classes in an inheritance relationship. unique_ptr<Derived> is not covariant with unique_ptr<Base> -- they are unrelated types. The override must return unique_ptr<Base>.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 341,
    difficulty: "Hard",
    topic: "OOP",
    question: "What subtle difference exists between these two lines?",
    code: `Widget w1 = Widget(42);  // Line A: copy initialization\nWidget w2(42);           // Line B: direct initialization`,
    options: [
      "Line A creates a temporary Widget and then copies it into w1 by invoking the copy constructor; Line B does not create a temporary",
      "Line A calls operator= to assign from the temporary value while Line B directly invokes the constructor, and these follow two entirely different overload resolution paths in the compiler",
      "They are always identical in every respect",
      "Line A requires an accessible copy/move constructor, while Line B only requires the matching constructor. If the copy/move constructor is deleted, Line A fails and Line B succeeds",
    ],
    correctIndex: 3,
    explanation:
      "Copy initialization (=) conceptually constructs a temporary and then copy/move-constructs the target. Even though copy elision (guaranteed since C++17 for prvalues) eliminates the actual copy, pre-C++17 the copy/move constructor must be accessible. Direct initialization has no such requirement.",
    link: "https://en.cppreference.com/w/cpp/language/direct_initialization.html",
  },

  // ── OOP fundamentals (Q1548–Q1556) ──
  {
    id: 1548,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is a class in C++?",
    options: [
      "A user-defined type that bundles data members and member functions into a single unit",
      "A built-in keyword that allocates memory on the heap for a group of related variables",
      "A special function template that generates different versions of code at compile time",
      "A namespace-like construct that only allows static functions and forbids member variables",
    ],
    correctIndex: 0,
    explanation:
      "A class is a user-defined type that combines data members (attributes) and member functions (methods) into one cohesive unit. Classes serve as blueprints for creating objects and are the foundation of object-oriented programming in C++.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-classes/",
  },
  {
    id: 1549,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is an object in C++?",
    options: [
      "A compile-time constant that the preprocessor substitutes before compilation begins",
      "A synonym for a pointer that stores the address of a dynamically allocated variable",
      "A specific instance of a class that occupies memory and holds its own member data",
      "A header file that declares function prototypes and type definitions for a module",
    ],
    correctIndex: 2,
    explanation:
      "An object is a specific instance of a class. When you declare a variable of a class type, the compiler allocates memory for that object's data members. Each object maintains its own copy of non-static data members, while sharing the class's member function definitions.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-classes/",
  },
  {
    id: 1550,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is inheritance in C++?",
    options: [
      "A technique that hides internal data by declaring all member variables as private fields",
      "A mechanism that allows a class to acquire the members and behavior of another class",
      "A compile-time process that inlines all function calls to eliminate virtual dispatch cost",
      "A design pattern that restricts a class to only one instance throughout the application",
    ],
    correctIndex: 1,
    explanation:
      "Inheritance is a mechanism where a new class (derived class) is created from an existing class (base class), automatically acquiring its data members and member functions. This enables code reuse and establishes an is-a relationship between the derived and base classes.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-inheritance/",
  },
  {
    id: 1551,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is polymorphism in C++?",
    options: [
      "A feature that prevents derived classes from overriding base class member functions",
      "A restriction that limits each class to inheriting from exactly one base class only",
      "A compiler optimization that removes unused virtual functions from the final binary",
      "The ability to treat objects of different types through a common interface at runtime",
    ],
    correctIndex: 3,
    explanation:
      "Polymorphism allows objects of different derived classes to be treated uniformly through a base class pointer or reference. When a virtual function is called through a base pointer, the correct derived class version is invoked at runtime via dynamic dispatch, enabling flexible and extensible code.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-functions/",
  },
  {
    id: 1552,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is abstraction in object-oriented programming?",
    options: [
      "The requirement that every class must inherit from at least one abstract base class type",
      "The process of converting all member variables from private access to public access level",
      "A compiler technique that merges multiple small classes into a single optimized structure",
      "The practice of exposing only essential details while hiding complex implementation logic",
    ],
    correctIndex: 3,
    explanation:
      "Abstraction is the practice of exposing only the relevant interface to users while hiding the complex implementation details. In C++, abstraction is achieved through access specifiers, abstract classes, and well-designed public interfaces that let users interact with objects without knowing their internal workings.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-object-oriented-programming/",
  },
  {
    id: 1553,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is a constructor in C++?",
    options: [
      "A regular member function that must be called manually after an object is allocated",
      "A static function that returns a pointer to a newly allocated object on the free store",
      "A special member function that is automatically called when an object is first created",
      "A friend function that initializes private members of a class from outside the scope",
    ],
    correctIndex: 2,
    explanation:
      "A constructor is a special member function with the same name as the class and no return type. It is called automatically when an object is created, allowing you to initialize member variables and acquire resources. A class can have multiple constructors with different parameter lists.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-constructors/",
  },
  {
    id: 1554,
    difficulty: "Easy",
    topic: "OOP",
    question: "What is a virtual function in C++?",
    options: [
      "A function declared in a derived class that cannot be called through a base class pointer",
      "A function declared with the virtual keyword that enables runtime polymorphic dispatch",
      "A function that is automatically inlined by the compiler to avoid function call overhead",
      "A function that only exists at compile time and is removed from the final binary output",
    ],
    correctIndex: 1,
    explanation:
      "A virtual function is a member function declared with the virtual keyword in a base class. When called through a base class pointer or reference, the most-derived override is invoked at runtime. This dynamic dispatch mechanism is the foundation of runtime polymorphism in C++.",
    link: "https://www.learncpp.com/cpp-tutorial/virtual-functions/",
  },
  {
    id: 1555,
    difficulty: "Medium",
    topic: "OOP",
    question: "What is an abstract class in C++?",
    options: [
      "A class that has no member variables and only provides static utility function methods",
      "A class that is marked with the abstract keyword and can only exist on the heap memory",
      "A class that cannot be instantiated because it contains at least one pure virtual function",
      "A class that is declared inside another class and can only be accessed by its enclosing one",
    ],
    correctIndex: 2,
    explanation:
      "An abstract class contains at least one pure virtual function (declared with = 0). It cannot be instantiated directly and serves as an interface that derived classes must implement. Unlike some other languages, C++ does not have an explicit abstract keyword.",
    link: "https://www.learncpp.com/cpp-tutorial/pure-virtual-functions-abstract-base-classes-and-interface-classes/",
  },
  {
    id: 1556,
    difficulty: "Medium",
    topic: "OOP",
    question: "What is operator overloading in C++?",
    options: [
      "A technique that restricts built-in operators to only work with primitive data types",
      "A feature that lets you redefine how built-in operators work with user-defined types",
      "A compiler pass that optimizes repeated use of the same operator into a single call",
      "A mechanism that converts all operator expressions into equivalent function templates",
    ],
    correctIndex: 1,
    explanation:
      "Operator overloading allows you to define custom behavior for built-in operators like +, -, ==, and << when used with your own class types. This makes user-defined types feel natural to use with the same syntax as built-in types. Most operators can be overloaded, with a few exceptions like :: and sizeof.",
    link: "https://www.learncpp.com/cpp-tutorial/introduction-to-operator-overloading/",
  },
];
