import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: 179,
    difficulty: "Easy",
    topic: "Operating Systems",
    question: "What is a process?",
    options: [
      "A program binary stored on disk, waiting to be loaded into memory by the OS",
      "A running instance of a program, with its own address space and resources",
      "A single thread of execution inside the kernel that handles incoming system calls",
      "A function call that has not yet returned, occupying a frame on the call stack",
    ],
    correctIndex: 1,
    explanation:
      "A process is an instance of a program in execution. The OS gives each process its own virtual address space, file descriptor table, and other resources. A program on disk is just a file; it becomes a process when loaded and executed.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-intro.pdf",
  },
  {
    id: 180,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is the key difference between a process and a thread?",
    options: [
      "Threads within the same process share the same address space; processes do not",
      "Threads do not have their own stack",
      "A process can only contain a single thread of execution at any given point during runtime",
      "Threads are always faster than processes because they have lower creation and scheduling overhead",
    ],
    correctIndex: 0,
    explanation:
      "Threads share the same virtual address space (heap, global variables, code) within a process, but each thread has its own stack and register state. Processes have completely separate address spaces, so one process cannot directly access another's memory.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/threads-intro.pdf",
  },
  {
    id: 181,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "On a POSIX system, which file descriptors are automatically open when a process starts?",
    options: [
      "0 (stdin) only",
      "1 (stdout) and 2 (stderr) only",
      "None -- the program must open all file descriptors explicitly",
      "0 (stdin), 1 (stdout), 2 (stderr)",
    ],
    correctIndex: 3,
    explanation:
      "By convention, every POSIX process inherits three open file descriptors: 0 for standard input, 1 for standard output, and 2 for standard error. These are set up by the parent process (usually the shell) before exec.",
    link: "https://man7.org/linux/man-pages/man3/stdin.3.html",
  },
  {
    id: 182,
    difficulty: "Easy",
    topic: "Operating Systems",
    question: "What is a system call?",
    options: [
      "A function call between two user-space libraries that are linked into the same process",
      "A call to main() that starts a program and initializes the runtime environment",
      "A request from a user-space program to the kernel to perform a privileged operation",
      "An interrupt generated by the CPU when it detects a hardware error during execution",
    ],
    correctIndex: 2,
    explanation:
      "A system call is the mechanism by which user-space programs request services from the OS kernel -- such as reading files, allocating memory, or creating processes. It involves a controlled transition from user mode to kernel mode.",
    link: "https://man7.org/linux/man-pages/man2/syscalls.2.html",
  },
  {
    id: 183,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is the difference between SIGTERM and SIGKILL?",
    options: [
      "SIGKILL is sent only by the kernel during emergencies; SIGTERM is sent only by user commands",
      "SIGTERM can be caught and handled; SIGKILL cannot be caught and terminates the process unconditionally",
      "SIGTERM terminates the process immediately and cannot be intercepted by any signal handler",
      "They are identical in effect",
    ],
    correctIndex: 1,
    explanation:
      "SIGTERM (signal 15) asks a process to terminate gracefully -- the process can catch it, clean up resources, and exit. SIGKILL (signal 9) cannot be caught or ignored; the kernel terminates the process immediately. This is why you should try SIGTERM before resorting to SIGKILL.",
    link: "https://man7.org/linux/man-pages/man7/signal.7.html",
  },
  {
    id: 184,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is a zombie process?",
    options: [
      "A process that consumes 100% of CPU time in an infinite loop and cannot be interrupted",
      "A process running in the background with no controlling terminal and no way to receive input",
      "A process that has finished executing but whose exit status has not been collected by its parent",
      "A process that has been killed by SIGKILL and left in a partially cleaned-up state",
    ],
    correctIndex: 2,
    explanation:
      "When a process exits, its entry remains in the process table until the parent calls wait() to retrieve its exit status. During this time it is a 'zombie' -- it uses no CPU or memory but occupies a PID. If the parent never calls wait(), zombies accumulate.",
    link: "https://man7.org/linux/man-pages/man2/waitpid.2.html",
  },
  {
    id: 185,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What does fork() return to the child process?",
    options: [
      "0",
      "-1",
      "The child's own PID",
      "The parent's PID",
    ],
    correctIndex: 0,
    explanation:
      "fork() creates a new child process that is a copy of the parent. It returns the child's PID to the parent and 0 to the child. This lets both processes determine which role they play. On failure, fork() returns -1 to the parent.",
    link: "https://man7.org/linux/man-pages/man2/fork.2.html",
  },
  {
    id: 186,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is the purpose of the exec() family of system calls?",
    options: [
      "To terminate the current process and return an exit code",
      "To duplicate a file descriptor for I/O redirection use",
      "To replace the current process image with a new program",
      "To create a new child process by duplicating the parent",
    ],
    correctIndex: 2,
    explanation:
      "exec() replaces the calling process's code, data, and stack with a new program loaded from disk. The PID remains the same. The common pattern is fork() to create a child, then exec() in the child to run a different program -- this is how shells launch commands.",
    link: "https://man7.org/linux/man-pages/man3/exec.3.html",
  },
  {
    id: 187,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is a pipe in the context of inter-process communication?",
    options: [
      "A shared file on disk that two processes read and write to for data exchange between them",
      "A network socket that connects two processes on different machines over TCP for communication",
      "A unidirectional byte stream connecting the stdout of one process to the stdin of another",
      "A block of shared memory mapped into the address spaces of two separate cooperating processes",
    ],
    correctIndex: 2,
    explanation:
      "A pipe is a kernel-managed buffer that provides a one-way byte stream between two processes. The shell's '|' operator creates a pipe connecting one command's stdout to the next command's stdin. For bidirectional communication, you need two pipes or a socket.",
    link: "https://man7.org/linux/man-pages/man2/pipe.2.html",
  },
  {
    id: 188,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is preemptive multitasking?",
    options: [
      "The OS allows each process to run until it voluntarily yields the CPU by making a system call",
      "The programmer manually switches between tasks using coroutines or cooperative scheduling",
      "Multiple processes run simultaneously on a single core by sharing the execution pipeline",
      "The OS can forcibly interrupt a running process to schedule another, using a timer interrupt",
    ],
    correctIndex: 3,
    explanation:
      "In preemptive multitasking, the OS uses a hardware timer interrupt to periodically regain control of the CPU and decide which process to run next. This prevents any single process from monopolizing the CPU. All modern general-purpose OSes use preemptive scheduling.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-mechanisms.pdf",
  },
  {
    id: 189,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is a context switch?",
    options: [
      "A CPU switching from one cache level to another when the requested data is not found locally",
      "The OS saving the state of the current process/thread and restoring the state of another so it can run",
      "A function call pushing a new frame onto the call stack and transferring control to the callee",
      "Switching from one source file to another during compilation of a multi-file project",
    ],
    correctIndex: 1,
    explanation:
      "A context switch involves saving the CPU registers, program counter, and stack pointer of the current process, then loading those of the next process. It also may involve flushing the TLB and switching page tables. Context switches are necessary for multitasking but have measurable overhead (typically a few microseconds).",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-mechanisms.pdf",
  },
  {
    id: 190,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What does the 'kernel mode' (ring 0) privilege level allow that 'user mode' (ring 3) does not?",
    options: [
      "Direct access to hardware, all memory, and privileged CPU instructions",
      "Allocating memory on the heap using system-level routines like brk() and mmap()",
      "Running C++ code instead of C code, which requires higher privilege for object construction",
      "Using more than one CPU core for parallel execution of threads within a process",
    ],
    correctIndex: 0,
    explanation:
      "Kernel mode (ring 0 on x86) can execute privileged instructions, access any physical memory address, and interact directly with hardware devices. User mode is restricted to prevent buggy or malicious programs from crashing the system. System calls provide the controlled gateway between user mode and kernel mode.",
    link: "https://en.wikipedia.org/wiki/Protection_ring",
  },
  {
    id: 191,
    difficulty: "Easy",
    topic: "Operating Systems",
    question:
      "What is an inode in a Unix filesystem?",
    options: [
      "A pointer to the next file entry in a directory listing, forming a linked list of files",
      "A section of disk reserved for swap space that the kernel uses for paging out memory",
      "A data structure that stores a file's metadata but not its name",
      "The human-readable name of a file as displayed in directory listings and file managers",
    ],
    correctIndex: 2,
    explanation:
      "An inode stores all metadata about a file -- ownership, permissions, timestamps, size, and pointers to the data blocks on disk. The filename is stored in the directory entry, which maps a name to an inode number. This is why hard links work: multiple names can point to the same inode.",
    link: "https://man7.org/linux/man-pages/man7/inode.7.html",
  },
  {
    id: 192,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "After calling fork(), the parent and child processes have identical memory contents. When one of them writes to a variable, what happens?",
    options: [
      "Only the writing process sees the change",
      "The write causes a segmentation fault because all forked memory is permanently marked as read-only",
      "The OS copies the entire address space into new physical memory immediately at the time of the write",
      "Both processes see the write because they share the same physical memory pages after the fork call",
    ],
    correctIndex: 0,
    explanation:
      "Modern OSes implement copy-on-write (COW): after fork(), parent and child share the same physical pages (marked read-only). When either process writes, a page fault occurs and the kernel copies only that page. This makes fork() fast even for large processes, since most pages are never written.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/vm-mechanism.pdf",
  },
  {
    id: 193,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "A multi-level page table (as used on x86-64) splits the virtual address into multiple indices. What is the primary advantage over a single flat page table?",
    options: [
      "It allows pages to be larger than 4 KB by combining multiple contiguous entries together",
      "Space efficiency",
      "It eliminates the need for a TLB by performing all address translation in software directly",
      "Faster lookups -- fewer memory accesses per translation compared to a single-level table approach",
    ],
    correctIndex: 1,
    explanation:
      "A flat page table for a 48-bit address space would require millions of entries even if most memory is unused. A multi-level table is sparse: intermediate levels can point to 'not present,' skipping huge unallocated regions. The tradeoff is more memory accesses per walk (up to 4 on x86-64), but the TLB caches recent translations.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/vm-paging.pdf",
  },
  {
    id: 194,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What are the four necessary conditions for deadlock (Coffman conditions)?",
    options: [
      "Mutual exclusion, hold and wait, no preemption, circular wait",
      "Mutual exclusion, starvation, priority inversion, busy waiting",
      "Race condition, hold and wait, livelock, starvation",
      "Atomicity, consistency, isolation, durability",
    ],
    correctIndex: 0,
    explanation:
      "All four conditions must hold simultaneously for deadlock: (1) mutual exclusion -- resources cannot be shared, (2) hold and wait -- processes hold resources while waiting for others, (3) no preemption -- resources cannot be forcibly taken, (4) circular wait -- a cycle exists in the resource dependency graph. Breaking any one condition prevents deadlock.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/threads-deadlock.pdf",
  },
  {
    id: 195,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "How does a semaphore differ from a mutex?",
    options: [
      "A mutex works across processes via shared memory; a semaphore works only within a single process due to its simpler implementation",
      "A mutex allows only one thread to enter the critical section; a semaphore maintains a count and can allow up to N threads to access a resource concurrently",
      "A semaphore is faster because it uses busy-waiting (spinning) instead of blocking, avoiding the overhead of context switches entirely",
      "They are identical in behavior",
    ],
    correctIndex: 1,
    explanation:
      "A mutex is a binary lock (locked/unlocked). A counting semaphore has an integer value: wait() decrements it (blocking if it would go below zero) and post() increments it. A semaphore initialized to N allows N concurrent accessors -- useful for connection pools or bounded buffers. A binary semaphore (N=1) is similar to a mutex but lacks ownership semantics.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/threads-sema.pdf",
  },
  {
    id: 196,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is priority inversion, and why is it a problem?",
    options: [
      "The OS deliberately inverts the priority of all threads on a periodic timer tick to ensure long-term fairness across all levels",
      "A low-priority thread runs before a high-priority thread due to a bug in the scheduler's priority comparison logic that reverses the ordering",
      "A high-priority thread is blocked waiting for a resource held by a low-priority thread, which is itself preempted by medium-priority threads",
      "Two threads of equal priority deadlock each other because the scheduler cannot determine which one should proceed and blocks both",
    ],
    correctIndex: 2,
    explanation:
      "Priority inversion occurs when a high-priority task H blocks on a lock held by low-priority task L, while medium-priority tasks preempt L -- effectively making H wait for tasks of lower priority. Solutions include priority inheritance (temporarily boosting L's priority to H's level) and priority ceiling protocols. The Mars Pathfinder mission famously encountered this bug.",
    link: "https://en.wikipedia.org/wiki/Priority_inversion",
  },
  {
    id: 197,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is mmap() used for?",
    options: [
      "Mapping a file or device into the process's virtual address space so it can be accessed like memory",
      "Allocating memory that is automatically freed when the calling function returns and its stack frame is destroyed",
      "Creating a new child process that receives a complete copy of the parent's virtual memory and file descriptors",
      "Encrypting a region of process memory for secure storage so that other processes cannot read its contents",
    ],
    correctIndex: 0,
    explanation:
      "mmap() asks the kernel to map a file (or anonymous memory) into the process's address space. Reading/writing the mapped region translates to file I/O handled by the kernel via page faults. This avoids explicit read()/write() calls and lets the kernel use the page cache efficiently. It's also used for loading shared libraries and allocating large memory regions.",
    link: "https://man7.org/linux/man-pages/man2/mmap.2.html",
  },
  {
    id: 198,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is the purpose of fsync() after writing to a file?",
    options: [
      "It acquires an exclusive lock on the file to prevent concurrent access from other processes",
      "It compresses the file data on disk to save storage space without changing the logical contents",
      "It checks the file for data corruption and attempts to repair any damaged blocks automatically",
      "It forces the OS to flush all buffered writes for the file to the physical storage device",
    ],
    correctIndex: 3,
    explanation:
      "When you call write(), the data typically goes into the OS page cache and is written to disk later (writeback). If the system crashes before writeback, data is lost. fsync() blocks until all dirty pages for that file are written to the storage device. Databases use fsync() (or fdatasync()) to ensure durability of committed transactions.",
    link: "https://man7.org/linux/man-pages/man2/fsync.2.html",
  },
  {
    id: 199,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is thrashing?",
    options: [
      "The system spending most of its time swapping pages in and out of memory instead of doing useful work",
      "Multiple threads contending for the same lock, causing high CPU usage from repeated acquire attempts",
      "A disk head moving rapidly back and forth due to fragmented files, reducing sequential read throughput",
      "A CPU running at 100% utilization on useful computation, indicating the processor is fully saturated",
    ],
    correctIndex: 0,
    explanation:
      "Thrashing occurs when the working set of active processes exceeds available physical memory. The OS constantly evicts pages that are needed again almost immediately, causing a storm of page faults. CPU utilization drops dramatically because processes spend nearly all their time waiting for I/O. Solutions include adding more RAM, reducing the number of processes, or improving data locality.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/vm-beyondphys-policy.pdf",
  },
  {
    id: 200,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is the difference between a hard link and a symbolic (soft) link?",
    options: [
      "A hard link is a second directory entry pointing to the same inode; a symbolic link is a separate file that stores a path string",
      "Hard links work across different filesystems and partitions; symbolic links are restricted to the same filesystem only",
      "Symbolic links update their target path automatically when the referenced file is moved; hard links do not track moves",
      "A hard link is a full copy of the file's data on disk; a symbolic link is a lightweight shortcut that takes no extra space",
    ],
    correctIndex: 0,
    explanation:
      "A hard link creates another directory entry referencing the same inode -- the file data is shared and the link count increases. Deleting one hard link does not affect the data until the last link is removed. A symbolic link is a separate inode that stores a pathname; if the target is deleted, the symlink becomes a dangling reference. Hard links cannot cross filesystem boundaries.",
    link: "https://man7.org/linux/man-pages/man2/link.2.html",
  },
  {
    id: 201,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What does dup2(oldfd, newfd) do?",
    options: [
      "Copies the file data from the buffer of oldfd into the buffer of newfd, transferring the actual bytes",
      "Makes newfd refer to the same open file description as oldfd, closing newfd first if it was open",
      "Swaps the file descriptors oldfd and newfd so that each refers to what the other originally pointed to",
      "Creates a new file with the same contents as oldfd, essentially duplicating the file on disk entirely",
    ],
    correctIndex: 1,
    explanation:
      "dup2() atomically closes newfd (if open) and makes it a copy of oldfd -- both now refer to the same underlying file description (same offset, status flags, etc.). This is the mechanism shells use to implement redirection: e.g., dup2(fd, STDOUT_FILENO) makes stdout go to the opened file.",
    link: "https://man7.org/linux/man-pages/man2/dup2.2.html",
  },
  {
    id: 202,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "A program calls printf() but the output does not appear immediately. What is the most likely reason?",
    options: [
      "printf() is a no-op unless you compile with -DPRINTF_ENABLED; without that flag, all output calls are silently discarded by the preprocessor",
      "The terminal driver discards output that is not followed by a newline character, so partial lines are never displayed to the user on screen",
      "stdout is line-buffered by the C library, so output is held in a user-space buffer until a newline, buffer full, or fflush()",
      "The kernel delays all I/O until the process exits to batch writes together for efficiency, so nothing appears until the program terminates",
    ],
    correctIndex: 2,
    explanation:
      "The C standard library buffers stdout output in user space. When connected to a terminal, stdout is typically line-buffered (flushed on newline). When redirected to a file or pipe, it is fully buffered (flushed only when the buffer fills or on fflush/exit). This reduces the number of write() system calls and improves performance.",
    link: "https://man7.org/linux/man-pages/man3/setbuf.3.html",
  },
  {
    id: 203,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is shared memory as an IPC mechanism?",
    options: [
      "A region of physical memory mapped into the address space of multiple processes, allowing direct read/write access without kernel involvement for each operation",
      "A kernel buffer that copies data from one process to another, with the kernel acting as an intermediary to ensure safe communication",
      "Two processes reading and writing the same file on disk, using file locks to synchronize their access and prevent data corruption",
      "A network protocol for transferring data between processes on different machines, using sockets and TCP/IP for reliable delivery",
    ],
    correctIndex: 0,
    explanation:
      "Shared memory (e.g., via shm_open() + mmap(), or shmget()) maps the same physical pages into multiple processes' virtual address spaces. Once set up, processes can read and write the shared region without system calls for each access, making it the fastest IPC mechanism. However, processes must use synchronization (mutexes, semaphores) to avoid data races.",
    link: "https://man7.org/linux/man-pages/man7/shm_overview.7.html",
  },
  {
    id: 204,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is the page cache (buffer cache)?",
    options: [
      "A region of RAM managed by the kernel that caches recently accessed file data, reducing disk I/O",
      "A user-space buffer allocated by malloc() to speed up file I/O operations for the application",
      "A cache of compiled bytecode maintained by the dynamic linker for faster shared library resolution",
      "A hardware cache inside the CPU used for virtual-to-physical address translations via the TLB",
    ],
    correctIndex: 0,
    explanation:
      "The kernel keeps recently read (and written) file data in unused RAM as the page cache. Subsequent reads of the same data are served from RAM instead of hitting disk. This is why 'free' memory on Linux is often low -- the kernel uses available memory for caching. The page cache is the reason the second read of a file is dramatically faster than the first.",
    link: "https://www.kernel.org/doc/html/latest/admin-guide/mm/concepts.html",
  },
  {
    id: 205,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What problem does select()/poll()/epoll() solve?",
    options: [
      "They increase the maximum number of open files a process can have by dynamically expanding the file descriptor table managed by the kernel",
      "They allow a single thread to monitor multiple file descriptors for readiness without blocking on each one individually",
      "They replace the need for TCP/IP in network programming by providing a simpler abstraction layer for inter-process communication on the same host",
      "They encrypt data sent over network sockets to ensure secure communication between processes on the same host or across the network boundary",
    ],
    correctIndex: 1,
    explanation:
      "I/O multiplexing lets a single thread efficiently wait on many file descriptors at once -- essential for building high-performance servers. select() and poll() scan all descriptors each call (O(n)); epoll (Linux) and kqueue (BSD/macOS) maintain a kernel data structure and report only ready descriptors (O(1) per event), enabling tens of thousands of concurrent connections.",
    link: "https://man7.org/linux/man-pages/man7/epoll.7.html",
  },
  {
    id: 206,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is a spinlock, and when is it preferred over a mutex that sleeps?",
    options: [
      "A spinlock busy-waits in a loop checking the lock; it is preferred when the expected wait time is very short (nanoseconds) and context-switch overhead would dominate",
      "A spinlock works only in user space and cannot be used in kernel code; mutexes work only in kernel space and require a system call to acquire",
      "A spinlock can be held by multiple threads simultaneously, making it a form of shared lock rather than an exclusive mutual exclusion primitive",
      "A spinlock is always faster than a mutex because it avoids the overhead of context switching by keeping the thread actively running on the CPU core",
    ],
    correctIndex: 0,
    explanation:
      "A spinlock repeatedly checks (spins on) a flag rather than yielding the CPU. This avoids the overhead of a context switch (~1-10 us) but wastes CPU cycles while waiting. Spinlocks are ideal for very short critical sections (especially in kernel code and on multiprocessors) where the lock holder will release within nanoseconds. For longer waits, a sleeping mutex is more efficient.",
    link: "https://en.wikipedia.org/wiki/Spinlock",
  },
  {
    id: 207,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is demand paging?",
    options: [
      "Paging out rarely used data to a dedicated partition on an SSD, freeing up physical RAM for more actively accessed memory regions",
      "Allocating virtual addresses on demand as the program calls malloc(), expanding the virtual address space incrementally as needed",
      "Loading pages into physical memory only when they are first accessed, triggering a page fault that the OS handles transparently",
      "Loading an entire program into RAM before execution begins, ensuring all code and data pages are resident from the start of the process",
    ],
    correctIndex: 2,
    explanation:
      "With demand paging, the OS does not load a program's pages into RAM until they are actually needed. When the CPU accesses an unmapped page, a page fault occurs; the OS then loads the page from disk (or allocates a zero page) and updates the page table. This saves memory and speeds up process startup, since many pages may never be accessed.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/vm-beyondphys.pdf",
  },
  {
    id: 208,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is the difference between a voluntary and an involuntary context switch?",
    options: [
      "Voluntary switches save less CPU state than involuntary ones because the process has already prepared for the transition by saving its own registers",
      "Voluntary context switches happen in user space code; involuntary ones happen in kernel space code when handling interrupts from hardware devices",
      "There is no real difference",
      "A voluntary switch occurs when a process blocks; an involuntary switch occurs when the OS preempts a running process",
    ],
    correctIndex: 3,
    explanation:
      "A voluntary context switch happens when a process cannot continue -- it calls read(), sleep(), or waits on a lock. An involuntary switch happens when the scheduler preempts a running process (typically because its time quantum expired). High involuntary context switch rates indicate CPU contention; high voluntary rates indicate I/O-heavy workloads.",
    link: "https://man7.org/linux/man-pages/man1/pidstat.1.html",
  },
  {
    id: 209,
    difficulty: "Medium",
    topic: "Operating Systems",
    question:
      "What is an orphan process, and what happens to it?",
    options: [
      "It is moved to a special orphan scheduling queue with the lowest priority, receiving CPU time only when no other process needs it",
      "Its parent has exited, so it is re-parented to init (PID 1), which will call wait() on it when it eventually exits",
      "It becomes a zombie process entry in the process table and can never be cleaned up by any mechanism available",
      "It is terminated immediately by the kernel as soon as its parent process exits, freeing all its resources at that point",
    ],
    correctIndex: 1,
    explanation:
      "When a parent process exits before its children, the orphaned children are adopted by the init process (PID 1) on Unix systems (or a subreaper). Init periodically calls wait() to collect the exit status of its adopted children, preventing them from becoming permanent zombies.",
    link: "https://man7.org/linux/man-pages/man2/waitpid.2.html",
  },
  {
    id: 210,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "On x86-64 Linux, a four-level page table is used. A virtual address is split into fields for PML4, PDPT, PD, PT, and offset. How many memory accesses does a TLB miss require to resolve a virtual address (not counting the final data access)?",
    options: [
      "4",
      "It varies depending on the page size",
      "2",
      "1",
    ],
    correctIndex: 0,
    explanation:
      "A TLB miss on x86-64 triggers a page table walk through four levels: PML4 → PDPT → PD → PT, each requiring one memory access to read the entry at that level. That's 4 memory accesses before the physical address is obtained. Huge pages (2 MB or 1 GB) reduce this by stopping the walk earlier, which is one reason they improve performance for large allocations.",
    link: "https://www.kernel.org/doc/html/latest/x86/x86_64/mm.html",
  },
  {
    id: 211,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What are huge pages (large pages), and why do they improve performance for memory-intensive applications?",
    options: [
      "They bypass the kernel's memory allocator and map physical memory directly into user space without any virtual translation",
      "They compress memory contents at the hardware level so that more data fits in physical RAM without additional modules",
      "They allow the OS to allocate memory faster by skipping the page table entirely and writing directly to physical address space",
      "They reduce TLB misses by mapping larger contiguous regions with a single TLB entry, and reduce page table depth",
    ],
    correctIndex: 3,
    explanation:
      "A standard page is 4 KB. A huge page (2 MB or 1 GB on x86-64) covers a much larger region with a single TLB entry, dramatically reducing TLB misses for large working sets. The page table walk is also shorter (3 or 2 levels instead of 4). Databases and virtual machines commonly use huge pages. Linux offers both transparent huge pages (automatic) and hugetlbfs (explicit).",
    link: "https://www.kernel.org/doc/html/latest/admin-guide/mm/hugetlbpage.html",
  },
  {
    id: 212,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "A function registered with signal() or sigaction() runs when a signal is delivered. Why is calling printf() or malloc() from a signal handler considered unsafe?",
    options: [
      "Signal handlers cannot access global variables because the kernel remaps the process's address space to a restricted view during signal delivery, hiding most of the process memory",
      "printf() and malloc() are not async-signal-safe",
      "Signal handlers run in kernel mode where user-space functions like printf() and malloc() are unavailable due to the different privilege level, stack configuration, and address space layout",
      "The kernel disables all standard library functions during signal delivery by temporarily unmapping the libc text segment from the process's address space, making those functions inaccessible",
    ],
    correctIndex: 1,
    explanation:
      "If a signal arrives while the thread is inside malloc() (which holds an internal lock), and the handler also calls malloc(), it will attempt to acquire the same lock -- causing a deadlock (or heap corruption). Only a small set of functions are guaranteed async-signal-safe (e.g., write(), _exit()). POSIX explicitly lists these safe functions in the signal-safety man page.",
    link: "https://man7.org/linux/man-pages/man7/signal-safety.7.html",
  },
  {
    id: 213,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is the OOM (Out-Of-Memory) killer in Linux?",
    options: [
      "A compiler warning that fires when a program statically allocates too much stack memory, detected during code analysis",
      "A kernel mechanism that selects and kills processes when the system runs critically low on memory, to prevent a complete system hang",
      "A user-space daemon that monitors memory usage and sends alerts to the system administrator when thresholds are exceeded",
      "A systemd service that continuously monitors processes and restarts any that exceed their configured memory limit",
    ],
    correctIndex: 1,
    explanation:
      "When the kernel cannot free enough memory through normal reclamation (cache eviction, swapping), the OOM killer selects a process to terminate based on a heuristic score (oom_score). This is a last resort to keep the system running. The score favors killing memory-hungry, low-priority processes. You can adjust a process's oom_score_adj to influence this decision.",
    link: "https://www.kernel.org/doc/html/latest/admin-guide/mm/concepts.html",
  },
  {
    id: 214,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is a futex, and why is it central to modern synchronization primitives on Linux?",
    options: [
      "A kernel data structure that replaces all spinlocks for in-kernel synchronization, providing sleeping behavior instead of busy-waiting",
      "A special CPU instruction that atomically locks an entire cache line, preventing any other core from reading or writing that memory region",
      "A 'fast userspace mutex'",
      "A file-system-based lock that prevents two processes from writing the same file, using advisory locking via special lock files on disk",
    ],
    correctIndex: 2,
    explanation:
      "A futex (fast userspace mutex) is an integer in shared memory. In the uncontended case, threads use atomic CPU instructions (like CAS) to acquire the lock entirely in user space -- no system call needed. Only when a thread must block (because another thread holds the lock) does it call futex(FUTEX_WAIT) to sleep in the kernel. This hybrid approach makes pthread_mutex, std::mutex, and Go's sync.Mutex fast in the common case.",
    link: "https://man7.org/linux/man-pages/man2/futex.2.html",
  },
  {
    id: 215,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "Linux uses an overcommit strategy for memory allocation. What does this mean, and what is a consequence?",
    options: [
      "Processes must request memory from a central kernel broker that tracks all allocations system-wide and ensures fair distribution among all running processes on the system",
      "The kernel allocates physical memory immediately when malloc() is called, reserving real pages upfront and guaranteeing they are available for use by the process at all times",
      "The kernel transparently compresses memory pages in the background to allow more total allocations than the amount of physical RAM installed in the machine at that time",
      "malloc() can succeed even when there is not enough physical memory to back the allocation; the kernel provides physical pages only on access and may invoke the OOM killer if memory runs out later",
    ],
    correctIndex: 3,
    explanation:
      "With overcommit, the kernel grants virtual address space without reserving physical pages. Physical memory is allocated on demand (demand paging). This works well because most programs allocate far more than they use. However, if all processes simultaneously touch their allocations, the kernel may run out of physical memory and invoke the OOM killer. This is why malloc() almost never returns NULL on Linux.",
    link: "https://www.kernel.org/doc/html/latest/admin-guide/sysctl/vm.html",
  },
  {
    id: 216,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is the difference between blocking I/O, non-blocking I/O, and asynchronous I/O?",
    options: [
      "They are three names for the same underlying mechanism",
      "Non-blocking I/O requires spawning multiple threads to poll each descriptor for readiness; blocking I/O and async I/O both operate efficiently on a single thread without additional concurrency",
      "Blocking I/O suspends the calling thread until complete; non-blocking I/O returns immediately with EAGAIN if not ready; async I/O initiates the operation and the kernel notifies the program when it completes",
      "Blocking I/O is designed for regular files on disk; non-blocking I/O is exclusively for network sockets; async I/O is reserved for pipes, FIFOs, and other special inter-process communication channels",
    ],
    correctIndex: 2,
    explanation:
      "Blocking I/O (the default) puts the thread to sleep until data is available. Non-blocking I/O (O_NONBLOCK) returns EAGAIN/EWOULDBLOCK if the operation would block, requiring the program to retry -- typically combined with epoll/select. Async I/O (e.g., io_uring on Linux) submits operations to the kernel and receives completions later, allowing the thread to do other work without polling.",
    link: "https://man7.org/linux/man-pages/man7/aio.7.html",
  },
  {
    id: 217,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "A program forks 1000 worker processes, each with a 100 MB address space. Does this require 100 GB of physical RAM?",
    options: [
      "No -- copy-on-write means forked processes share the parent's physical pages until they write; shared libraries and read-only pages are never duplicated",
      "No -- the kernel transparently compresses each process's memory pages in the background to fit more processes in physical RAM",
      "Yes -- each forked process receives its own independent copy of all physical memory pages at the moment fork() is called",
      "No -- only one process runs at a time on a given core, so they share the same physical memory through CPU time-slicing",
    ],
    correctIndex: 0,
    explanation:
      "Thanks to COW and shared mappings, forked processes share physical pages for code (text segment), read-only data, and shared libraries. Only pages that are actually modified get private copies. A parent with 100 MB and 1000 children that each modify only 1 MB would use roughly 100 MB (shared) + 1000 × 1 MB (private) ≈ 1.1 GB, not 100 GB.",
    link: "https://man7.org/linux/man-pages/man2/fork.2.html",
  },
  {
    id: 218,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is the working set of a process, and how does it relate to performance?",
    options: [
      "The total amount of virtual memory a process has allocated via malloc and mmap since it started running",
      "The set of pages actively being used during a given time window; if the working set exceeds available physical memory, the process thrashes",
      "The set of file descriptors currently open by the process, including sockets, pipes, and regular files",
      "The number of CPU instructions the process has executed in the last second, as measured by hardware performance counters",
    ],
    correctIndex: 1,
    explanation:
      "The working set is the subset of a process's pages that it accesses during a recent time interval. If the OS can keep the working set in RAM, page faults are rare and performance is good. If physical memory is too small for all active working sets, the OS evicts pages that are immediately needed again (thrashing). Understanding your working set size helps you optimize data structures for locality.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/vm-beyondphys-policy.pdf",
  },
  {
    id: 219,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is a condition variable, and why must it always be used with a mutex?",
    options: [
      "A condition variable is a boolean flag that threads poll in a busy loop; it does not need a mutex because the flag itself provides sufficient synchronization between threads",
      "A condition variable allows threads to sleep until a condition is true; the mutex protects the shared state that defines the condition, preventing the race between checking the condition and going to sleep",
      "A condition variable signals the kernel to deliver a hardware interrupt to waiting threads; the mutex prevents nested interrupts from corrupting shared state during the signal delivery",
      "A condition variable is a special type of counting semaphore that tracks how many threads are waiting; the mutex is technically optional and used only for performance optimization",
    ],
    correctIndex: 1,
    explanation:
      "Without a mutex, there is a race condition: Thread A checks the condition (it's false), then Thread B changes the condition and signals, then Thread A sleeps -- missing the signal forever. The mutex ensures the condition check and the wait are atomic: the wait atomically releases the mutex and sleeps, and re-acquires it when woken. Spurious wakeups mean you must always re-check the condition in a loop.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/threads-cv.pdf",
  },
  {
    id: 220,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is DMA (Direct Memory Access), and why is it important for I/O performance?",
    options: [
      "DMA is a technique for mapping device memory into user-space virtual address space so applications can communicate with hardware without system calls",
      "DMA is a security feature built into the IOMMU that prevents devices from writing to kernel memory regions they are not authorized to access",
      "DMA allows I/O devices to transfer data directly to/from RAM without involving the CPU for each byte, freeing the CPU to do other work during the transfer",
      "DMA allows the CPU to access device registers directly without going through the system bus, reducing per-access latency for device communication",
    ],
    correctIndex: 2,
    explanation:
      "Without DMA, the CPU would have to execute a load/store instruction for every byte transferred between a device and memory (programmed I/O), consuming 100% of a core. DMA controllers let devices read/write RAM independently -- the CPU initiates the transfer and receives an interrupt when it's complete. This is why modern disk and network I/O barely loads the CPU even at high throughput.",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/file-devices.pdf",
  },
  {
    id: 221,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "On Linux, what is the difference between a process's virtual memory size (VIRT/VSZ) and its resident set size (RSS)?",
    options: [
      "They represent the same measurement reported in different units",
      "VIRT is the total memory the process has paged out to disk swap; RSS is the portion that is actively loaded in physical RAM at the moment",
      "VIRT is the total virtual address space mapped; RSS is the portion actually present in physical RAM right now",
      "VIRT includes shared library mappings in its count; RSS excludes them to show only private memory usage belonging to the process alone",
    ],
    correctIndex: 2,
    explanation:
      "VIRT (virtual size) includes everything mapped into the process's address space: heap, stack, memory-mapped files, shared libraries -- even pages not yet backed by physical memory. RSS (resident set size) counts only the pages currently in RAM. A process can have a VIRT of several GB but an RSS of a few hundred MB. Neither perfectly reflects 'actual' memory usage due to shared pages counted by both.",
    link: "https://man7.org/linux/man-pages/man1/top.1.html",
  },
  {
    id: 222,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "Why is livelock considered different from deadlock, and in what situations does it arise?",
    options: [
      "Livelock is just another name for deadlock that occurs when more than two threads are involved in a circular wait dependency on shared resources within the system",
      "In livelock, threads are not blocked",
      "Livelock is caused by transient hardware faults like bit flips in memory that corrupt lock state; deadlock is caused by logical bugs in lock ordering within the software itself",
      "Livelock occurs only in distributed systems across network boundaries where message delays cause retries; deadlock occurs only on single-machine systems with shared memory locks",
    ],
    correctIndex: 1,
    explanation:
      "In deadlock, threads are blocked and do nothing. In livelock, threads are active -- they keep retrying or yielding, but their actions counteract each other so no progress is made. A classic analogy: two people in a hallway keep stepping aside in the same direction. Livelock can arise from overly aggressive deadlock-avoidance schemes (e.g., two threads repeatedly acquiring and releasing locks in response to contention).",
    link: "https://en.wikipedia.org/wiki/Deadlock#Livelock",
  },
  {
    id: 223,
    difficulty: "Hard",
    topic: "Operating Systems",
    question:
      "What is starvation in the context of process scheduling or resource allocation?",
    options: [
      "A process being killed by the OOM killer due to low memory, which frees resources for the remaining processes on the system",
      "A deadlock involving more than two resources in a circular dependency chain, sometimes called a multi-resource deadlock scenario",
      "A process or thread being perpetually denied access to a resource it needs because other higher-priority or more favored processes always get it first",
      "A process consuming all available CPU time and starving the OS kernel of cycles needed to service system calls from other processes",
    ],
    correctIndex: 2,
    explanation:
      "Starvation occurs when a thread or process is indefinitely delayed because resources are always allocated to others. For example, a strict priority scheduler may starve low-priority processes if high-priority processes always run. Solutions include aging (gradually increasing a waiting process's priority), fair scheduling algorithms (like CFS on Linux), and fair locks (FIFO ordering).",
    link: "https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-mlfq.pdf",
  },
];
