import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: 382,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What is a vtable (virtual table)?",
    options: [
      "A table of all variables defined in a class, storing their memory offsets, types, and sizes for runtime access and reflection purposes",
      "A per-class array of function pointers",
      "A memory allocation table managed by new/delete that tracks heap-allocated objects per class, including allocation size and alignment data",
      "A hash table that maps class names to objects at runtime for dynamic method resolution, using string-based lookup of function signatures",
    ],
    correctIndex: 1,
    explanation:
      "The compiler generates one vtable per polymorphic class. It is an array of function pointers, where each slot corresponds to a virtual function. When a class overrides a virtual function, its vtable slot points to the new implementation instead of the base version.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 383,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "Where is the vptr (virtual table pointer) stored?",
    code: `class Animal {\npublic:\n    virtual void speak() {}\n};\n\nsizeof(Animal);  // larger than expected?`,
    options: [
      "In the vtable itself as an embedded self-referencing pointer",
      "As a hidden pointer inside each object, typically at the beginning",
      "In the stack frame of the calling function, stored alongside local variables",
      "In a separate global table, not in the object",
    ],
    correctIndex: 1,
    explanation:
      "Each polymorphic object carries a hidden vptr member (usually the first field). It points to the class's vtable. This is why sizeof(Animal) is at least the size of a pointer (8 bytes on 64-bit) even with no data members.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 384,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What internal data structure does std::vector use?",
    options: [
      "A linked list of nodes, each containing one element and a pointer to the next node in sequence",
      "A contiguous dynamically-allocated array, typically tracked by three pointers: begin, end (size), and capacity",
      "A balanced binary search tree that maintains insertion order through in-order traversal of the nodes",
      "A hash table with open addressing, where elements are stored in contiguous slots determined by hash values",
    ],
    correctIndex: 1,
    explanation:
      "std::vector is a dynamic array. Most implementations store three pointers: one to the start of the array, one past the last element (giving size), and one past the allocated capacity. Elements are stored contiguously in memory.",
    link: "https://en.cppreference.com/w/cpp/container/vector.html",
  },
  {
    id: 385,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What is the Small String Optimization (SSO)?",
    code: `std::string s = "hi";  // Where is \"hi\" stored?`,
    options: [
      "Short strings are stored directly inside the std::string object itself rather than on the heap, avoiding a dynamic allocation",
      "Short strings are stored in a global string pool that deduplicates identical strings across the entire program",
      "The compiler replaces short strings with string literals at compile time, embedding them directly in the binary's read-only data section",
      "All strings are always heap-allocated regardless of length, using a dynamically managed character buffer",
    ],
    correctIndex: 0,
    explanation:
      "Most std::string implementations reserve a small internal buffer (typically 15-22 bytes). If the string fits, no heap allocation occurs -- the characters live directly in the string object. This makes short string operations much faster.",
    link: "https://en.cppreference.com/w/cpp/string/basic_string.html",
  },
  {
    id: 386,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What is the control block in std::shared_ptr?",
    options: [
      "A heap-allocated block that stores the strong reference count, weak reference count, deleter, and the managed object itself",
      "The pointed-to object itself, which contains embedded reference count fields added by the compiler automatically at compile time for all shared_ptr-managed types",
      "A mutex that protects the shared pointer from data races by synchronizing all reference count operations, using a kernel lock for every increment and decrement",
      "A stack-allocated counter that tracks copies of the shared_ptr and is destroyed when the last copy goes out of scope, without any heap allocation overhead involved",
    ],
    correctIndex: 0,
    explanation:
      "When you create a shared_ptr, a control block is allocated (or embedded with the object via make_shared). It holds the strong count, weak count, and the deleter. Multiple shared_ptrs to the same object share one control block.",
    link: "https://en.cppreference.com/w/cpp/memory/shared_ptr.html",
  },
  {
    id: 387,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What data structure does std::map use internally?",
    options: [
      "A hash table that maps keys to values using a hash function for O(1) average-case lookup with collision chaining",
      "A red-black tree, giving O(log n) lookup, insertion, and deletion",
      "A skip list with multiple linked layers, offering probabilistic O(log n) search via express lanes over the base list",
      "A sorted array with binary search for O(log n) reads, but requiring O(n) shifts for each insertion or deletion",
    ],
    correctIndex: 1,
    explanation:
      "std::map is required to keep elements sorted by key and provide O(log n) operations. All major implementations use a red-black tree -- a self-balancing BST that guarantees the tree height is at most 2·log₂(n).",
    link: "https://en.cppreference.com/w/cpp/container/map.html",
  },
  {
    id: 388,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What data structure does std::unordered_map use internally?",
    options: [
      "A trie (prefix tree) with one node per key character, giving lookup time proportional to key length",
      "A hash table with separate chaining, giving average O(1) lookup",
      "A red-black tree that keeps keys sorted for O(log n) lookup, insertion, and deletion",
      "A sorted array using binary search for O(log n) reads, but O(n) shifts on each insertion",
    ],
    correctIndex: 1,
    explanation:
      "std::unordered_map uses a hash table. The standard requires it to use separate chaining (each bucket is a linked list of elements that hash to the same slot). This is why it provides bucket_count(), load_factor(), and rehash() APIs.",
    link: "https://en.cppreference.com/w/cpp/container/unordered_map.html",
  },
  {
    id: 389,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "How is a lambda implemented by the compiler?",
    code: `auto fn = [x](int y) { return x + y; };`,
    options: [
      "As a compiler-generated class with captured variables as members and operator() as the body",
      "As a std::function object that wraps the lambda body and captures using type erasure internally",
      "As an inline assembly block that the compiler generates to avoid the overhead of a normal function call",
      "As a regular function pointer that is passed the captured variables through a hidden parameter",
    ],
    correctIndex: 0,
    explanation:
      "The compiler transforms the lambda into an anonymous class. Captured variables become data members (x is a member). The lambda body becomes operator(). The variable fn is an instance of this closure class. This is why each lambda has a unique type.",
    link: "https://en.cppreference.com/w/cpp/language/lambda.html",
  },
  {
    id: 390,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "Why does sizeof on an empty class return 1, not 0?",
    code: `class Empty {};\nstatic_assert(sizeof(Empty) == 1);`,
    options: [
      "Because the class contains a hidden default constructor the compiler inserts, and that body needs at least one byte",
      "So that every object has a unique address",
      "Because the vtable pointer takes 1 byte inside the object, even when the class has no virtual functions at all",
      "Because the compiler always adds padding to a minimum of 1 byte for alignment, regardless of the class contents",
    ],
    correctIndex: 1,
    explanation:
      "The C++ standard requires that every complete object has a unique address. If empty objects had size 0, an array of them would give every element the same address, breaking identity comparisons. The 1-byte minimum guarantees address uniqueness.",
    link: "https://en.cppreference.com/w/cpp/language/ebo.html",
  },
  {
    id: 391,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What is struct padding and why does it exist?",
    code: `struct S {\n    char a;   // 1 byte\n    int b;    // 4 bytes\n};\n// sizeof(S) is typically 8, not 5. Why?`,
    options: [
      "The extra bytes store metadata about the struct, such as the member count and their types for runtime reflection, allowing dynamic introspection of the struct layout at runtime",
      "Padding is a bug in the compiler",
      "The compiler adds extra bytes as a security feature to prevent buffer overflow between adjacent struct members, inserting guard bytes that are checked at runtime to detect corruption",
      "The compiler inserts padding bytes so that each member is aligned to its natural alignment boundary, which is required for efficient (or correct) CPU memory access",
    ],
    correctIndex: 3,
    explanation:
      "CPUs access memory most efficiently when data is aligned to its size (e.g., a 4-byte int at a 4-byte boundary). The compiler inserts padding after char a (3 bytes) so that int b starts at offset 4. This is why sizeof(S) is 8, not 5.",
    link: "https://en.cppreference.com/w/cpp/language/object.html",
  },
  {
    id: 392,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "What does a stack frame contain for a function call?",
    options: [
      "Only the function pointer and its arguments, stored contiguously so the callee can locate them by offset",
      "Only the return value of the function, which is placed in a reserved slot at the top of the stack frame",
      "A copy of the entire program's memory, snapshotted so the function can be re-entered or rolled back if needed",
      "Local variables, function parameters, the return address, saved registers, and space for temporaries",
    ],
    correctIndex: 3,
    explanation:
      "Each function call creates a stack frame (activation record) on the call stack. It holds the return address (where to resume after the function), saved register values, function parameters, and local variables. It is deallocated when the function returns.",
    link: "https://www.learncpp.com/cpp-tutorial/the-stack-and-the-heap/",
  },
  {
    id: 393,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "How does std::array differ from a C-style array internally?",
    code: `std::array<int, 5> arr = {1, 2, 3, 4, 5};\nint carr[5] = {1, 2, 3, 4, 5};`,
    options: [
      "Internally identical",
      "std::array stores elements on the heap with a pointer, like vector, but has a fixed capacity set at compile time that cannot be changed after construction of the container",
      "std::array uses a linked list internally so that elements can be inserted and removed efficiently at any position, unlike a C array which requires shifting elements on insertion",
      "std::array is heap-allocated while C arrays are stack-allocated, so std::array has dynamic allocation overhead and pointer indirection on every element access compared to a raw array",
    ],
    correctIndex: 0,
    explanation:
      "std::array<T,N> is essentially struct { T data[N]; }. It has zero overhead over a C array -- same memory layout, same performance. But it provides .size(), .at() (bounds-checked), iterators, and doesn't decay to a pointer when passed to functions.",
    link: "https://en.cppreference.com/w/cpp/container/array.html",
  },
  {
    id: 394,
    difficulty: "Easy",
    topic: "Under the Hood",
    question: "How does std::unique_ptr compare to a raw pointer in terms of size and overhead?",
    options: [
      "unique_ptr with the default deleter is typically the same size as a raw pointer (one pointer) and has zero runtime overhead",
      "unique_ptr uses an extra heap allocation for bookkeeping, storing a control block similar to shared_ptr that tracks ownership state and the custom deleter function pointer",
      "unique_ptr is twice the size of a raw pointer due to the reference counter it maintains alongside the stored pointer, adding overhead for ownership tracking on every copy",
      "unique_ptr is always 16 bytes due to the type erasure mechanism it uses to store the deleter at runtime, requiring an additional pointer-sized field beyond the managed object pointer",
    ],
    correctIndex: 0,
    explanation:
      "With the default deleter, unique_ptr stores just one pointer -- the same as a raw pointer. All ownership logic is enforced at compile time (deleted copy constructor, move-only semantics). There is no reference count and no extra allocation. It's a zero-cost abstraction.",
    link: "https://en.cppreference.com/w/cpp/memory/unique_ptr.html",
  },
  {
    id: 395,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "Walk through a virtual function call: what steps does the CPU execute?",
    code: `Base* p = new Derived();\np->speak();  // virtual call`,
    options: [
      "1) Load the vptr from the object p points to, 2) Index into the vtable at the slot for speak(), 3) Call the function pointer found there",
      "The compiler directly calls Derived::speak() since it knows the type from the new expression at compile time, so no vtable indirection is needed and the call is resolved statically",
      "The runtime searches a hash map of function names, matching the method signature string against registered implementations in a global dispatch table maintained by the C++ runtime",
      "The compiler generates a switch statement over all possible derived types and dispatches to the correct override based on a hidden type ID integer stored in each polymorphic object",
    ],
    correctIndex: 0,
    explanation:
      "A virtual call compiles to roughly: load vptr from *p (first indirection), read the function pointer at vtable[speak_index] (second indirection), then call that pointer. This is why virtual calls are slightly slower than direct calls -- two memory loads instead of a direct jump.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 396,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "What happens to the vptr during object construction?",
    code: `class Base {\npublic:\n    Base() { /* vptr points to Base's vtable here */ }\n    virtual void f() {}\n};\n\nclass Derived : public Base {\npublic:\n    Derived() { /* vptr now points to Derived's vtable */ }\n    void f() override {}\n};`,
    options: [
      "The vptr is updated at each construction stage: set to Base's vtable during Base(), then updated to Derived's vtable when Derived's constructor begins",
      "The vptr is only set after all constructors finish running completely, ensuring that virtual dispatch is never used during construction of any part of the object hierarchy",
      "The vptr is set randomly and resolved at the first virtual call through a lazy initialization mechanism, with the runtime caching the result for subsequent dispatch operations",
      "The vptr is set once during the most-derived class constructor and never changes after that point, meaning virtual calls in the base constructor dispatch to the final overrider",
    ],
    correctIndex: 0,
    explanation:
      "During construction, the vptr is updated as each class's constructor executes. In Base::Base(), the vptr points to Base's vtable (so virtual calls resolve to Base's versions). When Derived's constructor starts, the vptr is overwritten to point to Derived's vtable. This is why virtual calls in constructors don't dispatch to derived classes.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 397,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "What does the memory layout of an object with multiple inheritance look like?",
    code: `class A { int a; virtual void fa(); };\nclass B { int b; virtual void fb(); };\nclass C : public A, public B { int c; };`,
    options: [
      "One vptr shared between A and B, followed by a, b, c -- the compiler merges both vtables into a single combined table to reduce indirection",
      "Two sub-objects laid out sequentially: [A's vptr, a] [B's vptr, b] [c] -- the object contains two vptrs, one for each polymorphic base",
      "Three separate heap allocations, one per base -- each sub-object is allocated independently and connected through internal pointers in the derived class",
      "One contiguous block: [vptr, a, b, c] -- the compiler merges all base data into a single region with one shared vptr for dispatch to both A and B",
    ],
    correctIndex: 1,
    explanation:
      "With multiple inheritance, each polymorphic base contributes its own vptr. The object layout is: [A sub-object: vptr_A, a] [B sub-object: vptr_B, b] [C's own data: c]. When you cast a C* to B*, the pointer is adjusted to point to the B sub-object.",
    link: "https://en.cppreference.com/w/cpp/language/derived_class.html",
  },
  {
    id: 398,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "Why does casting a pointer from a derived class to a second base class sometimes change the pointer value?",
    code: `class A { virtual void f(); int a; };\nclass B { virtual void g(); int b; };\nclass C : public A, public B {};\n\nC c;\nA* pa = &c;  // points to start of c\nB* pb = &c;  // different address!`,
    options: [
      "This is a compiler bug that violates the standard",
      "The compiler adjusts the pointer by an offset because B's sub-object is not at the start of C",
      "The pointer changes because B is heap-allocated separately from the rest of the object, with a dedicated allocation for each base sub-object",
      "It doesn't change",
    ],
    correctIndex: 1,
    explanation:
      "In C's layout, A sits at offset 0 and B sits at a later offset. pa points to the start of c (the A sub-object), but pb must point to the B sub-object, which is further into the object. The compiler adds a static offset during the cast. This is called pointer adjustment.",
    link: "https://en.cppreference.com/w/cpp/language/static_cast.html",
  },
  {
    id: 399,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does std::function implement type erasure internally?",
    options: [
      "It uses a virtual base class pointer to store any callable through an internal polymorphic wrapper that knows how to invoke the stored callable",
      "It uses a C function pointer for all callables, converting lambdas and functors to plain function pointers",
      "It uses a union of all possible callable types, sized at compile time based on the function signature",
      "It uses template specialization for each callable type at compile time, generating separate code paths with no runtime overhead",
    ],
    correctIndex: 0,
    explanation:
      "std::function uses type erasure: it stores a pointer to an internal abstract base class with a virtual operator(). When you assign a lambda, function pointer, or functor, it creates a concrete derived class that wraps your callable. This is why std::function has overhead -- virtual dispatch + possible heap allocation.",
    link: "https://en.cppreference.com/w/cpp/utility/functional/function.html",
  },
  {
    id: 400,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does std::variant store its data internally?",
    code: `std::variant<int, double, std::string> v = 42;`,
    options: [
      "It uses a std::any internally to perform type erasure, wrapping the stored value in a polymorphic container that handles construction and destruction",
      "It heap-allocates the active type using new and stores a pointer to the allocation, with automatic cleanup when the variant is reassigned or goes out of scope",
      "It stores all three types simultaneously in separate memory regions, maintaining valid objects for every alternative even when only one is logically active at a time",
      "A union-like storage plus a small index/tag indicating which type is currently active",
    ],
    correctIndex: 3,
    explanation:
      "std::variant uses an aligned storage buffer large enough for the largest type, plus a discriminator (tag/index). The tag records which type is active. Accessing the wrong type throws std::bad_variant_access. No heap allocation, no virtual dispatch -- it's a type-safe tagged union.",
    link: "https://en.cppreference.com/w/cpp/utility/variant.html",
  },
  {
    id: 401,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does std::optional avoid heap allocation?",
    code: `std::optional<Widget> opt = Widget(42);`,
    options: [
      "It stores the object in an aligned internal buffer plus a bool flag indicating whether a value is present",
      "It uses placement new into a global memory pool maintained by the runtime, allocating from a pre-reserved arena that avoids per-object heap calls but still uses indirection for access",
      "It heap-allocates the Widget using new and stores a pointer to the allocation, then calls delete on the pointer when the optional is reset or destroyed to free the memory",
      "It uses std::shared_ptr internally to manage the optional value, reference-counting the contained object so multiple optional instances can share the same underlying data efficiently",
    ],
    correctIndex: 0,
    explanation:
      "std::optional<T> is roughly equivalent to struct { alignas(T) char storage[sizeof(T)]; bool has_value; }. When engaged, the object lives directly in the buffer (constructed via placement new). sizeof(optional<T>) is typically sizeof(T) + alignment padding + 1 byte for the flag.",
    link: "https://en.cppreference.com/w/cpp/utility/optional.html",
  },
  {
    id: 402,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does std::deque work internally? It provides O(1) push_front AND push_back.",
    options: [
      "An array of pointers to fixed-size chunks (blocks) of contiguous memory, allowing growth at both ends without moving existing elements",
      "A doubly-linked list where each node holds one element, with prev and next pointers enabling O(1) insertion at both ends but poor cache locality",
      "Two vectors placed back-to-back, one growing leftward for push_front and the other rightward for push_back, reallocating independently",
      "A single contiguous array like vector, with elements stored sequentially in one heap allocation that is reallocated whenever capacity is exceeded",
    ],
    correctIndex: 0,
    explanation:
      "std::deque uses a 'map' (array of pointers) where each pointer points to a fixed-size chunk of elements. New chunks are added at either end. This gives O(1) amortized push_front and push_back. Elements within a chunk are contiguous, but chunks are not contiguous with each other.",
    link: "https://en.cppreference.com/w/cpp/container/deque.html",
  },
  {
    id: 403,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "What does sizeof return for a class with one virtual function and one int member on a 64-bit system?",
    code: `class Widget {\n    int x;  // 4 bytes\npublic:\n    virtual void f();\n};`,
    options: [
      "8 -- the int plus 4 bytes of padding for alignment; the vptr is stored separately",
      "16 -- the hidden vptr (8 bytes) + int (4 bytes) + 4 bytes padding for alignment",
      "4 -- only the int counts; virtual functions live in the vtable, not in the object",
      "12 -- the vptr (8 bytes) + int (4 bytes) with no padding needed for this layout",
    ],
    correctIndex: 1,
    explanation:
      "The vptr is a hidden pointer (8 bytes on 64-bit). The int is 4 bytes. Total data is 12 bytes, but the struct must be aligned to 8 (the alignment of the pointer), so 4 bytes of padding are added, giving sizeof = 16.",
    link: "https://en.cppreference.com/w/cpp/language/object.html",
  },
  {
    id: 404,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does dynamic_cast determine if a cast is valid at runtime?",
    options: [
      "It uses a hash table of all created objects, keyed by their memory address, to look up the actual dynamic type at runtime and verify it against the target type in the cast expression",
      "It reinterprets the bits and checks if the first bytes match the target class's expected vtable signature pattern, using a magic number embedded by the compiler at the start of every vtable",
      "It compares pointer values against a table of known valid addresses for each class in the hierarchy, checking whether the address falls within a registered object range for the target type",
      "It traverses RTTI data",
    ],
    correctIndex: 3,
    explanation:
      "dynamic_cast uses RTTI stored alongside the vtable. Each polymorphic class has type_info data that encodes the class hierarchy. The runtime traverses this hierarchy to determine if the cast is valid. This is why dynamic_cast only works on polymorphic types (those with at least one virtual function).",
    link: "https://en.cppreference.com/w/cpp/language/dynamic_cast.html",
  },
  {
    id: 405,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does std::shared_ptr handle thread-safe reference counting without a mutex on the whole object?",
    options: [
      "The reference counts in the control block are updated using atomic operations, which are lock-free on modern CPUs",
      "Each thread has its own copy of the count, merged on destruction using a thread-local accumulation strategy that reconciles all partial counts when the last thread finishes",
      "It doesn't handle thread safety at all",
      "It uses a global lock for all shared_ptr instances across the process, serializing all reference count modifications across threads using a single kernel-level mutex",
    ],
    correctIndex: 0,
    explanation:
      "The control block's strong and weak counts are std::atomic integers. Incrementing/decrementing uses hardware atomic instructions (like lock xadd on x86). This makes reference count manipulation thread-safe without a full mutex. Note: the pointed-to object itself is NOT protected -- only the reference count is.",
    link: "https://en.cppreference.com/w/cpp/memory/shared_ptr.html",
  },
  {
    id: 406,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "Why does make_shared typically perform better than separately constructing shared_ptr?",
    code: `// Option A: two allocations\nstd::shared_ptr<Widget> p1(new Widget());\n\n// Option B: one allocation\nauto p2 = std::make_shared<Widget>();`,
    options: [
      "make_shared uses a memory pool for all shared objects, amortizing allocation cost across multiple shared_ptr instances",
      "make_shared combines the control block and the object into a single heap allocation, reducing allocation overhead and improving cache locality",
      "make_shared avoids creating a control block entirely by embedding the reference count directly in the managed object",
      "make_shared uses stack allocation instead of heap, placing the control block in the caller's stack frame",
    ],
    correctIndex: 1,
    explanation:
      "Option A performs two heap allocations: one for the Widget and one for the control block. make_shared allocates a single memory block containing both. This halves the allocation count, improves cache locality, and reduces memory fragmentation. The trade-off: the memory can't be freed until all weak_ptrs are gone too.",
    link: "https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared.html",
  },
  {
    id: 407,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How can you minimize struct padding to reduce memory usage?",
    code: `struct Bad {\n    char a;    // 1 byte + 7 padding\n    double b;  // 8 bytes\n    char c;    // 1 byte + 7 padding\n};  // sizeof = 24\n\nstruct Good {\n    double b;  // 8 bytes\n    char a;    // 1 byte\n    char c;    // 1 byte + 6 padding\n};  // sizeof = 16`,
    options: [
      "Use bitfields for all members to control the exact number of bits each field occupies, since bitfields eliminate padding by specifying precise bit widths",
      "Always use #pragma pack(1) to eliminate all padding",
      "Order members from largest alignment to smallest",
      "Padding cannot be controlled by the programmer",
    ],
    correctIndex: 2,
    explanation:
      "By placing members in descending order of alignment (e.g., doubles first, then ints, then chars), you minimize the padding gaps between them. #pragma pack works but can cause misaligned access, which is slow or even crashes on some architectures.",
    link: "https://en.cppreference.com/w/cpp/language/object.html",
  },
  {
    id: 408,
    difficulty: "Medium",
    topic: "Under the Hood",
    question: "How does static_cast differ from dynamic_cast at the machine code level?",
    options: [
      "static_cast applies a compile-time offset",
      "static_cast is slower because it adds bounds checking and validates the pointer against the object's actual type at runtime, whereas dynamic_cast skips these checks for faster execution",
      "They generate identical machine code",
      "dynamic_cast is a compile-time operation resolved entirely by the compiler during type checking; static_cast is resolved at runtime using type metadata embedded in the vtable structure",
    ],
    correctIndex: 0,
    explanation:
      "static_cast compiles to a simple pointer adjustment (adding a constant offset) or nothing at all. It does no runtime checking. dynamic_cast generates a call to a runtime library function (like __dynamic_cast) that inspects RTTI data and may fail gracefully. This is why dynamic_cast is slower but safer.",
    link: "https://en.cppreference.com/w/cpp/language/dynamic_cast.html",
  },
  {
    id: 409,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "What is a thunk in the context of multiple inheritance virtual dispatch?",
    code: `class A { virtual void f(); };\nclass B { virtual void g(); };\nclass C : public A, public B {\n    void g() override;  // overrides B::g\n};`,
    options: [
      "A placeholder for unresolved virtual functions that triggers a linker error if the function is called without being overridden, acting as a compile-time guard against incomplete implementations in the derived class",
      "A small code stub that adjusts the this pointer by an offset before jumping to the actual function",
      "A compiler-generated error handler for failed casts that throws std::bad_cast when dynamic_cast detects an invalid conversion, serving as a safety mechanism in the runtime type-checking infrastructure",
      "A hash table entry in the vtable that maps a function signature string to the corresponding implementation address, using runtime string comparison to resolve overloaded virtual methods across the hierarchy",
    ],
    correctIndex: 1,
    explanation:
      "When C::g() is called through a B*, the this pointer points to B's sub-object (not the start of C). The thunk subtracts the offset to get a pointer to the full C object, then jumps to C::g(). B's vtable entry for g() points to this thunk, not directly to C::g().",
    link: "https://itanium-cxx-abi.github.io/cxx-abi/abi.html#vtable",
  },
  {
    id: 410,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does virtual inheritance affect the internal object layout?",
    code: `class A { int a; };\nclass B : virtual public A { int b; };\nclass C : virtual public A { int c; };\nclass D : public B, public C { int d; };`,
    options: [
      "A is heap-allocated separately and pointed to by B and C through shared pointers, forming a reference-counted virtual base that is automatically destroyed when both B and C release their references during destruction",
      "The compiler duplicates A but merges them at link time by combining identical symbols from B's and C's translation units, using linker-level deduplication similar to how COMDAT sections handle template instantiations",
      "A appears twice in D, just like non-virtual inheritance",
      "A appears once, placed at a dynamic offset. B and C each contain a vbase pointer that stores the offset to the shared A sub-object, because its position relative to B or C varies depending on the most-derived class",
    ],
    correctIndex: 3,
    explanation:
      "With virtual inheritance, the shared base A is placed at a dynamic offset (typically at the end of D). B and C cannot know A's offset at compile time (it depends on the full object), so they use a vbase offset (stored in or near their vtable) to find A at runtime. This extra indirection is the cost of virtual inheritance.",
    link: "https://itanium-cxx-abi.github.io/cxx-abi/abi.html#vtable",
  },
  {
    id: 411,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does the 'zero-cost exception' model work behind the scenes?",
    options: [
      "Exceptions are implemented as global error codes checked after every function call, with each call site testing a thread-local flag before proceeding",
      "The compiler generates side tables that map program counter ranges to cleanup actions. When an exception is thrown, the runtime walks the call stack, consulting these tables to find handlers and run destructors",
      "try/catch blocks use setjmp/longjmp on all platforms, saving and restoring the register state at each try entry point and catch handler",
      "Exceptions are syntactic sugar for return codes",
    ],
    correctIndex: 1,
    explanation:
      "Table-based exception handling (used on most modern platforms) generates no extra code on the normal (non-throwing) execution path -- hence 'zero-cost.' When a throw occurs, the runtime uses unwind tables (mapping PC ranges to cleanup actions and catch handlers) to walk the stack. The cost is paid only when exceptions are actually thrown.",
    link: "https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html",
  },
  {
    id: 412,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "What does the vtable look like for a class with virtual inheritance?",
    code: `class Base { virtual void f(); };\nclass Derived : virtual public Base {\n    void f() override;\n    virtual void g();\n};`,
    options: [
      "Two separate vtables that are merged at runtime into a single dispatch table when the most-derived object is constructed, with the runtime concatenating entries from both tables and updating all vptrs to point to the merged result",
      "No vtable is needed",
      "Same as non-virtual inheritance",
      "The vtable includes additional entries: a vbase offset, a top offset, and RTTI pointer, in addition to the normal virtual function pointers",
    ],
    correctIndex: 3,
    explanation:
      "Under the Itanium ABI, each vtable contains: the offset-to-top (for dynamic_cast), the RTTI pointer, virtual function pointers, AND for virtual bases, vbase offsets that tell the runtime where to find the virtual base sub-object relative to the current sub-object.",
    link: "https://itanium-cxx-abi.github.io/cxx-abi/abi.html#vtable",
  },
  {
    id: 413,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does std::function's small buffer optimization (SBO) work?",
    options: [
      "The callable is always stored on the stack of the caller, using alloca-style allocation that grows the current stack frame dynamically, meaning the std::function object becomes invalid once the creating function returns",
      "std::function always heap-allocates the stored callable, wrapping it in a polymorphic container managed by new/delete",
      "std::function contains a small inline buffer. If the callable fits, it is stored directly in the buffer. Larger callables trigger a heap allocation",
      "std::function uses a global callable pool that caches previously allocated wrappers and reuses them for new assignments, amortizing the cost of heap allocation across the program's lifetime by recycling freed entries",
    ],
    correctIndex: 2,
    explanation:
      "Like SSO for strings, std::function uses SBO: a small internal buffer avoids heap allocation for small callables. A function pointer or captureless lambda easily fits. A lambda capturing many variables may exceed the buffer and trigger a heap allocation. The threshold is implementation-defined.",
    link: "https://en.cppreference.com/w/cpp/utility/functional/function.html",
  },
  {
    id: 414,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "What is devirtualization and when can the compiler apply it?",
    code: `class Dog : public Animal {\npublic:\n    void speak() override { std::cout << "Woof"; }\n};\n\nDog d;\nd.speak();  // can the compiler skip the vtable?`,
    options: [
      "Never -- virtual calls always go through the vtable regardless of how much type information the compiler has available at compile time, because the standard mandates vtable-based dispatch for every call to a virtual function in the hierarchy",
      "Only when the function is marked final",
      "When the compiler can prove the exact dynamic type at compile time, it replaces the virtual call with a direct call or even inlines the function",
      "Only with link-time optimization enabled, because the compiler needs visibility across all translation units to prove the type is not overridden elsewhere",
    ],
    correctIndex: 2,
    explanation:
      "When the compiler knows the exact type (e.g., a local Dog object, not a Base* or Base&), it can devirtualize: replace the vtable lookup with a direct function call. The final keyword helps too -- if a class or function is final, no further override is possible, enabling devirtualization even through pointers.",
    link: "https://en.cppreference.com/w/cpp/language/final.html",
  },
  {
    id: 415,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "Why can virtual dispatch cause performance problems beyond the extra indirection?",
    options: [
      "Virtual functions use more registers because the this pointer and vtable index must be loaded before the call can be dispatched, and the extra register pressure may cause additional stack spills in tight loops",
      "Virtual functions disable all compiler optimizations on the call site, preventing inlining, constant propagation, and dead code elimination",
      "The vtable is locked with a mutex during dispatch to prevent data races when multiple threads call the same virtual function concurrently, adding synchronization overhead that serializes all virtual calls on the same object",
      "The indirect call through a vtable is hard for the CPU's branch predictor to speculate on, and calling functions scattered across memory causes instruction cache misses",
    ],
    correctIndex: 3,
    explanation:
      "The two main costs are: (1) branch prediction -- indirect calls (call through a pointer) are harder to predict than direct calls, causing pipeline stalls, and (2) instruction cache -- virtual functions from different classes may be scattered across memory, causing icache misses. On hot loops, this can significantly impact performance.",
    link: "https://en.cppreference.com/w/cpp/language/virtual.html",
  },
  {
    id: 416,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does std::tuple typically store its elements internally?",
    options: [
      "In a std::array of std::any objects, where each element uses type erasure to store its value and type information at runtime, with any_cast required to retrieve elements by their original type",
      "Using recursive inheritance or recursive composition",
      "In a hash map indexed by type, mapping each element's std::type_info to a type-erased storage slot in the tuple, with runtime lookup required for every std::get call on the tuple object",
      "In a flat struct with named members, where the compiler generates a unique field name for each tuple element based on its index position, similar to how anonymous structs name their fields internally",
    ],
    correctIndex: 1,
    explanation:
      "Most implementations use recursive inheritance: tuple<int, double, char> inherits from tuple<double, char>, which inherits from tuple<char>. Each level holds one element. EBO ensures empty types don't waste space. std::get<N> uses template recursion to access the Nth base class.",
    link: "https://en.cppreference.com/w/cpp/utility/tuple.html",
  },
  {
    id: 417,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does thread_local storage (TLS) work at the system level?",
    options: [
      "The OS/runtime maintains a per-thread data block. Each thread_local variable is at a fixed offset within this block, giving O(1) access per thread",
      "thread_local variables are stored in shared memory protected by mutexes that are acquired on each access to prevent data races between threads, adding synchronization overhead proportional to the number of concurrent threads",
      "Each thread gets a completely separate copy of the program's entire memory space, including code, stack, and global data segments",
      "The compiler transforms thread_local declarations into a std::map<thread_id, value> that is locked with a global mutex and searched on every variable access, making thread_local semantically equivalent to a guarded map",
    ],
    correctIndex: 0,
    explanation:
      "Modern OSes allocate a Thread Local Storage (TLS) block per thread. On x86-64, a segment register (typically %fs or %gs) points to the thread's TLS area. Accessing a thread_local variable compiles to a load at a fixed offset from the segment base -- nearly as fast as a regular global variable.",
    link: "https://en.cppreference.com/w/cpp/language/storage_duration.html",
  },
  {
    id: 418,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does std::any implement type erasure differently from std::function?",
    options: [
      "std::any stores values as void* with no type information, relying on the caller to cast back to the correct type without any safety checks",
      "std::any uses templates only, with no runtime overhead",
      "They are implemented identically",
      "std::any stores a type_info pointer plus either an inline buffer or a heap pointer. It uses virtual-like dispatch for copy, move, and destroy operations",
    ],
    correctIndex: 3,
    explanation:
      "std::any erases the type of its stored value. Internally it stores: a manager function (or vtable) that knows how to copy, move, and destroy the stored object, a type_info for any_cast type checking, and either inline storage (SBO) or a heap pointer for the actual object. any_cast checks type_info before returning.",
    link: "https://en.cppreference.com/w/cpp/utility/any.html",
  },
  {
    id: 419,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does a C++20 coroutine work internally?",
    options: [
      "Coroutines use OS threads under the hood",
      "The compiler transforms it into a regular function with callbacks, splitting the body at each co_await into separate continuation functions that are chained together",
      "Coroutines use setjmp/longjmp for context switching, saving the full register state and stack pointer at each suspend point for later restoration",
      "The compiler creates a coroutine frame containing the function's local variables, parameters, suspend point index, and the promise object. At each co_await/co_yield, the state is saved and control returns to the caller. Resumption restores the frame and jumps to the saved suspend point",
    ],
    correctIndex: 3,
    explanation:
      "The compiler transforms a coroutine into a state machine. The coroutine frame (like a stack frame, but heap-allocated so it outlives the caller) holds all local state. Each suspend point has an index. On resume, the runtime loads the frame and jumps to the right point. The compiler may optimize away the heap allocation (HALO optimization).",
    link: "https://en.cppreference.com/w/cpp/language/coroutines.html",
  },
  {
    id: 420,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "How does the free store (heap) allocator typically manage memory behind new/delete?",
    options: [
      "All heap memory is pre-allocated at program start and never grows",
      "It calls the OS for every single allocation and deallocation, issuing a system call such as mmap or sbrk each time new or delete is invoked",
      "The allocator maintains a data structure in user-space memory obtained from the OS in large chunks. new searches for a suitable free block; delete returns it to the free list. OS calls happen only when the pool is exhausted",
      "new/delete are implemented as no-ops on modern systems because the OS reclaims all process memory on exit, making explicit deallocation unnecessary",
    ],
    correctIndex: 2,
    explanation:
      "The C runtime's allocator (e.g., glibc's ptmalloc, jemalloc, tcmalloc) requests large memory regions from the OS and subdivides them. Common strategies: free lists (tracking freed blocks by size), buddy allocation (splitting/merging power-of-2 blocks), and thread-local caches to reduce contention. This is why small allocations are fast -- they rarely need OS calls.",
    link: "https://en.cppreference.com/w/cpp/memory/new/operator_new.html",
  },
  {
    id: 421,
    difficulty: "Hard",
    topic: "Under the Hood",
    question: "What does the 'offset-to-top' value in a vtable entry enable?",
    code: `class A { virtual void f(); };\nclass B { virtual void g(); };\nclass C : public A, public B { void f() override; void g() override; };`,
    options: [
      "It stores the offset from the vtable to the RTTI data so that typeid can locate the type_info structure from any vtable pointer, enabling runtime type identification without requiring a separate RTTI lookup table",
      "It stores the displacement from the current sub-object to the beginning of the most-derived object",
      "It stores the total size of the object so the runtime can compute how much memory to deallocate when delete is called, allowing the allocator to free the correct number of bytes for polymorphic objects",
      "It stores the number of virtual functions in the class, allowing the runtime to bounds-check vtable indices during dispatch and detect out-of-range slot access that would otherwise cause undefined behavior",
    ],
    correctIndex: 1,
    explanation:
      "When you have a B* pointing to the B sub-object inside a C, dynamic_cast needs to find the start of the full C object. The offset-to-top (stored in B's vtable) gives the distance from B's sub-object back to the top of C. This enables cross-casts (e.g., dynamic_cast<A*> from a B*) by first finding the complete object.",
    link: "https://itanium-cxx-abi.github.io/cxx-abi/abi.html#vtable",
  },
];
