import type { Flashcard } from "./types";

export const flashcards: Flashcard[] = [
  {
    id: 1,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Newton's Second Law (Force)",
    back: "F = ma",
    note: "Force equals mass times linear acceleration. The foundation of all rigid body dynamics.",
  },
  {
    id: 2,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Linear acceleration from force",
    back: "a = \\frac{F}{m}",
    note: "In engines storing inverse mass: a = F \\cdot m^{-1}, avoiding division each frame.",
  },
  {
    id: 3,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Torque equation (rotational analog of F = ma)",
    back: "\\tau = I\\alpha",
    note: "Torque equals the inertia tensor times angular acceleration.",
  },
  {
    id: 4,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Angular acceleration from torque",
    back: "\\alpha = I^{-1}\\tau",
    note: "Computed each frame using the pre-stored inverse inertia tensor.",
  },
  {
    id: 5,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Torque from an off-centre force",
    back: "\\tau = r \\times F",
    note: "r is the vector from the centre of mass to the point of force application.",
  },
  {
    id: 6,
    topic: "Rigid Bodies",
    category: "Spaces & Conventions",
    front: "Inertia tensor: body space → world space",
    back: "I_{world} = R \\, I_{body} \\, R^T",
    note: "A similarity transform that rotates the inertia tensor into the global frame.",
  },
  {
    id: 7,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Semi-implicit Euler: velocity update",
    back: "v(t + \\Delta t) = v(t) + a \\cdot \\Delta t",
    note: "Velocity is updated FIRST using the current acceleration.",
  },
  {
    id: 8,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Semi-implicit Euler: position update",
    back: "x(t + \\Delta t) = x(t) + v(t + \\Delta t) \\cdot \\Delta t",
    note: "Uses the NEWLY computed velocity (not the old one) — this is what makes it symplectic.",
  },
  {
    id: 9,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Quaternion orientation update",
    back: "q_{new} = q + \\frac{\\Delta t}{2} \\, [0,\\, \\omega] \\cdot q",
    note: "[0, ω] is a pure quaternion. The result must be normalized back to unit length.",
  },
  {
    id: 10,
    topic: "Rigid Bodies",
    category: "Damping",
    front: "Exponential damping",
    back: "v_{damped} = v \\cdot e^{-k \\, \\Delta t}",
    note: "Timestep-independent — produces the same decay regardless of Δt, unlike the linear form v·(1 − k·Δt).",
  },
];
