import type { Flashcard } from "./types";

export const flashcards: Flashcard[] = [
  {
    id: 1,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Newton's Second Law (Force)",
    back: "F = ma",
    note: "Force equals mass times linear acceleration. The foundation of all rigid body dynamics.",
  },
  {
    id: 2,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Linear acceleration from force",
    back: "a = \\frac{F}{m}",
    note: "In engines storing inverse mass: a = F \\cdot m^{-1}, avoiding division each frame.",
  },
  {
    id: 3,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Torque equation (rotational analog of F = ma)",
    back: "\\tau = I\\alpha",
    note: "Torque equals the inertia tensor times angular acceleration.",
  },
  {
    id: 4,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Angular acceleration from torque",
    back: "\\alpha = I^{-1}\\tau",
    note: "Computed each frame using the pre-stored inverse inertia tensor.",
  },
  {
    id: 5,
    topic: "Rigid Bodies",
    category: "Forces & Torques",
    front: "Torque from an off-centre force",
    back: "\\tau = r \\times F",
    note: "r is the vector from the centre of mass to the point of force application.",
  },
  {
    id: 6,
    topic: "Rigid Bodies",
    category: "Spaces & Conventions",
    front: "Inertia tensor: body space → world space",
    back: "I_{world} = R \\, I_{body} \\, R^T",
    note: "A similarity transform that rotates the inertia tensor into the global frame.",
  },
  {
    id: 7,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Semi-implicit Euler: velocity update",
    back: "v(t + \\Delta t) = v(t) + a \\cdot \\Delta t",
    note: "Velocity is updated FIRST using the current acceleration.",
  },
  {
    id: 8,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Semi-implicit Euler: position update",
    back: "x(t + \\Delta t) = x(t) + v(t + \\Delta t) \\cdot \\Delta t",
    note: "Uses the NEWLY computed velocity (not the old one) — this is what makes it symplectic.",
  },
  {
    id: 9,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Quaternion orientation update",
    back: "q_{new} = q + \\frac{\\Delta t}{2} \\, [0,\\, \\omega] \\cdot q",
    note: "[0, ω] is a pure quaternion. The result must be normalized back to unit length.",
  },
  {
    id: 10,
    topic: "Rigid Bodies",
    category: "Damping",
    front: "Exponential damping",
    back: "v_{damped} = v \\cdot e^{-k \\, \\Delta t}",
    note: "Timestep-independent — produces the same decay regardless of Δt, unlike the linear form v·(1 − k·Δt).",
  },
  // ── Classic (Explicit) Euler ──
  {
    id: 11,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Classic Euler: position update",
    back: "x(t + \\Delta t) = x(t) + v(t) \\cdot \\Delta t",
    note: "Uses the OLD velocity to update position. Simple but gains energy over time and is unstable for stiff systems.",
  },
  {
    id: 12,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Classic Euler: velocity update",
    back: "v(t + \\Delta t) = v(t) + a(t) \\cdot \\Delta t",
    note: "Velocity is updated using the current acceleration. In classic Euler, position is updated BEFORE this step (using v_old).",
  },
  // ── Verlet Integration ──
  {
    id: 13,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Störmer-Verlet: position update",
    back: "x(t + \\Delta t) = 2x(t) - x(t - \\Delta t) + a(t) \\cdot \\Delta t^2",
    note: "Requires no explicit velocity — uses current and previous positions. Second-order accurate and symplectic.",
  },
  {
    id: 14,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Velocity Verlet: position update",
    back: "x(t + \\Delta t) = x(t) + v(t) \\cdot \\Delta t + \\frac{1}{2} a(t) \\cdot \\Delta t^2",
    note: "First half of velocity Verlet — advances position using current velocity and acceleration.",
  },
  {
    id: 15,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Velocity Verlet: velocity update",
    back: "v(t + \\Delta t) = v(t) + \\frac{1}{2}\\bigl(a(t) + a(t + \\Delta t)\\bigr) \\cdot \\Delta t",
    note: "Averages the old and new accelerations. Requires computing a(t+Δt) after the position update.",
  },
  {
    id: 16,
    topic: "Rigid Bodies",
    category: "Integration",
    front: "Verlet: recover velocity from positions",
    back: "v(t) \\approx \\frac{x(t + \\Delta t) - x(t - \\Delta t)}{2 \\, \\Delta t}",
    note: "Central difference approximation — used when Störmer-Verlet needs velocity for damping or collisions.",
  },
];
