import type { LearningPath } from "./types";

export const learningPaths: LearningPath[] = [
  {
    id: "ownership-problem",
    title: "The Ownership Problem",
    description: "Who is responsible for this pointer? Eight programs that trace the tension between allocation and deallocation.",
    programIds: [13, 54, 14, 17, 64, 16, 19, 21],
  },
  {
    id: "smart-pointer-mastery",
    title: "Smart Pointer Mastery",
    description: "From unique_ptr to shared_ptr to weak_ptr — ten programs that test whether you truly understand automatic lifetime.",
    programIds: [23, 25, 27, 29, 31, 24, 26, 28, 30, 32],
  },
  {
    id: "iterator-invalidation",
    title: "Iterator Invalidation Rules",
    description: "Containers change shape. Nine programs that ask: is this iterator still pointing where you think?",
    programIds: [1, 74, 77, 76, 75, 78, 79, 80, 83],
  },
  {
    id: "c-string-archaeology",
    title: "C String Archaeology",
    description: "Null terminators, buffer sizes, and pointer arithmetic — seven programs from the era before std::string.",
    programIds: [18, 55, 70, 60, 73, 67, 72],
  },
  {
    id: "object-lifecycle",
    title: "Object Lifecycle",
    description: "Construction, copying, assignment, destruction — eight programs that follow an object from birth to death.",
    programIds: [44, 46, 49, 47, 11, 66, 5, 15],
  },
  {
    id: "operator-overloading",
    title: "Operator Overloading Pitfalls",
    description: "Making + and = and < do the right thing is harder than it looks. Eight programs that prove it.",
    programIds: [34, 36, 38, 35, 39, 43, 41, 42],
  },
  {
    id: "resource-guards",
    title: "Resource Guards",
    description: "Files, buffers, connections — ten programs where something is acquired and must eventually be released.",
    programIds: [84, 85, 86, 87, 88, 90, 89, 91, 92, 93],
  },
  {
    id: "value-in-motion",
    title: "Value in Motion",
    description: "What does it mean to move an object? Ten programs exploring transfer of ownership and the state left behind.",
    programIds: [94, 95, 96, 97, 98, 99, 100, 101, 102, 103],
  },
  {
    id: "when-things-throw",
    title: "When Things Throw",
    description: "Exceptions unwind the stack — but what about the promises your code already made? Ten programs on the edge of failure.",
    programIds: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113],
  },
  {
    id: "algorithm-contracts",
    title: "Algorithm Contracts",
    description: "Every STL algorithm has preconditions. Ten programs that call the algorithm correctly — almost.",
    programIds: [114, 115, 116, 117, 118, 119, 120, 121, 122, 123],
  },
  {
    id: "shared-state",
    title: "Shared State",
    description: "Multiple threads, one truth. Ten programs about what happens when concurrent code disagrees on reality.",
    programIds: [124, 125, 126, 127, 128, 130, 129, 131, 132, 133],
  },
  {
    id: "template-traps",
    title: "Template Traps",
    description: "Type deduction, SFINAE, and instantiation surprises — ten programs that compile but don't do what you expect.",
    programIds: [8, 134, 135, 136, 137, 138, 139, 140, 141, 142],
  },
  {
    id: "text-processing",
    title: "Text Processing",
    description: "Splitting, searching, encoding — ten programs where string handling goes subtly wrong.",
    programIds: [234, 235, 236, 237, 238, 239, 240, 241, 242, 243],
  },
  {
    id: "pointer-discipline",
    title: "Pointer Discipline",
    description: "Dangling pointers, null dereferences, and address confusion — ten programs that test your pointer intuition.",
    programIds: [244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
  },
  {
    id: "silent-conversions",
    title: "Silent Conversions",
    description: "Narrowing, truncation, and sign confusion — ten programs where the compiler helpfully destroys your data.",
    programIds: [254, 255, 256, 257, 258, 259, 260, 261, 262, 263],
  },
  {
    id: "build-it-yourself",
    title: "Build It Yourself",
    description: "Stacks, trees, heaps, and graphs — ten hand-rolled data structures with bugs lurking in the logic.",
    programIds: [264, 265, 266, 267, 268, 269, 270, 271, 272, 273],
  },
  {
    id: "construction-zone",
    title: "Construction Zone",
    description: "Initialization order, brace semantics, and constructor delegation — ten programs where objects start life wrong.",
    programIds: [274, 275, 276, 277, 278, 279, 280, 281, 282, 283],
  },
  {
    id: "thread-hazards",
    title: "Thread Hazards",
    description: "Deadlocks, data races, and lock-free illusions — ten more concurrency programs that look correct until they aren't.",
    programIds: [284, 285, 286, 287, 288, 289, 290, 291, 292, 293],
  },
  {
    id: "memory-forensics",
    title: "Memory Forensics",
    description: "Leaks, dangling pointers, and double frees — ten programs that expose what happens when you manage memory by hand.",
    programIds: [224, 225, 226, 227, 228, 229, 230, 231, 232, 233],
  },
  {
    id: "fundamentals-gauntlet",
    title: "Fundamentals Gauntlet",
    description: "Integer division, switch fallthrough, and operator precedence — ten beginner-level programs with traps hiding in plain sight.",
    programIds: [3, 10, 214, 215, 216, 217, 218, 219, 220, 221],
  },
  {
    id: "language-traps",
    title: "Language Traps",
    description: "Most vexing parse, operator precedence, and name hiding — ten programs that exploit the dark corners of C++ syntax.",
    programIds: [294, 295, 296, 297, 298, 299, 300, 301, 302, 303],
  },
  {
    id: "stdlib-surprises",
    title: "Standard Library Surprises",
    description: "Optional misuse, invalid comparators, and silent copies — ten programs where the standard library doesn't do what you assumed.",
    programIds: [304, 305, 306, 307, 308, 309, 310, 311, 312, 313],
  },
  {
    id: "object-anatomy",
    title: "Object Anatomy",
    description: "Slicing, hidden overloads, and suppressed moves — ten programs that reveal how C++ objects really behave.",
    programIds: [314, 315, 316, 317, 318, 319, 320, 321, 322, 323],
  },
  {
    id: "concurrency-patterns",
    title: "Concurrency Patterns",
    description: "Memory ordering, false sharing, and lock-free pitfalls — ten programs that push beyond basic mutexes.",
    programIds: [324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
  },
  {
    id: "template-depths",
    title: "Template Depths",
    description: "SFINAE failures, deduction traps, and double-forwarding — ten programs that test your template metaprogramming instincts.",
    programIds: [334, 335, 336, 337, 338, 339, 340, 341, 342, 343],
  },
  {
    id: "lifetime-puzzles",
    title: "Lifetime Puzzles",
    description: "Dangling captures, temporary extension rules, and thread-local destruction — ten programs about when things stop existing.",
    programIds: [344, 345, 346, 347, 348, 349, 350, 351, 352, 353],
  },
];
